// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/liujit/shop/server/lib/data/models"
)

func newGoodsSpec(db *gorm.DB, opts ...gen.DOOption) goodsSpec {
	_goodsSpec := goodsSpec{}

	_goodsSpec.goodsSpecDo.UseDB(db, opts...)
	_goodsSpec.goodsSpecDo.UseModel(&models.GoodsSpec{})

	tableName := _goodsSpec.goodsSpecDo.TableName()
	_goodsSpec.ALL = field.NewAsterisk(tableName)
	_goodsSpec.ID = field.NewInt64(tableName, "id")
	_goodsSpec.GoodsID = field.NewInt64(tableName, "goods_id")
	_goodsSpec.Name = field.NewString(tableName, "name")
	_goodsSpec.Item = field.NewString(tableName, "item")
	_goodsSpec.Sort = field.NewInt32(tableName, "sort")
	_goodsSpec.DeletedAt = field.NewField(tableName, "deleted_at")

	_goodsSpec.fillFieldMap()

	return _goodsSpec
}

// goodsSpec 商品规格信息
type goodsSpec struct {
	goodsSpecDo goodsSpecDo

	ALL       field.Asterisk
	ID        field.Int64  // 商品规格ID
	GoodsID   field.Int64  // 商品ID
	Name      field.String // 规格标题
	Item      field.String // 规格内容
	Sort      field.Int32  // 排序
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (g goodsSpec) Table(newTableName string) *goodsSpec {
	g.goodsSpecDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsSpec) As(alias string) *goodsSpec {
	g.goodsSpecDo.DO = *(g.goodsSpecDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsSpec) updateTableName(table string) *goodsSpec {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.GoodsID = field.NewInt64(table, "goods_id")
	g.Name = field.NewString(table, "name")
	g.Item = field.NewString(table, "item")
	g.Sort = field.NewInt32(table, "sort")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *goodsSpec) WithContext(ctx context.Context) *goodsSpecDo {
	return g.goodsSpecDo.WithContext(ctx)
}

func (g goodsSpec) TableName() string { return g.goodsSpecDo.TableName() }

func (g goodsSpec) Alias() string { return g.goodsSpecDo.Alias() }

func (g goodsSpec) Columns(cols ...field.Expr) gen.Columns { return g.goodsSpecDo.Columns(cols...) }

func (g *goodsSpec) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsSpec) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 6)
	g.fieldMap["id"] = g.ID
	g.fieldMap["goods_id"] = g.GoodsID
	g.fieldMap["name"] = g.Name
	g.fieldMap["item"] = g.Item
	g.fieldMap["sort"] = g.Sort
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g goodsSpec) clone(db *gorm.DB) goodsSpec {
	g.goodsSpecDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goodsSpec) replaceDB(db *gorm.DB) goodsSpec {
	g.goodsSpecDo.ReplaceDB(db)
	return g
}

type goodsSpecDo struct{ gen.DO }

func (g goodsSpecDo) Debug() *goodsSpecDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsSpecDo) WithContext(ctx context.Context) *goodsSpecDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsSpecDo) ReadDB() *goodsSpecDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsSpecDo) WriteDB() *goodsSpecDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsSpecDo) Session(config *gorm.Session) *goodsSpecDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsSpecDo) Clauses(conds ...clause.Expression) *goodsSpecDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsSpecDo) Returning(value interface{}, columns ...string) *goodsSpecDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsSpecDo) Not(conds ...gen.Condition) *goodsSpecDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsSpecDo) Or(conds ...gen.Condition) *goodsSpecDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsSpecDo) Select(conds ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsSpecDo) Where(conds ...gen.Condition) *goodsSpecDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsSpecDo) Order(conds ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsSpecDo) Distinct(cols ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsSpecDo) Omit(cols ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsSpecDo) Join(table schema.Tabler, on ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsSpecDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsSpecDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsSpecDo) Group(cols ...field.Expr) *goodsSpecDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsSpecDo) Having(conds ...gen.Condition) *goodsSpecDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsSpecDo) Limit(limit int) *goodsSpecDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsSpecDo) Offset(offset int) *goodsSpecDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsSpecDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsSpecDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsSpecDo) Unscoped() *goodsSpecDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsSpecDo) Create(values ...*models.GoodsSpec) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsSpecDo) CreateInBatches(values []*models.GoodsSpec, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsSpecDo) Save(values ...*models.GoodsSpec) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsSpecDo) First() (*models.GoodsSpec, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSpec), nil
	}
}

func (g goodsSpecDo) Take() (*models.GoodsSpec, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSpec), nil
	}
}

func (g goodsSpecDo) Last() (*models.GoodsSpec, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSpec), nil
	}
}

func (g goodsSpecDo) Find() ([]*models.GoodsSpec, error) {
	result, err := g.DO.Find()
	return result.([]*models.GoodsSpec), err
}

func (g goodsSpecDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GoodsSpec, err error) {
	buf := make([]*models.GoodsSpec, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsSpecDo) FindInBatches(result *[]*models.GoodsSpec, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsSpecDo) Attrs(attrs ...field.AssignExpr) *goodsSpecDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsSpecDo) Assign(attrs ...field.AssignExpr) *goodsSpecDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsSpecDo) Joins(fields ...field.RelationField) *goodsSpecDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsSpecDo) Preload(fields ...field.RelationField) *goodsSpecDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsSpecDo) FirstOrInit() (*models.GoodsSpec, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSpec), nil
	}
}

func (g goodsSpecDo) FirstOrCreate() (*models.GoodsSpec, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsSpec), nil
	}
}

func (g goodsSpecDo) FindByPage(offset int, limit int) (result []*models.GoodsSpec, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsSpecDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsSpecDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsSpecDo) Delete(models ...*models.GoodsSpec) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsSpecDo) withDO(do gen.Dao) *goodsSpecDo {
	g.DO = *do.(*gen.DO)
	return g
}
