// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/liujit/shop/server/lib/data/models"
)

func newGoods(db *gorm.DB, opts ...gen.DOOption) goods {
	_goods := goods{}

	_goods.goodsDo.UseDB(db, opts...)
	_goods.goodsDo.UseModel(&models.Goods{})

	tableName := _goods.goodsDo.TableName()
	_goods.ALL = field.NewAsterisk(tableName)
	_goods.ID = field.NewInt64(tableName, "id")
	_goods.CategoryID = field.NewInt64(tableName, "category_id")
	_goods.Name = field.NewString(tableName, "name")
	_goods.Desc = field.NewString(tableName, "desc")
	_goods.Picture = field.NewString(tableName, "picture")
	_goods.Banner = field.NewString(tableName, "banner")
	_goods.Detail = field.NewString(tableName, "detail")
	_goods.Price = field.NewInt64(tableName, "price")
	_goods.DiscountPrice = field.NewInt64(tableName, "discount_price")
	_goods.InitSaleNum = field.NewInt64(tableName, "init_sale_num")
	_goods.RealSaleNum = field.NewInt64(tableName, "real_sale_num")
	_goods.Status = field.NewInt32(tableName, "status")
	_goods.CreatedBy = field.NewInt64(tableName, "created_by")
	_goods.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_goods.CreatedAt = field.NewTime(tableName, "created_at")
	_goods.UpdatedAt = field.NewTime(tableName, "updated_at")
	_goods.DeletedAt = field.NewField(tableName, "deleted_at")

	_goods.fillFieldMap()

	return _goods
}

// goods 商品信息
type goods struct {
	goodsDo goodsDo

	ALL           field.Asterisk
	ID            field.Int64  // 商品ID
	CategoryID    field.Int64  // 商品分类ID
	Name          field.String // 商品名称
	Desc          field.String // 商品描述
	Picture       field.String // 商品图片
	Banner        field.String // 商品视频
	Detail        field.String // 商品详情
	Price         field.Int64  // 当前价格(分)
	DiscountPrice field.Int64  // 折扣价格（分）
	InitSaleNum   field.Int64  // 初始销量
	RealSaleNum   field.Int64  // 真实销售数量
	Status        field.Int32  // 状态：枚举【GoodsStatus】
	CreatedBy     field.Int64  // 创建人ID
	UpdatedBy     field.Int64  // 更新人ID
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 更新时间
	DeletedAt     field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (g goods) Table(newTableName string) *goods {
	g.goodsDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goods) As(alias string) *goods {
	g.goodsDo.DO = *(g.goodsDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goods) updateTableName(table string) *goods {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.CategoryID = field.NewInt64(table, "category_id")
	g.Name = field.NewString(table, "name")
	g.Desc = field.NewString(table, "desc")
	g.Picture = field.NewString(table, "picture")
	g.Banner = field.NewString(table, "banner")
	g.Detail = field.NewString(table, "detail")
	g.Price = field.NewInt64(table, "price")
	g.DiscountPrice = field.NewInt64(table, "discount_price")
	g.InitSaleNum = field.NewInt64(table, "init_sale_num")
	g.RealSaleNum = field.NewInt64(table, "real_sale_num")
	g.Status = field.NewInt32(table, "status")
	g.CreatedBy = field.NewInt64(table, "created_by")
	g.UpdatedBy = field.NewInt64(table, "updated_by")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *goods) WithContext(ctx context.Context) *goodsDo { return g.goodsDo.WithContext(ctx) }

func (g goods) TableName() string { return g.goodsDo.TableName() }

func (g goods) Alias() string { return g.goodsDo.Alias() }

func (g goods) Columns(cols ...field.Expr) gen.Columns { return g.goodsDo.Columns(cols...) }

func (g *goods) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goods) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 17)
	g.fieldMap["id"] = g.ID
	g.fieldMap["category_id"] = g.CategoryID
	g.fieldMap["name"] = g.Name
	g.fieldMap["desc"] = g.Desc
	g.fieldMap["picture"] = g.Picture
	g.fieldMap["banner"] = g.Banner
	g.fieldMap["detail"] = g.Detail
	g.fieldMap["price"] = g.Price
	g.fieldMap["discount_price"] = g.DiscountPrice
	g.fieldMap["init_sale_num"] = g.InitSaleNum
	g.fieldMap["real_sale_num"] = g.RealSaleNum
	g.fieldMap["status"] = g.Status
	g.fieldMap["created_by"] = g.CreatedBy
	g.fieldMap["updated_by"] = g.UpdatedBy
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g goods) clone(db *gorm.DB) goods {
	g.goodsDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goods) replaceDB(db *gorm.DB) goods {
	g.goodsDo.ReplaceDB(db)
	return g
}

type goodsDo struct{ gen.DO }

func (g goodsDo) Debug() *goodsDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsDo) WithContext(ctx context.Context) *goodsDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsDo) ReadDB() *goodsDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsDo) WriteDB() *goodsDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsDo) Session(config *gorm.Session) *goodsDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsDo) Clauses(conds ...clause.Expression) *goodsDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsDo) Returning(value interface{}, columns ...string) *goodsDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsDo) Not(conds ...gen.Condition) *goodsDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsDo) Or(conds ...gen.Condition) *goodsDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsDo) Select(conds ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsDo) Where(conds ...gen.Condition) *goodsDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsDo) Order(conds ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsDo) Distinct(cols ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsDo) Omit(cols ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsDo) Join(table schema.Tabler, on ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsDo) Group(cols ...field.Expr) *goodsDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsDo) Having(conds ...gen.Condition) *goodsDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsDo) Limit(limit int) *goodsDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsDo) Offset(offset int) *goodsDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsDo) Unscoped() *goodsDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsDo) Create(values ...*models.Goods) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsDo) CreateInBatches(values []*models.Goods, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsDo) Save(values ...*models.Goods) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsDo) First() (*models.Goods, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Goods), nil
	}
}

func (g goodsDo) Take() (*models.Goods, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Goods), nil
	}
}

func (g goodsDo) Last() (*models.Goods, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Goods), nil
	}
}

func (g goodsDo) Find() ([]*models.Goods, error) {
	result, err := g.DO.Find()
	return result.([]*models.Goods), err
}

func (g goodsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Goods, err error) {
	buf := make([]*models.Goods, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsDo) FindInBatches(result *[]*models.Goods, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsDo) Attrs(attrs ...field.AssignExpr) *goodsDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsDo) Assign(attrs ...field.AssignExpr) *goodsDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsDo) Joins(fields ...field.RelationField) *goodsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsDo) Preload(fields ...field.RelationField) *goodsDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsDo) FirstOrInit() (*models.Goods, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Goods), nil
	}
}

func (g goodsDo) FirstOrCreate() (*models.Goods, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Goods), nil
	}
}

func (g goodsDo) FindByPage(offset int, limit int) (result []*models.Goods, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsDo) Delete(models ...*models.Goods) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsDo) withDO(do gen.Dao) *goodsDo {
	g.DO = *do.(*gen.DO)
	return g
}
