// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/liujit/shop/server/lib/data/models"
)

func newGoodsCategory(db *gorm.DB, opts ...gen.DOOption) goodsCategory {
	_goodsCategory := goodsCategory{}

	_goodsCategory.goodsCategoryDo.UseDB(db, opts...)
	_goodsCategory.goodsCategoryDo.UseModel(&models.GoodsCategory{})

	tableName := _goodsCategory.goodsCategoryDo.TableName()
	_goodsCategory.ALL = field.NewAsterisk(tableName)
	_goodsCategory.ID = field.NewInt64(tableName, "id")
	_goodsCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_goodsCategory.Path = field.NewString(tableName, "path")
	_goodsCategory.Picture = field.NewString(tableName, "picture")
	_goodsCategory.Name = field.NewString(tableName, "name")
	_goodsCategory.Sort = field.NewInt32(tableName, "sort")
	_goodsCategory.Status = field.NewInt32(tableName, "status")
	_goodsCategory.CreatedBy = field.NewInt64(tableName, "created_by")
	_goodsCategory.UpdatedBy = field.NewInt64(tableName, "updated_by")
	_goodsCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_goodsCategory.UpdatedAt = field.NewTime(tableName, "updated_at")
	_goodsCategory.DeletedAt = field.NewField(tableName, "deleted_at")

	_goodsCategory.fillFieldMap()

	return _goodsCategory
}

// goodsCategory 商品分类信息
type goodsCategory struct {
	goodsCategoryDo goodsCategoryDo

	ALL       field.Asterisk
	ID        field.Int64  // 商品分类ID
	ParentID  field.Int64  // 父级商品分类ID
	Path      field.String // 商品分类路径
	Picture   field.String // 商品分类图片
	Name      field.String // 商品分类名称
	Sort      field.Int32  // 排序
	Status    field.Int32  // 状态：枚举【Status】
	CreatedBy field.Int64  // 创建人ID
	UpdatedBy field.Int64  // 更新人ID
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (g goodsCategory) Table(newTableName string) *goodsCategory {
	g.goodsCategoryDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goodsCategory) As(alias string) *goodsCategory {
	g.goodsCategoryDo.DO = *(g.goodsCategoryDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goodsCategory) updateTableName(table string) *goodsCategory {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt64(table, "id")
	g.ParentID = field.NewInt64(table, "parent_id")
	g.Path = field.NewString(table, "path")
	g.Picture = field.NewString(table, "picture")
	g.Name = field.NewString(table, "name")
	g.Sort = field.NewInt32(table, "sort")
	g.Status = field.NewInt32(table, "status")
	g.CreatedBy = field.NewInt64(table, "created_by")
	g.UpdatedBy = field.NewInt64(table, "updated_by")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")

	g.fillFieldMap()

	return g
}

func (g *goodsCategory) WithContext(ctx context.Context) *goodsCategoryDo {
	return g.goodsCategoryDo.WithContext(ctx)
}

func (g goodsCategory) TableName() string { return g.goodsCategoryDo.TableName() }

func (g goodsCategory) Alias() string { return g.goodsCategoryDo.Alias() }

func (g goodsCategory) Columns(cols ...field.Expr) gen.Columns {
	return g.goodsCategoryDo.Columns(cols...)
}

func (g *goodsCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goodsCategory) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 12)
	g.fieldMap["id"] = g.ID
	g.fieldMap["parent_id"] = g.ParentID
	g.fieldMap["path"] = g.Path
	g.fieldMap["picture"] = g.Picture
	g.fieldMap["name"] = g.Name
	g.fieldMap["sort"] = g.Sort
	g.fieldMap["status"] = g.Status
	g.fieldMap["created_by"] = g.CreatedBy
	g.fieldMap["updated_by"] = g.UpdatedBy
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
}

func (g goodsCategory) clone(db *gorm.DB) goodsCategory {
	g.goodsCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goodsCategory) replaceDB(db *gorm.DB) goodsCategory {
	g.goodsCategoryDo.ReplaceDB(db)
	return g
}

type goodsCategoryDo struct{ gen.DO }

func (g goodsCategoryDo) Debug() *goodsCategoryDo {
	return g.withDO(g.DO.Debug())
}

func (g goodsCategoryDo) WithContext(ctx context.Context) *goodsCategoryDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goodsCategoryDo) ReadDB() *goodsCategoryDo {
	return g.Clauses(dbresolver.Read)
}

func (g goodsCategoryDo) WriteDB() *goodsCategoryDo {
	return g.Clauses(dbresolver.Write)
}

func (g goodsCategoryDo) Session(config *gorm.Session) *goodsCategoryDo {
	return g.withDO(g.DO.Session(config))
}

func (g goodsCategoryDo) Clauses(conds ...clause.Expression) *goodsCategoryDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goodsCategoryDo) Returning(value interface{}, columns ...string) *goodsCategoryDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goodsCategoryDo) Not(conds ...gen.Condition) *goodsCategoryDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goodsCategoryDo) Or(conds ...gen.Condition) *goodsCategoryDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goodsCategoryDo) Select(conds ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goodsCategoryDo) Where(conds ...gen.Condition) *goodsCategoryDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goodsCategoryDo) Order(conds ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goodsCategoryDo) Distinct(cols ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goodsCategoryDo) Omit(cols ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goodsCategoryDo) Join(table schema.Tabler, on ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goodsCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goodsCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goodsCategoryDo) Group(cols ...field.Expr) *goodsCategoryDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goodsCategoryDo) Having(conds ...gen.Condition) *goodsCategoryDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goodsCategoryDo) Limit(limit int) *goodsCategoryDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goodsCategoryDo) Offset(offset int) *goodsCategoryDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goodsCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *goodsCategoryDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goodsCategoryDo) Unscoped() *goodsCategoryDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goodsCategoryDo) Create(values ...*models.GoodsCategory) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goodsCategoryDo) CreateInBatches(values []*models.GoodsCategory, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goodsCategoryDo) Save(values ...*models.GoodsCategory) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goodsCategoryDo) First() (*models.GoodsCategory, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsCategory), nil
	}
}

func (g goodsCategoryDo) Take() (*models.GoodsCategory, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsCategory), nil
	}
}

func (g goodsCategoryDo) Last() (*models.GoodsCategory, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsCategory), nil
	}
}

func (g goodsCategoryDo) Find() ([]*models.GoodsCategory, error) {
	result, err := g.DO.Find()
	return result.([]*models.GoodsCategory), err
}

func (g goodsCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.GoodsCategory, err error) {
	buf := make([]*models.GoodsCategory, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goodsCategoryDo) FindInBatches(result *[]*models.GoodsCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goodsCategoryDo) Attrs(attrs ...field.AssignExpr) *goodsCategoryDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goodsCategoryDo) Assign(attrs ...field.AssignExpr) *goodsCategoryDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goodsCategoryDo) Joins(fields ...field.RelationField) *goodsCategoryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goodsCategoryDo) Preload(fields ...field.RelationField) *goodsCategoryDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goodsCategoryDo) FirstOrInit() (*models.GoodsCategory, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsCategory), nil
	}
}

func (g goodsCategoryDo) FirstOrCreate() (*models.GoodsCategory, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.GoodsCategory), nil
	}
}

func (g goodsCategoryDo) FindByPage(offset int, limit int) (result []*models.GoodsCategory, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goodsCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goodsCategoryDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goodsCategoryDo) Delete(models ...*models.GoodsCategory) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goodsCategoryDo) withDO(do gen.Dao) *goodsCategoryDo {
	g.DO = *do.(*gen.DO)
	return g
}
