// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitee.com/liujit/shop/server/lib/data/models"
)

func newOrderPayment(db *gorm.DB, opts ...gen.DOOption) orderPayment {
	_orderPayment := orderPayment{}

	_orderPayment.orderPaymentDo.UseDB(db, opts...)
	_orderPayment.orderPaymentDo.UseModel(&models.OrderPayment{})

	tableName := _orderPayment.orderPaymentDo.TableName()
	_orderPayment.ALL = field.NewAsterisk(tableName)
	_orderPayment.ID = field.NewInt64(tableName, "id")
	_orderPayment.OrderID = field.NewInt64(tableName, "order_id")
	_orderPayment.OrderNo = field.NewString(tableName, "order_no")
	_orderPayment.ThirdOrderNo = field.NewString(tableName, "third_order_no")
	_orderPayment.TradeType = field.NewString(tableName, "trade_type")
	_orderPayment.TradeState = field.NewString(tableName, "trade_state")
	_orderPayment.TradeStateDesc = field.NewString(tableName, "trade_state_desc")
	_orderPayment.BankType = field.NewString(tableName, "bank_type")
	_orderPayment.SuccessTime = field.NewTime(tableName, "success_time")
	_orderPayment.Payer = field.NewString(tableName, "payer")
	_orderPayment.Amount = field.NewString(tableName, "amount")
	_orderPayment.SceneInfo = field.NewString(tableName, "scene_info")
	_orderPayment.Status = field.NewInt32(tableName, "status")
	_orderPayment.DeletedAt = field.NewField(tableName, "deleted_at")

	_orderPayment.fillFieldMap()

	return _orderPayment
}

// orderPayment 订单支付信息
type orderPayment struct {
	orderPaymentDo orderPaymentDo

	ALL            field.Asterisk
	ID             field.Int64  // 订单支付ID
	OrderID        field.Int64  // 订单ID
	OrderNo        field.String // 订单编号
	ThirdOrderNo   field.String // 三方订单编号
	TradeType      field.String // 交易类型：JSAPI：公众号支付、小程序支付，NATIVE：Native支付，APP：APP支付，MICROPAY：付款码支付，MWEB：H5支付，FACEPAY：刷脸支付
	TradeState     field.String // 交易状态 SUCCESS：支付成功，REFUND：转入退款，NOTPAY：未支付，CLOSED：已关闭，REVOKED：已撤销（仅付款码支付会返回），USERPAYING：用户支付中（仅付款码支付会返，PAYERROR：支付失败（仅付款码支付会返回）
	TradeStateDesc field.String // 交易状态描述
	BankType       field.String // 银行类型
	SuccessTime    field.Time   // 支付完成时间
	Payer          field.String // 支付者信息
	Amount         field.String // 订单金额
	SceneInfo      field.String // 场景信息
	Status         field.Int32  // 对账状态：枚举【OrderBillStatus】
	DeletedAt      field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (o orderPayment) Table(newTableName string) *orderPayment {
	o.orderPaymentDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o orderPayment) As(alias string) *orderPayment {
	o.orderPaymentDo.DO = *(o.orderPaymentDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *orderPayment) updateTableName(table string) *orderPayment {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewInt64(table, "id")
	o.OrderID = field.NewInt64(table, "order_id")
	o.OrderNo = field.NewString(table, "order_no")
	o.ThirdOrderNo = field.NewString(table, "third_order_no")
	o.TradeType = field.NewString(table, "trade_type")
	o.TradeState = field.NewString(table, "trade_state")
	o.TradeStateDesc = field.NewString(table, "trade_state_desc")
	o.BankType = field.NewString(table, "bank_type")
	o.SuccessTime = field.NewTime(table, "success_time")
	o.Payer = field.NewString(table, "payer")
	o.Amount = field.NewString(table, "amount")
	o.SceneInfo = field.NewString(table, "scene_info")
	o.Status = field.NewInt32(table, "status")
	o.DeletedAt = field.NewField(table, "deleted_at")

	o.fillFieldMap()

	return o
}

func (o *orderPayment) WithContext(ctx context.Context) *orderPaymentDo {
	return o.orderPaymentDo.WithContext(ctx)
}

func (o orderPayment) TableName() string { return o.orderPaymentDo.TableName() }

func (o orderPayment) Alias() string { return o.orderPaymentDo.Alias() }

func (o orderPayment) Columns(cols ...field.Expr) gen.Columns {
	return o.orderPaymentDo.Columns(cols...)
}

func (o *orderPayment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *orderPayment) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 14)
	o.fieldMap["id"] = o.ID
	o.fieldMap["order_id"] = o.OrderID
	o.fieldMap["order_no"] = o.OrderNo
	o.fieldMap["third_order_no"] = o.ThirdOrderNo
	o.fieldMap["trade_type"] = o.TradeType
	o.fieldMap["trade_state"] = o.TradeState
	o.fieldMap["trade_state_desc"] = o.TradeStateDesc
	o.fieldMap["bank_type"] = o.BankType
	o.fieldMap["success_time"] = o.SuccessTime
	o.fieldMap["payer"] = o.Payer
	o.fieldMap["amount"] = o.Amount
	o.fieldMap["scene_info"] = o.SceneInfo
	o.fieldMap["status"] = o.Status
	o.fieldMap["deleted_at"] = o.DeletedAt
}

func (o orderPayment) clone(db *gorm.DB) orderPayment {
	o.orderPaymentDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o orderPayment) replaceDB(db *gorm.DB) orderPayment {
	o.orderPaymentDo.ReplaceDB(db)
	return o
}

type orderPaymentDo struct{ gen.DO }

func (o orderPaymentDo) Debug() *orderPaymentDo {
	return o.withDO(o.DO.Debug())
}

func (o orderPaymentDo) WithContext(ctx context.Context) *orderPaymentDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o orderPaymentDo) ReadDB() *orderPaymentDo {
	return o.Clauses(dbresolver.Read)
}

func (o orderPaymentDo) WriteDB() *orderPaymentDo {
	return o.Clauses(dbresolver.Write)
}

func (o orderPaymentDo) Session(config *gorm.Session) *orderPaymentDo {
	return o.withDO(o.DO.Session(config))
}

func (o orderPaymentDo) Clauses(conds ...clause.Expression) *orderPaymentDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o orderPaymentDo) Returning(value interface{}, columns ...string) *orderPaymentDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o orderPaymentDo) Not(conds ...gen.Condition) *orderPaymentDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o orderPaymentDo) Or(conds ...gen.Condition) *orderPaymentDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o orderPaymentDo) Select(conds ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o orderPaymentDo) Where(conds ...gen.Condition) *orderPaymentDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o orderPaymentDo) Order(conds ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o orderPaymentDo) Distinct(cols ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o orderPaymentDo) Omit(cols ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o orderPaymentDo) Join(table schema.Tabler, on ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o orderPaymentDo) LeftJoin(table schema.Tabler, on ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o orderPaymentDo) RightJoin(table schema.Tabler, on ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o orderPaymentDo) Group(cols ...field.Expr) *orderPaymentDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o orderPaymentDo) Having(conds ...gen.Condition) *orderPaymentDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o orderPaymentDo) Limit(limit int) *orderPaymentDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o orderPaymentDo) Offset(offset int) *orderPaymentDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o orderPaymentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *orderPaymentDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o orderPaymentDo) Unscoped() *orderPaymentDo {
	return o.withDO(o.DO.Unscoped())
}

func (o orderPaymentDo) Create(values ...*models.OrderPayment) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o orderPaymentDo) CreateInBatches(values []*models.OrderPayment, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o orderPaymentDo) Save(values ...*models.OrderPayment) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o orderPaymentDo) First() (*models.OrderPayment, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.OrderPayment), nil
	}
}

func (o orderPaymentDo) Take() (*models.OrderPayment, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.OrderPayment), nil
	}
}

func (o orderPaymentDo) Last() (*models.OrderPayment, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.OrderPayment), nil
	}
}

func (o orderPaymentDo) Find() ([]*models.OrderPayment, error) {
	result, err := o.DO.Find()
	return result.([]*models.OrderPayment), err
}

func (o orderPaymentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OrderPayment, err error) {
	buf := make([]*models.OrderPayment, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o orderPaymentDo) FindInBatches(result *[]*models.OrderPayment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o orderPaymentDo) Attrs(attrs ...field.AssignExpr) *orderPaymentDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o orderPaymentDo) Assign(attrs ...field.AssignExpr) *orderPaymentDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o orderPaymentDo) Joins(fields ...field.RelationField) *orderPaymentDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o orderPaymentDo) Preload(fields ...field.RelationField) *orderPaymentDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o orderPaymentDo) FirstOrInit() (*models.OrderPayment, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.OrderPayment), nil
	}
}

func (o orderPaymentDo) FirstOrCreate() (*models.OrderPayment, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.OrderPayment), nil
	}
}

func (o orderPaymentDo) FindByPage(offset int, limit int) (result []*models.OrderPayment, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o orderPaymentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o orderPaymentDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o orderPaymentDo) Delete(models ...*models.OrderPayment) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *orderPaymentDo) withDO(do gen.Dao) *orderPaymentDo {
	o.DO = *do.(*gen.DO)
	return o
}
