// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: file/file.proto

package file

import (
	"context"
	"errors"
	"gitee.com/liujit/shop/server/api/file"
	"gitee.com/liujit/shop/server/pkg/core"
	"gitee.com/liujit/shop/server/pkg/service/file/biz"
	"go.newcapec.cn/ncttools/nmskit/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// FileServiceImpl is the server API for FileService service implement.
type FileServiceImpl struct {
	file.UnimplementedFileServiceServer
	*core.ShopCore
	fileCase *biz.FileCase
}

// NewFileServiceImpl create a service implement.
// 文件服务
func NewFileServiceImpl(
	sc *core.ShopCore,
	fileCase *biz.FileCase,
) *FileServiceImpl {
	var ss = FileServiceImpl{
		ShopCore: sc,
		fileCase: fileCase,
	}
	log.Debug("NewFileServiceImpl.")
	return &ss
}

// MultiUploadFile
// 多个文件上传
func (s *FileServiceImpl) MultiUploadFile(ctx context.Context, req *file.MultiUploadFileRequest) (*file.MultiUploadFileResponse, error) {
	res, err := s.fileCase.MultiUploadFile(req)
	if err != nil {
		log.Error("MultiUploadFile err:", err.Error())
		return nil, errors.New("多个文件上传失败")
	}
	return res, nil
}

// UploadFile
// 单个文件上传
func (s *FileServiceImpl) UploadFile(ctx context.Context, req *file.UploadFileInfo) (*file.FileInfo, error) {
	res, err := s.fileCase.UploadFile(req)
	if err != nil {
		log.Error("UploadFile err:", err.Error())
		return nil, errors.New("单个文件上传失败")
	}
	return res, nil
}

// DownloadFile
// 下载文件
func (s *FileServiceImpl) DownloadFile(ctx context.Context, req *file.DownloadFileRequest) (*wrapperspb.BytesValue, error) {
	res, err := s.fileCase.DownloadFile(req)
	if err != nil {
		log.Error("DownloadFile err:", err.Error())
		return nil, errors.New("下载文件失败")
	}
	return res, nil
}
