// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/base_log.proto

package admin

import (
	"context"
	"errors"
	"gitee.com/liujit/shop/server/api/admin"
	_const "gitee.com/liujit/shop/server/lib/const"
	"gitee.com/liujit/shop/server/pkg/core"
	"gitee.com/liujit/shop/server/pkg/service/admin/biz"
	"go.newcapec.cn/ncttools/nmskit/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// BaseLogServiceImpl is the server API for BaseLogService service implement.
type BaseLogServiceImpl struct {
	admin.UnimplementedBaseLogServiceServer
	*core.ShopCore
	baseLogCase *biz.BaseLogCase
}

// NewBaseLogServiceImpl create a service implement.
// Admin日志服务
func NewBaseLogServiceImpl(
	sc *core.ShopCore,
	logCase *biz.BaseLogCase,
) *BaseLogServiceImpl {
	var ss = BaseLogServiceImpl{
		ShopCore:    sc,
		baseLogCase: logCase,
	}
	// 注册日志队列
	ss.Queue.Register(_const.Log, ss.baseLogCase.SaveLog)
	log.Debug("NewBaseLogServiceImpl.")
	return &ss
}

// PageBaseLog
// 查询日志分页列表
func (s *BaseLogServiceImpl) PageBaseLog(ctx context.Context, req *admin.PageBaseLogRequest) (*admin.PageBaseLogResponse, error) {
	page, err := s.baseLogCase.Page(ctx, req)
	if err != nil {
		log.Error("PageBaseLog err:", err.Error())
		return nil, errors.New("查询日志分页列表失败")
	}

	return page, nil
}

// GetBaseLog
// 查询日志
func (s *BaseLogServiceImpl) GetBaseLog(ctx context.Context, req *wrapperspb.Int64Value) (*admin.BaseLog, error) {
	baseLog, err := s.baseLogCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetBaseLog err:", err.Error())
		return nil, errors.New("查询日志失败")
	}

	return s.baseLogCase.ConvertToProto(baseLog), nil
}
