// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: admin/order.proto

package admin

import (
	"context"
	"errors"
	"gitee.com/liujit/shop/server/api/admin"
	"gitee.com/liujit/shop/server/pkg/core"
	"gitee.com/liujit/shop/server/pkg/service/admin/biz"
	"go.newcapec.cn/ncttools/nmskit/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

const _ = grpc.SupportPackageIsVersion7

// OrderServiceImpl is the server API for OrderService service implement.
type OrderServiceImpl struct {
	admin.UnimplementedOrderServiceServer
	*core.ShopCore
	orderCase *biz.OrderCase
}

// NewOrderServiceImpl create a service implement.
// 订单服务
func NewOrderServiceImpl(
	sc *core.ShopCore,
	orderCase *biz.OrderCase,
) *OrderServiceImpl {
	var ss = OrderServiceImpl{
		ShopCore:  sc,
		orderCase: orderCase,
	}
	log.Debug("NewOrderServiceImpl.")
	return &ss
}

// PageOrder
// 查询订单分页列表
func (s *OrderServiceImpl) PageOrder(ctx context.Context, req *admin.PageOrderRequest) (*admin.PageOrderResponse, error) {
	page, err := s.orderCase.Page(ctx, req)
	if err != nil {
		log.Error("PageOrder err:", err.Error())
		return nil, errors.New("查询订单分页列表失败")
	}
	return page, nil
}

// GetOrder
// 查询订单
func (s *OrderServiceImpl) GetOrder(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderResponse, error) {
	res, err := s.orderCase.GetFromID(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrder err:", err.Error())
		return nil, errors.New("查询订单失败")
	}

	return res, nil
}

// GetOrderRefund
// 查询订单退款信息
func (s *OrderServiceImpl) GetOrderRefund(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderRefundResponse, error) {
	res, err := s.orderCase.GetOrderRefund(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrderRefund err:", err.Error())
		return nil, errors.New("查询订单退款信息失败")
	}

	return res, nil
}

// RefundOrder
// 订单退款
func (s *OrderServiceImpl) RefundOrder(ctx context.Context, req *admin.RefundOrderRequest) (*emptypb.Empty, error) {
	err := s.orderCase.RefundOrder(ctx, req)
	if err != nil {
		log.Error("RefundOrder err:", err.Error())
		return nil, errors.New("订单退款失败")
	}

	return &emptypb.Empty{}, nil
}

// GetOrderShipped
// 查询订单发货信息
func (s *OrderServiceImpl) GetOrderShipped(ctx context.Context, req *wrapperspb.Int64Value) (*admin.OrderShippedResponse, error) {
	res, err := s.orderCase.GetOrderShipped(ctx, req.GetValue())
	if err != nil {
		log.Error("GetOrderShipped err:", err.Error())
		return nil, errors.New("查询订单发货信息失败")
	}

	return res, nil
}

// ShippedOrder
// 订单发货
func (s *OrderServiceImpl) ShippedOrder(ctx context.Context, req *admin.ShippedOrderRequest) (*emptypb.Empty, error) {
	err := s.orderCase.ShippedOrder(ctx, req)
	if err != nil {
		log.Error("ShippedOrder err:", err.Error())
		return nil, errors.New("订单发货失败")
	}

	return &emptypb.Empty{}, nil
}
