// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/base_role.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "gitee.com/liujit/shop/server/api/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.Status(0)
)

// Validate checks the field values on PageBaseRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageBaseRoleRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageBaseRoleRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageBaseRoleRequestMultiError, or nil if none found.
func (m *PageBaseRoleRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageBaseRoleRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for PageNum

	// no validation rules for PageSize

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return PageBaseRoleRequestMultiError(errors)
	}

	return nil
}

// PageBaseRoleRequestMultiError is an error wrapping multiple validation
// errors returned by PageBaseRoleRequest.ValidateAll() if the designated
// constraints aren't met.
type PageBaseRoleRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageBaseRoleRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageBaseRoleRequestMultiError) AllErrors() []error { return m }

// PageBaseRoleRequestValidationError is the validation error returned by
// PageBaseRoleRequest.Validate if the designated constraints aren't met.
type PageBaseRoleRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageBaseRoleRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageBaseRoleRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageBaseRoleRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageBaseRoleRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageBaseRoleRequestValidationError) ErrorName() string {
	return "PageBaseRoleRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageBaseRoleRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageBaseRoleRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageBaseRoleRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageBaseRoleRequestValidationError{}

// Validate checks the field values on PageBaseRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageBaseRoleResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageBaseRoleResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageBaseRoleResponseMultiError, or nil if none found.
func (m *PageBaseRoleResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageBaseRoleResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageBaseRoleResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageBaseRoleResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageBaseRoleResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageBaseRoleResponseMultiError(errors)
	}

	return nil
}

// PageBaseRoleResponseMultiError is an error wrapping multiple validation
// errors returned by PageBaseRoleResponse.ValidateAll() if the designated
// constraints aren't met.
type PageBaseRoleResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageBaseRoleResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageBaseRoleResponseMultiError) AllErrors() []error { return m }

// PageBaseRoleResponseValidationError is the validation error returned by
// PageBaseRoleResponse.Validate if the designated constraints aren't met.
type PageBaseRoleResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageBaseRoleResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageBaseRoleResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageBaseRoleResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageBaseRoleResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageBaseRoleResponseValidationError) ErrorName() string {
	return "PageBaseRoleResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageBaseRoleResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageBaseRoleResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageBaseRoleResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageBaseRoleResponseValidationError{}

// Validate checks the field values on BaseRole with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseRole) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseRole with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseRoleMultiError, or nil
// if none found.
func (m *BaseRole) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseRole) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for DataScope

	// no validation rules for Status

	// no validation rules for Remark

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return BaseRoleMultiError(errors)
	}

	return nil
}

// BaseRoleMultiError is an error wrapping multiple validation errors returned
// by BaseRole.ValidateAll() if the designated constraints aren't met.
type BaseRoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseRoleMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseRoleMultiError) AllErrors() []error { return m }

// BaseRoleValidationError is the validation error returned by
// BaseRole.Validate if the designated constraints aren't met.
type BaseRoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseRoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseRoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseRoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseRoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseRoleValidationError) ErrorName() string { return "BaseRoleValidationError" }

// Error satisfies the builtin error interface
func (e BaseRoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseRoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseRoleValidationError{}

// Validate checks the field values on BaseRoleForm with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseRoleForm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseRoleForm with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseRoleFormMultiError, or
// nil if none found.
func (m *BaseRoleForm) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseRoleForm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Code

	// no validation rules for Remark

	if m.DataScope != nil {
		// no validation rules for DataScope
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return BaseRoleFormMultiError(errors)
	}

	return nil
}

// BaseRoleFormMultiError is an error wrapping multiple validation errors
// returned by BaseRoleForm.ValidateAll() if the designated constraints aren't met.
type BaseRoleFormMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseRoleFormMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseRoleFormMultiError) AllErrors() []error { return m }

// BaseRoleFormValidationError is the validation error returned by
// BaseRoleForm.Validate if the designated constraints aren't met.
type BaseRoleFormValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseRoleFormValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseRoleFormValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseRoleFormValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseRoleFormValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseRoleFormValidationError) ErrorName() string { return "BaseRoleFormValidationError" }

// Error satisfies the builtin error interface
func (e BaseRoleFormValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseRoleForm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseRoleFormValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseRoleFormValidationError{}

// Validate checks the field values on SetMenusRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SetMenusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SetMenusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SetMenusRequestMultiError, or nil if none found.
func (m *SetMenusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SetMenusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return SetMenusRequestMultiError(errors)
	}

	return nil
}

// SetMenusRequestMultiError is an error wrapping multiple validation errors
// returned by SetMenusRequest.ValidateAll() if the designated constraints
// aren't met.
type SetMenusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SetMenusRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SetMenusRequestMultiError) AllErrors() []error { return m }

// SetMenusRequestValidationError is the validation error returned by
// SetMenusRequest.Validate if the designated constraints aren't met.
type SetMenusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SetMenusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SetMenusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SetMenusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SetMenusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SetMenusRequestValidationError) ErrorName() string { return "SetMenusRequestValidationError" }

// Error satisfies the builtin error interface
func (e SetMenusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSetMenusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SetMenusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SetMenusRequestValidationError{}
