// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: admin/base_config.proto

package admin

import (
	common "gitee.com/liujit/shop/server/api/common"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageBaseConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Site  *common.BaseConfigSite `protobuf:"varint,2,opt,name=site,proto3,enum=common.BaseConfigSite,oneof" json:"site,omitempty"` // 位置：枚举【BaseConfigSite】
	Name  *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`                             // 配置名称
	Type  *common.BaseConfigType `protobuf:"varint,4,opt,name=type,proto3,enum=common.BaseConfigType,oneof" json:"type,omitempty"` // 配置类型：枚举【BaseConfigType】
	Key   *string                `protobuf:"bytes,5,opt,name=key,proto3,oneof" json:"key,omitempty"`                               // 配置key
	// 状态：枚举【Status】
	Status *common.Status `protobuf:"varint,100,opt,name=status,proto3,enum=common.Status,oneof" json:"status,omitempty"`
	// 当前页码
	PageNum int64 `protobuf:"varint,101,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 每一页的行数
	PageSize      int64 `protobuf:"varint,102,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageBaseConfigRequest) Reset() {
	*x = PageBaseConfigRequest{}
	mi := &file_admin_base_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageBaseConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageBaseConfigRequest) ProtoMessage() {}

func (x *PageBaseConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_base_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageBaseConfigRequest.ProtoReflect.Descriptor instead.
func (*PageBaseConfigRequest) Descriptor() ([]byte, []int) {
	return file_admin_base_config_proto_rawDescGZIP(), []int{0}
}

func (x *PageBaseConfigRequest) GetSite() common.BaseConfigSite {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return common.BaseConfigSite(0)
}

func (x *PageBaseConfigRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PageBaseConfigRequest) GetType() common.BaseConfigType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return common.BaseConfigType(0)
}

func (x *PageBaseConfigRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *PageBaseConfigRequest) GetStatus() common.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return common.Status(0)
}

func (x *PageBaseConfigRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageBaseConfigRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageBaseConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页数据
	List []*BaseConfig `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageBaseConfigResponse) Reset() {
	*x = PageBaseConfigResponse{}
	mi := &file_admin_base_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageBaseConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageBaseConfigResponse) ProtoMessage() {}

func (x *PageBaseConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_base_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageBaseConfigResponse.ProtoReflect.Descriptor instead.
func (*PageBaseConfigResponse) Descriptor() ([]byte, []int) {
	return file_admin_base_config_proto_rawDescGZIP(), []int{1}
}

func (x *PageBaseConfigResponse) GetList() []*BaseConfig {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PageBaseConfigResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BaseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 配置ID
	Site          common.BaseConfigSite  `protobuf:"varint,2,opt,name=site,proto3,enum=common.BaseConfigSite" json:"site,omitempty"` // 位置：枚举【BaseConfigSite】
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // 配置名称
	Type          common.BaseConfigType  `protobuf:"varint,4,opt,name=type,proto3,enum=common.BaseConfigType" json:"type,omitempty"` // 配置类型：枚举【BaseConfigType】
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`                               // 配置key
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                           // 配置value
	Status        common.Status          `protobuf:"varint,100,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`   // 状态：枚举【Status】
	CreatedAt     string                 `protobuf:"bytes,200,opt,name=createdAt,proto3" json:"createdAt,omitempty"`                 // 创建时间
	UpdatedAt     string                 `protobuf:"bytes,201,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`                 // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfig) Reset() {
	*x = BaseConfig{}
	mi := &file_admin_base_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfig) ProtoMessage() {}

func (x *BaseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_admin_base_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfig.ProtoReflect.Descriptor instead.
func (*BaseConfig) Descriptor() ([]byte, []int) {
	return file_admin_base_config_proto_rawDescGZIP(), []int{2}
}

func (x *BaseConfig) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseConfig) GetSite() common.BaseConfigSite {
	if x != nil {
		return x.Site
	}
	return common.BaseConfigSite(0)
}

func (x *BaseConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseConfig) GetType() common.BaseConfigType {
	if x != nil {
		return x.Type
	}
	return common.BaseConfigType(0)
}

func (x *BaseConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BaseConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BaseConfig) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *BaseConfig) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BaseConfig) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type BaseConfigForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 配置ID
	Site          *common.BaseConfigSite `protobuf:"varint,2,opt,name=site,proto3,enum=common.BaseConfigSite,oneof" json:"site,omitempty"` // 位置：枚举【BaseConfigSite】
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                   // 配置名称
	Type          *common.BaseConfigType `protobuf:"varint,4,opt,name=type,proto3,enum=common.BaseConfigType,oneof" json:"type,omitempty"` // 配置类型：1、文本，2、图片。3、富文本
	Key           string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`                                     // 配置key
	Value         string                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                                 // 配置value
	Status        *common.Status         `protobuf:"varint,51,opt,name=status,proto3,enum=common.Status,oneof" json:"status,omitempty"`    // 状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseConfigForm) Reset() {
	*x = BaseConfigForm{}
	mi := &file_admin_base_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseConfigForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseConfigForm) ProtoMessage() {}

func (x *BaseConfigForm) ProtoReflect() protoreflect.Message {
	mi := &file_admin_base_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseConfigForm.ProtoReflect.Descriptor instead.
func (*BaseConfigForm) Descriptor() ([]byte, []int) {
	return file_admin_base_config_proto_rawDescGZIP(), []int{3}
}

func (x *BaseConfigForm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseConfigForm) GetSite() common.BaseConfigSite {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return common.BaseConfigSite(0)
}

func (x *BaseConfigForm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseConfigForm) GetType() common.BaseConfigType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return common.BaseConfigType(0)
}

func (x *BaseConfigForm) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BaseConfigForm) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BaseConfigForm) GetStatus() common.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return common.Status(0)
}

var File_admin_base_config_proto protoreflect.FileDescriptor

const file_admin_base_config_proto_rawDesc = "" +
	"\n" +
	"\x17admin/base_config.proto\x12\x05admin\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13common/common.proto\x1a\x11common/enum.proto\"\xa4\x04\n" +
	"\x15PageBaseConfigRequest\x12Z\n" +
	"\x04site\x18\x02 \x01(\x0e2\x16.common.BaseConfigSiteB)\xbaG&\x92\x02#位置：枚举【BaseConfigSite】H\x00R\x04site\x88\x01\x01\x12+\n" +
	"\x04name\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f配置名称H\x01R\x04name\x88\x01\x01\x12`\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.common.BaseConfigTypeB/\xbaG,\x92\x02)配置类型：枚举【BaseConfigType】H\x02R\x04type\x88\x01\x01\x12&\n" +
	"\x03key\x18\x05 \x01(\tB\x0f\xbaG\f\x92\x02\t配置keyH\x03R\x03key\x88\x01\x01\x12N\n" +
	"\x06status\x18d \x01(\x0e2\x0e.common.StatusB!\xbaG\x1e\x92\x02\x1b状态：枚举【Status】H\x04R\x06status\x88\x01\x01\x128\n" +
	"\apageNum\x18e \x01(\x03B\x1e\xbaG\x1b\x8a\x02\t\t\x00\x00\x00\x00\x00\x00\xf0?\x92\x02\f当前页码R\apageNum\x12@\n" +
	"\bpageSize\x18f \x01(\x03B$\xbaG!\x8a\x02\t\t\x00\x00\x00\x00\x00\x00$@\x92\x02\x12每一页的行数R\bpageSizeB\a\n" +
	"\x05_siteB\a\n" +
	"\x05_nameB\a\n" +
	"\x05_typeB\x06\n" +
	"\x04_keyB\t\n" +
	"\a_status\"U\n" +
	"\x16PageBaseConfigResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.admin.BaseConfigR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x85\x04\n" +
	"\n" +
	"BaseConfig\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b配置IDR\x02id\x12U\n" +
	"\x04site\x18\x02 \x01(\x0e2\x16.common.BaseConfigSiteB)\xbaG&\x92\x02#位置：枚举【BaseConfigSite】R\x04site\x12&\n" +
	"\x04name\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f配置名称R\x04name\x12[\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.common.BaseConfigTypeB/\xbaG,\x92\x02)配置类型：枚举【BaseConfigType】R\x04type\x12!\n" +
	"\x03key\x18\x05 \x01(\tB\x0f\xbaG\f\x92\x02\t配置keyR\x03key\x12'\n" +
	"\x05value\x18\x06 \x01(\tB\x11\xbaG\x0e\x92\x02\v配置valueR\x05value\x12I\n" +
	"\x06status\x18d \x01(\x0e2\x0e.common.StatusB!\xbaG\x1e\x92\x02\x1b状态：枚举【Status】R\x06status\x121\n" +
	"\tcreatedAt\x18\xc8\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f创建时间R\tcreatedAt\x121\n" +
	"\tupdatedAt\x18\xc9\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f更新时间R\tupdatedAt\"\xc7\x03\n" +
	"\x0eBaseConfigForm\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b配置IDR\x02id\x12Z\n" +
	"\x04site\x18\x02 \x01(\x0e2\x16.common.BaseConfigSiteB)\xbaG&\x92\x02#位置：枚举【BaseConfigSite】H\x00R\x04site\x88\x01\x01\x12&\n" +
	"\x04name\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f配置名称R\x04name\x12m\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.common.BaseConfigTypeB<\xbaG9\x92\x026配置类型：1、文本，2、图片。3、富文本H\x01R\x04type\x88\x01\x01\x12!\n" +
	"\x03key\x18\x05 \x01(\tB\x0f\xbaG\f\x92\x02\t配置keyR\x03key\x12'\n" +
	"\x05value\x18\x06 \x01(\tB\x11\xbaG\x0e\x92\x02\v配置valueR\x05value\x129\n" +
	"\x06status\x183 \x01(\x0e2\x0e.common.StatusB\f\xbaG\t\x92\x02\x06状态H\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_siteB\a\n" +
	"\x05_typeB\t\n" +
	"\a_status2\x9a\x06\n" +
	"\x11BaseConfigService\x12n\n" +
	"\x11RefreshBaseConfig\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/admin/base/config/refresh\x12m\n" +
	"\x0ePageBaseConfig\x12\x1c.admin.PageBaseConfigRequest\x1a\x1d.admin.PageBaseConfigResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/admin/base/config\x12k\n" +
	"\rGetBaseConfig\x12\x1b.google.protobuf.Int64Value\x1a\x15.admin.BaseConfigForm\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/admin/base/config/{value}\x12d\n" +
	"\x10CreateBaseConfig\x12\x15.admin.BaseConfigForm\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/admin/base/config\x12i\n" +
	"\x10UpdateBaseConfig\x12\x15.admin.BaseConfigForm\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/admin/base/config/{id}\x12p\n" +
	"\x10DeleteBaseConfig\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 *\x1e/api/admin/base/config/{value}\x12v\n" +
	"\x13SetBaseConfigStatus\x12\x18.common.SetStatusRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/admin/base/config/{id}/statusB~\n" +
	"\tcom.adminB\x0fBaseConfigProtoP\x01Z,gitee.com/liujit/shop/server/api/admin;admin\xa2\x02\x03AXX\xaa\x02\x05Admin\xca\x02\x05Admin\xe2\x02\x11Admin\\GPBMetadata\xea\x02\x05Adminb\x06proto3"

var (
	file_admin_base_config_proto_rawDescOnce sync.Once
	file_admin_base_config_proto_rawDescData []byte
)

func file_admin_base_config_proto_rawDescGZIP() []byte {
	file_admin_base_config_proto_rawDescOnce.Do(func() {
		file_admin_base_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_base_config_proto_rawDesc), len(file_admin_base_config_proto_rawDesc)))
	})
	return file_admin_base_config_proto_rawDescData
}

var file_admin_base_config_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_base_config_proto_goTypes = []any{
	(*PageBaseConfigRequest)(nil),   // 0: admin.PageBaseConfigRequest
	(*PageBaseConfigResponse)(nil),  // 1: admin.PageBaseConfigResponse
	(*BaseConfig)(nil),              // 2: admin.BaseConfig
	(*BaseConfigForm)(nil),          // 3: admin.BaseConfigForm
	(common.BaseConfigSite)(0),      // 4: common.BaseConfigSite
	(common.BaseConfigType)(0),      // 5: common.BaseConfigType
	(common.Status)(0),              // 6: common.Status
	(*emptypb.Empty)(nil),           // 7: google.protobuf.Empty
	(*wrapperspb.Int64Value)(nil),   // 8: google.protobuf.Int64Value
	(*wrapperspb.StringValue)(nil),  // 9: google.protobuf.StringValue
	(*common.SetStatusRequest)(nil), // 10: common.SetStatusRequest
}
var file_admin_base_config_proto_depIdxs = []int32{
	4,  // 0: admin.PageBaseConfigRequest.site:type_name -> common.BaseConfigSite
	5,  // 1: admin.PageBaseConfigRequest.type:type_name -> common.BaseConfigType
	6,  // 2: admin.PageBaseConfigRequest.status:type_name -> common.Status
	2,  // 3: admin.PageBaseConfigResponse.list:type_name -> admin.BaseConfig
	4,  // 4: admin.BaseConfig.site:type_name -> common.BaseConfigSite
	5,  // 5: admin.BaseConfig.type:type_name -> common.BaseConfigType
	6,  // 6: admin.BaseConfig.status:type_name -> common.Status
	4,  // 7: admin.BaseConfigForm.site:type_name -> common.BaseConfigSite
	5,  // 8: admin.BaseConfigForm.type:type_name -> common.BaseConfigType
	6,  // 9: admin.BaseConfigForm.status:type_name -> common.Status
	7,  // 10: admin.BaseConfigService.RefreshBaseConfig:input_type -> google.protobuf.Empty
	0,  // 11: admin.BaseConfigService.PageBaseConfig:input_type -> admin.PageBaseConfigRequest
	8,  // 12: admin.BaseConfigService.GetBaseConfig:input_type -> google.protobuf.Int64Value
	3,  // 13: admin.BaseConfigService.CreateBaseConfig:input_type -> admin.BaseConfigForm
	3,  // 14: admin.BaseConfigService.UpdateBaseConfig:input_type -> admin.BaseConfigForm
	9,  // 15: admin.BaseConfigService.DeleteBaseConfig:input_type -> google.protobuf.StringValue
	10, // 16: admin.BaseConfigService.SetBaseConfigStatus:input_type -> common.SetStatusRequest
	7,  // 17: admin.BaseConfigService.RefreshBaseConfig:output_type -> google.protobuf.Empty
	1,  // 18: admin.BaseConfigService.PageBaseConfig:output_type -> admin.PageBaseConfigResponse
	3,  // 19: admin.BaseConfigService.GetBaseConfig:output_type -> admin.BaseConfigForm
	7,  // 20: admin.BaseConfigService.CreateBaseConfig:output_type -> google.protobuf.Empty
	7,  // 21: admin.BaseConfigService.UpdateBaseConfig:output_type -> google.protobuf.Empty
	7,  // 22: admin.BaseConfigService.DeleteBaseConfig:output_type -> google.protobuf.Empty
	7,  // 23: admin.BaseConfigService.SetBaseConfigStatus:output_type -> google.protobuf.Empty
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_base_config_proto_init() }
func file_admin_base_config_proto_init() {
	if File_admin_base_config_proto != nil {
		return
	}
	file_admin_base_config_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_base_config_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_base_config_proto_rawDesc), len(file_admin_base_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_base_config_proto_goTypes,
		DependencyIndexes: file_admin_base_config_proto_depIdxs,
		MessageInfos:      file_admin_base_config_proto_msgTypes,
	}.Build()
	File_admin_base_config_proto = out.File
	file_admin_base_config_proto_goTypes = nil
	file_admin_base_config_proto_depIdxs = nil
}
