// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/base_log.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on PageBaseLogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageBaseLogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageBaseLogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageBaseLogRequestMultiError, or nil if none found.
func (m *PageBaseLogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageBaseLogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Operation

	// no validation rules for PageNum

	// no validation rules for PageSize

	if m.StatusCode != nil {
		// no validation rules for StatusCode
	}

	if len(errors) > 0 {
		return PageBaseLogRequestMultiError(errors)
	}

	return nil
}

// PageBaseLogRequestMultiError is an error wrapping multiple validation errors
// returned by PageBaseLogRequest.ValidateAll() if the designated constraints
// aren't met.
type PageBaseLogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageBaseLogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageBaseLogRequestMultiError) AllErrors() []error { return m }

// PageBaseLogRequestValidationError is the validation error returned by
// PageBaseLogRequest.Validate if the designated constraints aren't met.
type PageBaseLogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageBaseLogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageBaseLogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageBaseLogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageBaseLogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageBaseLogRequestValidationError) ErrorName() string {
	return "PageBaseLogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageBaseLogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageBaseLogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageBaseLogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageBaseLogRequestValidationError{}

// Validate checks the field values on PageBaseLogResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageBaseLogResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageBaseLogResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageBaseLogResponseMultiError, or nil if none found.
func (m *PageBaseLogResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageBaseLogResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageBaseLogResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageBaseLogResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageBaseLogResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageBaseLogResponseMultiError(errors)
	}

	return nil
}

// PageBaseLogResponseMultiError is an error wrapping multiple validation
// errors returned by PageBaseLogResponse.ValidateAll() if the designated
// constraints aren't met.
type PageBaseLogResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageBaseLogResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageBaseLogResponseMultiError) AllErrors() []error { return m }

// PageBaseLogResponseValidationError is the validation error returned by
// PageBaseLogResponse.Validate if the designated constraints aren't met.
type PageBaseLogResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageBaseLogResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageBaseLogResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageBaseLogResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageBaseLogResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageBaseLogResponseValidationError) ErrorName() string {
	return "PageBaseLogResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageBaseLogResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageBaseLogResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageBaseLogResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageBaseLogResponseValidationError{}

// Validate checks the field values on BaseLog with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseLog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseLog with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BaseLogMultiError, or nil if none found.
func (m *BaseLog) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseLog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for RequestId

	// no validation rules for RequestTime

	// no validation rules for Method

	// no validation rules for Operation

	// no validation rules for Path

	// no validation rules for Referer

	// no validation rules for RequestUri

	// no validation rules for RequestHeader

	// no validation rules for RequestBody

	// no validation rules for Response

	// no validation rules for CostTime

	// no validation rules for Success

	// no validation rules for StatusCode

	// no validation rules for Reason

	// no validation rules for Location

	// no validation rules for UserId

	// no validation rules for UserName

	// no validation rules for ClientIp

	// no validation rules for UserAgent

	// no validation rules for BrowserName

	// no validation rules for BrowserVersion

	// no validation rules for ClientId

	// no validation rules for ClientName

	// no validation rules for OsName

	// no validation rules for OsVersion

	if len(errors) > 0 {
		return BaseLogMultiError(errors)
	}

	return nil
}

// BaseLogMultiError is an error wrapping multiple validation errors returned
// by BaseLog.ValidateAll() if the designated constraints aren't met.
type BaseLogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseLogMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseLogMultiError) AllErrors() []error { return m }

// BaseLogValidationError is the validation error returned by BaseLog.Validate
// if the designated constraints aren't met.
type BaseLogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseLogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseLogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseLogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseLogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseLogValidationError) ErrorName() string { return "BaseLogValidationError" }

// Error satisfies the builtin error interface
func (e BaseLogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseLog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseLogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseLogValidationError{}
