// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: admin/base_dept.proto

package admin

import (
	context "context"
	common "gitee.com/liujit/shop/server/api/common"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBaseDeptServiceCreateBaseDept = "/admin.BaseDeptService/CreateBaseDept"
const OperationBaseDeptServiceDeleteBaseDept = "/admin.BaseDeptService/DeleteBaseDept"
const OperationBaseDeptServiceGetBaseDept = "/admin.BaseDeptService/GetBaseDept"
const OperationBaseDeptServiceOptionBaseDept = "/admin.BaseDeptService/OptionBaseDept"
const OperationBaseDeptServiceSetBaseDeptStatus = "/admin.BaseDeptService/SetBaseDeptStatus"
const OperationBaseDeptServiceTreeBaseDept = "/admin.BaseDeptService/TreeBaseDept"
const OperationBaseDeptServiceUpdateBaseDept = "/admin.BaseDeptService/UpdateBaseDept"

type BaseDeptServiceHTTPServer interface {
	// CreateBaseDept 创建部门
	CreateBaseDept(context.Context, *BaseDeptForm) (*emptypb.Empty, error)
	// DeleteBaseDept 删除部门
	DeleteBaseDept(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetBaseDept 查询部门
	GetBaseDept(context.Context, *wrapperspb.Int64Value) (*BaseDeptForm, error)
	// OptionBaseDept 查询部门树形选择
	OptionBaseDept(context.Context, *OptionBaseDeptRequest) (*common.TreeOptionResponse, error)
	// SetBaseDeptStatus 设置状态
	SetBaseDeptStatus(context.Context, *common.SetStatusRequest) (*emptypb.Empty, error)
	// TreeBaseDept 查询部门树形列表
	TreeBaseDept(context.Context, *emptypb.Empty) (*TreeBaseDeptResponse, error)
	// UpdateBaseDept 更新部门
	UpdateBaseDept(context.Context, *BaseDeptForm) (*emptypb.Empty, error)
}

func RegisterBaseDeptServiceHTTPServer(s *http.Server, srv BaseDeptServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/admin/base/dept/tree", _BaseDeptService_TreeBaseDept0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dept/option", _BaseDeptService_OptionBaseDept0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dept/{value}", _BaseDeptService_GetBaseDept0_HTTP_Handler(srv))
	r.POST("/api/admin/base/dept", _BaseDeptService_CreateBaseDept0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dept/{id}", _BaseDeptService_UpdateBaseDept0_HTTP_Handler(srv))
	r.DELETE("/api/admin/base/dept/{value}", _BaseDeptService_DeleteBaseDept0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dept/{id}/status", _BaseDeptService_SetBaseDeptStatus0_HTTP_Handler(srv))
}

func _BaseDeptService_TreeBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceTreeBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TreeBaseDept(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TreeBaseDeptResponse)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_OptionBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in OptionBaseDeptRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceOptionBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.OptionBaseDept(ctx, req.(*OptionBaseDeptRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.TreeOptionResponse)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_GetBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceGetBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBaseDept(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BaseDeptForm)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_CreateBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDeptForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceCreateBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBaseDept(ctx, req.(*BaseDeptForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_UpdateBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDeptForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceUpdateBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBaseDept(ctx, req.(*BaseDeptForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_DeleteBaseDept0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.StringValue
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceDeleteBaseDept)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBaseDept(ctx, req.(*wrapperspb.StringValue))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDeptService_SetBaseDeptStatus0_HTTP_Handler(srv BaseDeptServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in common.SetStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDeptServiceSetBaseDeptStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetBaseDeptStatus(ctx, req.(*common.SetStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type BaseDeptServiceHTTPClient interface {
	CreateBaseDept(ctx context.Context, req *BaseDeptForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteBaseDept(ctx context.Context, req *wrapperspb.StringValue, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetBaseDept(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *BaseDeptForm, err error)
	OptionBaseDept(ctx context.Context, req *OptionBaseDeptRequest, opts ...http.CallOption) (rsp *common.TreeOptionResponse, err error)
	SetBaseDeptStatus(ctx context.Context, req *common.SetStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	TreeBaseDept(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *TreeBaseDeptResponse, err error)
	UpdateBaseDept(ctx context.Context, req *BaseDeptForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type BaseDeptServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBaseDeptServiceHTTPClient(client *http.Client) BaseDeptServiceHTTPClient {
	return &BaseDeptServiceHTTPClientImpl{client}
}

func (c *BaseDeptServiceHTTPClientImpl) CreateBaseDept(ctx context.Context, in *BaseDeptForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dept"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDeptServiceCreateBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) DeleteBaseDept(ctx context.Context, in *wrapperspb.StringValue, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dept/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDeptServiceDeleteBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) GetBaseDept(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*BaseDeptForm, error) {
	var out BaseDeptForm
	pattern := "/api/admin/base/dept/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDeptServiceGetBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) OptionBaseDept(ctx context.Context, in *OptionBaseDeptRequest, opts ...http.CallOption) (*common.TreeOptionResponse, error) {
	var out common.TreeOptionResponse
	pattern := "/api/admin/base/dept/option"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDeptServiceOptionBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) SetBaseDeptStatus(ctx context.Context, in *common.SetStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dept/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDeptServiceSetBaseDeptStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) TreeBaseDept(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*TreeBaseDeptResponse, error) {
	var out TreeBaseDeptResponse
	pattern := "/api/admin/base/dept/tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDeptServiceTreeBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDeptServiceHTTPClientImpl) UpdateBaseDept(ctx context.Context, in *BaseDeptForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dept/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDeptServiceUpdateBaseDept))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
