// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: admin/base_dict.proto

package admin

import (
	context "context"
	common "gitee.com/liujit/shop/server/api/common"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBaseDictServiceCreateBaseDict = "/admin.BaseDictService/CreateBaseDict"
const OperationBaseDictServiceCreateBaseDictItem = "/admin.BaseDictService/CreateBaseDictItem"
const OperationBaseDictServiceDeleteBaseDict = "/admin.BaseDictService/DeleteBaseDict"
const OperationBaseDictServiceDeleteBaseDictItem = "/admin.BaseDictService/DeleteBaseDictItem"
const OperationBaseDictServiceGetBaseDict = "/admin.BaseDictService/GetBaseDict"
const OperationBaseDictServiceGetBaseDictItem = "/admin.BaseDictService/GetBaseDictItem"
const OperationBaseDictServiceListBaseDict = "/admin.BaseDictService/ListBaseDict"
const OperationBaseDictServicePageBaseDict = "/admin.BaseDictService/PageBaseDict"
const OperationBaseDictServicePageBaseDictItem = "/admin.BaseDictService/PageBaseDictItem"
const OperationBaseDictServiceSetBaseDictItemStatus = "/admin.BaseDictService/SetBaseDictItemStatus"
const OperationBaseDictServiceSetBaseDictStatus = "/admin.BaseDictService/SetBaseDictStatus"
const OperationBaseDictServiceUpdateBaseDict = "/admin.BaseDictService/UpdateBaseDict"
const OperationBaseDictServiceUpdateBaseDictItem = "/admin.BaseDictService/UpdateBaseDictItem"

type BaseDictServiceHTTPServer interface {
	// CreateBaseDict 创建字典
	CreateBaseDict(context.Context, *BaseDictForm) (*emptypb.Empty, error)
	// CreateBaseDictItem 创建字典属性
	CreateBaseDictItem(context.Context, *BaseDictItemForm) (*emptypb.Empty, error)
	// DeleteBaseDict 删除字典
	DeleteBaseDict(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// DeleteBaseDictItem 删除字典属性
	DeleteBaseDictItem(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetBaseDict 查询字典
	GetBaseDict(context.Context, *wrapperspb.Int64Value) (*BaseDictForm, error)
	// GetBaseDictItem 查询字典属性
	GetBaseDictItem(context.Context, *wrapperspb.Int64Value) (*BaseDictItemForm, error)
	// ListBaseDict 查询字典列表
	ListBaseDict(context.Context, *emptypb.Empty) (*ListBaseDictResponse, error)
	// PageBaseDict 查询字典分页列表
	PageBaseDict(context.Context, *PageBaseDictRequest) (*PageBaseDictResponse, error)
	// PageBaseDictItem 查询字典属性分页列表
	PageBaseDictItem(context.Context, *PageBaseDictItemRequest) (*PageBaseDictItemResponse, error)
	// SetBaseDictItemStatus 设置状态
	SetBaseDictItemStatus(context.Context, *common.SetStatusRequest) (*emptypb.Empty, error)
	// SetBaseDictStatus 设置状态
	SetBaseDictStatus(context.Context, *common.SetStatusRequest) (*emptypb.Empty, error)
	// UpdateBaseDict 更新字典
	UpdateBaseDict(context.Context, *BaseDictForm) (*emptypb.Empty, error)
	// UpdateBaseDictItem 更新字典属性
	UpdateBaseDictItem(context.Context, *BaseDictItemForm) (*emptypb.Empty, error)
}

func RegisterBaseDictServiceHTTPServer(s *http.Server, srv BaseDictServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/admin/base/dict/list", _BaseDictService_ListBaseDict0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dict", _BaseDictService_PageBaseDict0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dict/{value}", _BaseDictService_GetBaseDict0_HTTP_Handler(srv))
	r.POST("/api/admin/base/dict", _BaseDictService_CreateBaseDict0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dict/{id}", _BaseDictService_UpdateBaseDict0_HTTP_Handler(srv))
	r.DELETE("/api/admin/base/dict/{value}", _BaseDictService_DeleteBaseDict0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dict/{id}/status", _BaseDictService_SetBaseDictStatus0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dict-item", _BaseDictService_PageBaseDictItem0_HTTP_Handler(srv))
	r.GET("/api/admin/base/dict-item/{value}", _BaseDictService_GetBaseDictItem0_HTTP_Handler(srv))
	r.POST("/api/admin/base/dict-item", _BaseDictService_CreateBaseDictItem0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dict-item/{id}", _BaseDictService_UpdateBaseDictItem0_HTTP_Handler(srv))
	r.DELETE("/api/admin/base/dict-item/{value}", _BaseDictService_DeleteBaseDictItem0_HTTP_Handler(srv))
	r.PUT("/api/admin/base/dict-item/{id}/status", _BaseDictService_SetBaseDictItemStatus0_HTTP_Handler(srv))
}

func _BaseDictService_ListBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceListBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBaseDict(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBaseDictResponse)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_PageBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageBaseDictRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServicePageBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageBaseDict(ctx, req.(*PageBaseDictRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageBaseDictResponse)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_GetBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceGetBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBaseDict(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BaseDictForm)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_CreateBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDictForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceCreateBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBaseDict(ctx, req.(*BaseDictForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_UpdateBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDictForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceUpdateBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBaseDict(ctx, req.(*BaseDictForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_DeleteBaseDict0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.StringValue
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceDeleteBaseDict)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBaseDict(ctx, req.(*wrapperspb.StringValue))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_SetBaseDictStatus0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in common.SetStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceSetBaseDictStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetBaseDictStatus(ctx, req.(*common.SetStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_PageBaseDictItem0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageBaseDictItemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServicePageBaseDictItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageBaseDictItem(ctx, req.(*PageBaseDictItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageBaseDictItemResponse)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_GetBaseDictItem0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceGetBaseDictItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetBaseDictItem(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BaseDictItemForm)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_CreateBaseDictItem0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDictItemForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceCreateBaseDictItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateBaseDictItem(ctx, req.(*BaseDictItemForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_UpdateBaseDictItem0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BaseDictItemForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceUpdateBaseDictItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateBaseDictItem(ctx, req.(*BaseDictItemForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_DeleteBaseDictItem0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.StringValue
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceDeleteBaseDictItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteBaseDictItem(ctx, req.(*wrapperspb.StringValue))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _BaseDictService_SetBaseDictItemStatus0_HTTP_Handler(srv BaseDictServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in common.SetStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseDictServiceSetBaseDictItemStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetBaseDictItemStatus(ctx, req.(*common.SetStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type BaseDictServiceHTTPClient interface {
	CreateBaseDict(ctx context.Context, req *BaseDictForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	CreateBaseDictItem(ctx context.Context, req *BaseDictItemForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteBaseDict(ctx context.Context, req *wrapperspb.StringValue, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteBaseDictItem(ctx context.Context, req *wrapperspb.StringValue, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetBaseDict(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *BaseDictForm, err error)
	GetBaseDictItem(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *BaseDictItemForm, err error)
	ListBaseDict(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListBaseDictResponse, err error)
	PageBaseDict(ctx context.Context, req *PageBaseDictRequest, opts ...http.CallOption) (rsp *PageBaseDictResponse, err error)
	PageBaseDictItem(ctx context.Context, req *PageBaseDictItemRequest, opts ...http.CallOption) (rsp *PageBaseDictItemResponse, err error)
	SetBaseDictItemStatus(ctx context.Context, req *common.SetStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	SetBaseDictStatus(ctx context.Context, req *common.SetStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateBaseDict(ctx context.Context, req *BaseDictForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateBaseDictItem(ctx context.Context, req *BaseDictItemForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type BaseDictServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBaseDictServiceHTTPClient(client *http.Client) BaseDictServiceHTTPClient {
	return &BaseDictServiceHTTPClientImpl{client}
}

func (c *BaseDictServiceHTTPClientImpl) CreateBaseDict(ctx context.Context, in *BaseDictForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceCreateBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) CreateBaseDictItem(ctx context.Context, in *BaseDictItemForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict-item"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceCreateBaseDictItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) DeleteBaseDict(ctx context.Context, in *wrapperspb.StringValue, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServiceDeleteBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) DeleteBaseDictItem(ctx context.Context, in *wrapperspb.StringValue, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict-item/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServiceDeleteBaseDictItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) GetBaseDict(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*BaseDictForm, error) {
	var out BaseDictForm
	pattern := "/api/admin/base/dict/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServiceGetBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) GetBaseDictItem(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*BaseDictItemForm, error) {
	var out BaseDictItemForm
	pattern := "/api/admin/base/dict-item/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServiceGetBaseDictItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) ListBaseDict(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListBaseDictResponse, error) {
	var out ListBaseDictResponse
	pattern := "/api/admin/base/dict/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServiceListBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) PageBaseDict(ctx context.Context, in *PageBaseDictRequest, opts ...http.CallOption) (*PageBaseDictResponse, error) {
	var out PageBaseDictResponse
	pattern := "/api/admin/base/dict"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServicePageBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) PageBaseDictItem(ctx context.Context, in *PageBaseDictItemRequest, opts ...http.CallOption) (*PageBaseDictItemResponse, error) {
	var out PageBaseDictItemResponse
	pattern := "/api/admin/base/dict-item"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseDictServicePageBaseDictItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) SetBaseDictItemStatus(ctx context.Context, in *common.SetStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict-item/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceSetBaseDictItemStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) SetBaseDictStatus(ctx context.Context, in *common.SetStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceSetBaseDictStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) UpdateBaseDict(ctx context.Context, in *BaseDictForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceUpdateBaseDict))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *BaseDictServiceHTTPClientImpl) UpdateBaseDictItem(ctx context.Context, in *BaseDictItemForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/base/dict-item/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationBaseDictServiceUpdateBaseDictItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
