// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/goods.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "gitee.com/liujit/shop/server/api/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.GoodsStatus(0)
)

// Validate checks the field values on ListGoodsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListGoodsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGoodsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListGoodsRequestMultiError, or nil if none found.
func (m *ListGoodsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGoodsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return ListGoodsRequestMultiError(errors)
	}

	return nil
}

// ListGoodsRequestMultiError is an error wrapping multiple validation errors
// returned by ListGoodsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListGoodsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGoodsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGoodsRequestMultiError) AllErrors() []error { return m }

// ListGoodsRequestValidationError is the validation error returned by
// ListGoodsRequest.Validate if the designated constraints aren't met.
type ListGoodsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGoodsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGoodsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGoodsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGoodsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGoodsRequestValidationError) ErrorName() string { return "ListGoodsRequestValidationError" }

// Error satisfies the builtin error interface
func (e ListGoodsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGoodsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGoodsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGoodsRequestValidationError{}

// Validate checks the field values on ListGoodsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListGoodsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGoodsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListGoodsResponseMultiError, or nil if none found.
func (m *ListGoodsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGoodsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListGoodsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListGoodsResponseMultiError(errors)
	}

	return nil
}

// ListGoodsResponseMultiError is an error wrapping multiple validation errors
// returned by ListGoodsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListGoodsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGoodsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGoodsResponseMultiError) AllErrors() []error { return m }

// ListGoodsResponseValidationError is the validation error returned by
// ListGoodsResponse.Validate if the designated constraints aren't met.
type ListGoodsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGoodsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGoodsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGoodsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGoodsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGoodsResponseValidationError) ErrorName() string {
	return "ListGoodsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListGoodsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGoodsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGoodsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGoodsResponseValidationError{}

// Validate checks the field values on PageGoodsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageGoodsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageGoodsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageGoodsRequestMultiError, or nil if none found.
func (m *PageGoodsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageGoodsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for PageNum

	// no validation rules for PageSize

	if m.CategoryId != nil {
		// no validation rules for CategoryId
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return PageGoodsRequestMultiError(errors)
	}

	return nil
}

// PageGoodsRequestMultiError is an error wrapping multiple validation errors
// returned by PageGoodsRequest.ValidateAll() if the designated constraints
// aren't met.
type PageGoodsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageGoodsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageGoodsRequestMultiError) AllErrors() []error { return m }

// PageGoodsRequestValidationError is the validation error returned by
// PageGoodsRequest.Validate if the designated constraints aren't met.
type PageGoodsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageGoodsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageGoodsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageGoodsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageGoodsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageGoodsRequestValidationError) ErrorName() string { return "PageGoodsRequestValidationError" }

// Error satisfies the builtin error interface
func (e PageGoodsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageGoodsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageGoodsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageGoodsRequestValidationError{}

// Validate checks the field values on PageGoodsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageGoodsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageGoodsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageGoodsResponseMultiError, or nil if none found.
func (m *PageGoodsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageGoodsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageGoodsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageGoodsResponseMultiError(errors)
	}

	return nil
}

// PageGoodsResponseMultiError is an error wrapping multiple validation errors
// returned by PageGoodsResponse.ValidateAll() if the designated constraints
// aren't met.
type PageGoodsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageGoodsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageGoodsResponseMultiError) AllErrors() []error { return m }

// PageGoodsResponseValidationError is the validation error returned by
// PageGoodsResponse.Validate if the designated constraints aren't met.
type PageGoodsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageGoodsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageGoodsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageGoodsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageGoodsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageGoodsResponseValidationError) ErrorName() string {
	return "PageGoodsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageGoodsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageGoodsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageGoodsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageGoodsResponseValidationError{}

// Validate checks the field values on Goods with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Goods) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Goods with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in GoodsMultiError, or nil if none found.
func (m *Goods) ValidateAll() error {
	return m.validate(true)
}

func (m *Goods) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for CategoryId

	// no validation rules for Name

	// no validation rules for Desc

	// no validation rules for Picture

	// no validation rules for Price

	// no validation rules for DiscountPrice

	// no validation rules for InitSaleNum

	// no validation rules for RealSaleNum

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for CategoryName

	if len(errors) > 0 {
		return GoodsMultiError(errors)
	}

	return nil
}

// GoodsMultiError is an error wrapping multiple validation errors returned by
// Goods.ValidateAll() if the designated constraints aren't met.
type GoodsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodsMultiError) AllErrors() []error { return m }

// GoodsValidationError is the validation error returned by Goods.Validate if
// the designated constraints aren't met.
type GoodsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodsValidationError) ErrorName() string { return "GoodsValidationError" }

// Error satisfies the builtin error interface
func (e GoodsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoods.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodsValidationError{}

// Validate checks the field values on GoodsForm with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GoodsForm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GoodsForm with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GoodsFormMultiError, or nil
// if none found.
func (m *GoodsForm) ValidateAll() error {
	return m.validate(true)
}

func (m *GoodsForm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Desc

	// no validation rules for Picture

	for idx, item := range m.GetPropList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("PropList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("PropList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GoodsFormValidationError{
					field:  fmt.Sprintf("PropList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetSkuList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("SkuList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("SkuList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GoodsFormValidationError{
					field:  fmt.Sprintf("SkuList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetSpecList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("SpecList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GoodsFormValidationError{
						field:  fmt.Sprintf("SpecList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GoodsFormValidationError{
					field:  fmt.Sprintf("SpecList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CategoryName

	if m.CategoryId != nil {
		// no validation rules for CategoryId
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return GoodsFormMultiError(errors)
	}

	return nil
}

// GoodsFormMultiError is an error wrapping multiple validation errors returned
// by GoodsForm.ValidateAll() if the designated constraints aren't met.
type GoodsFormMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GoodsFormMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GoodsFormMultiError) AllErrors() []error { return m }

// GoodsFormValidationError is the validation error returned by
// GoodsForm.Validate if the designated constraints aren't met.
type GoodsFormValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GoodsFormValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GoodsFormValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GoodsFormValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GoodsFormValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GoodsFormValidationError) ErrorName() string { return "GoodsFormValidationError" }

// Error satisfies the builtin error interface
func (e GoodsFormValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGoodsForm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GoodsFormValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GoodsFormValidationError{}

// Validate checks the field values on ListGoodsResponse_Goods with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListGoodsResponse_Goods) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListGoodsResponse_Goods with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListGoodsResponse_GoodsMultiError, or nil if none found.
func (m *ListGoodsResponse_Goods) ValidateAll() error {
	return m.validate(true)
}

func (m *ListGoodsResponse_Goods) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Price

	// no validation rules for CategoryName

	if len(errors) > 0 {
		return ListGoodsResponse_GoodsMultiError(errors)
	}

	return nil
}

// ListGoodsResponse_GoodsMultiError is an error wrapping multiple validation
// errors returned by ListGoodsResponse_Goods.ValidateAll() if the designated
// constraints aren't met.
type ListGoodsResponse_GoodsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListGoodsResponse_GoodsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListGoodsResponse_GoodsMultiError) AllErrors() []error { return m }

// ListGoodsResponse_GoodsValidationError is the validation error returned by
// ListGoodsResponse_Goods.Validate if the designated constraints aren't met.
type ListGoodsResponse_GoodsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListGoodsResponse_GoodsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListGoodsResponse_GoodsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListGoodsResponse_GoodsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListGoodsResponse_GoodsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListGoodsResponse_GoodsValidationError) ErrorName() string {
	return "ListGoodsResponse_GoodsValidationError"
}

// Error satisfies the builtin error interface
func (e ListGoodsResponse_GoodsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListGoodsResponse_Goods.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListGoodsResponse_GoodsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListGoodsResponse_GoodsValidationError{}
