// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.2
// - protoc             (unknown)
// source: admin/goods_sku.proto

package admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ================== 客户端 接口、结构、工厂、方法 ===================

// GoodsSkuServiceClient is the client API for GoodsSkuService service.
// client interface. Admin商品SKU服务
type GoodsSkuServiceClient interface {
	// 查询商品SKU分页列表
	PageGoodsSku(ctx context.Context, in *PageGoodsSkuRequest, opts ...grpc.CallOption) (*PageGoodsSkuResponse, error)
	// 查询商品SKU
	GetGoodsSku(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*GoodsSku, error)
	// 更新商品SKU
	UpdateGoodsSku(ctx context.Context, in *GoodsSku, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

// client data structure. Admin商品SKU服务
type goodsSkuServiceClient struct {
	cc grpc.ClientConnInterface
}

// Client factory. Admin商品SKU服务
func NewGoodsSkuServiceClient(cc grpc.ClientConnInterface) GoodsSkuServiceClient {
	return &goodsSkuServiceClient{cc}
}

// 查询商品SKU分页列表
func (c *goodsSkuServiceClient) PageGoodsSku(ctx context.Context, in *PageGoodsSkuRequest, opts ...grpc.CallOption) (*PageGoodsSkuResponse, error) {
	out := new(PageGoodsSkuResponse)
	err := c.cc.Invoke(ctx, "Service/admin.GoodsSkuService/PageGoodsSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// 查询商品SKU
func (c *goodsSkuServiceClient) GetGoodsSku(ctx context.Context, in *wrapperspb.Int64Value, opts ...grpc.CallOption) (*GoodsSku, error) {
	out := new(GoodsSku)
	err := c.cc.Invoke(ctx, "Service/admin.GoodsSkuService/GetGoodsSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// 更新商品SKU
func (c *goodsSkuServiceClient) UpdateGoodsSku(ctx context.Context, in *GoodsSku, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "Service/admin.GoodsSkuService/UpdateGoodsSku", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ================== 服务端 接口、空结构、方法、注册器、句柄、描述 ===================

// GoodsSkuServiceServer is the server API for GoodsSkuService service.
// All implementations must embed UnimplementedGoodsSkuServiceServer
// for forward compatibility
// Server interface. Admin商品SKU服务
type GoodsSkuServiceServer interface {
	// 查询商品SKU分页列表
	PageGoodsSku(ctx context.Context, req *PageGoodsSkuRequest) (*PageGoodsSkuResponse, error)
	// 查询商品SKU
	GetGoodsSku(ctx context.Context, req *wrapperspb.Int64Value) (*GoodsSku, error)
	// 更新商品SKU
	UpdateGoodsSku(ctx context.Context, req *GoodsSku) (*emptypb.Empty, error)
	mustEmbedUnimplementedGoodsSkuServiceServer()
}

// UnimplementedGoodsSkuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsSkuServiceServer struct {
}

func (UnimplementedGoodsSkuServiceServer) PageGoodsSku(ctx context.Context, req *PageGoodsSkuRequest) (*PageGoodsSkuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageGoodsSku not implemented")
}

func (UnimplementedGoodsSkuServiceServer) GetGoodsSku(ctx context.Context, req *wrapperspb.Int64Value) (*GoodsSku, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsSku not implemented")
}

func (UnimplementedGoodsSkuServiceServer) UpdateGoodsSku(ctx context.Context, req *GoodsSku) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoodsSku not implemented")
}

func (UnimplementedGoodsSkuServiceServer) mustEmbedUnimplementedGoodsSkuServiceServer() {}

// Server registration of GoodsSkuService
func RegisterGoodsSkuServiceServer(s grpc.ServiceRegistrar, srv GoodsSkuServiceServer) {
	s.RegisterService(&GoodsSkuService_ServiceDesc, srv)
}

// 查询商品SKU分页列表
func _GoodsSkuService_PageGoodsSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageGoodsSkuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSkuServiceServer).PageGoodsSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "Service/admin.GoodsSkuService/PageGoodsSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSkuServiceServer).PageGoodsSku(ctx, req.(*PageGoodsSkuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// 查询商品SKU
func _GoodsSkuService_GetGoodsSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.Int64Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSkuServiceServer).GetGoodsSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "Service/admin.GoodsSkuService/GetGoodsSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSkuServiceServer).GetGoodsSku(ctx, req.(*wrapperspb.Int64Value))
	}
	return interceptor(ctx, in, info, handler)
}

// 更新商品SKU
func _GoodsSkuService_UpdateGoodsSku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsSku)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSkuServiceServer).UpdateGoodsSku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "Service/admin.GoodsSkuService/UpdateGoodsSku",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSkuServiceServer).UpdateGoodsSku(ctx, req.(*GoodsSku))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsSkuService_ServiceDesc is the grpc.ServiceDesc for GoodsSkuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsSkuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Service/admin.GoodsSkuService",
	HandlerType: (*GoodsSkuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PageGoodsSku",
			Handler:    _GoodsSkuService_PageGoodsSku_Handler,
		},
		{
			MethodName: "GetGoodsSku",
			Handler:    _GoodsSkuService_GetGoodsSku_Handler,
		},
		{
			MethodName: "UpdateGoodsSku",
			Handler:    _GoodsSkuService_UpdateGoodsSku_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/goods_sku.proto",
}

// ================== 本地激发 local instance 结构、工厂、方法 ===================

// LocalInstance of GoodsSkuService
// Admin商品SKU服务
type goodsSkuServiceInstance struct {
	goodsSkuServiceImpl GoodsSkuServiceServer
}

// NewGoodsSkuServiceInstance create a new local instance of GoodsSkuService
// Admin商品SKU服务
func NewGoodsSkuServiceInstance(svcImpl GoodsSkuServiceServer) GoodsSkuServiceClient {
	c := goodsSkuServiceInstance{
		goodsSkuServiceImpl: svcImpl,
	}
	return &c
}

// 查询商品SKU分页列表
func (c *goodsSkuServiceInstance) PageGoodsSku(ctx context.Context, in *PageGoodsSkuRequest, nilOpts ...grpc.CallOption) (*PageGoodsSkuResponse, error) {
	out, err := c.goodsSkuServiceImpl.PageGoodsSku(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// 查询商品SKU
func (c *goodsSkuServiceInstance) GetGoodsSku(ctx context.Context, in *wrapperspb.Int64Value, nilOpts ...grpc.CallOption) (*GoodsSku, error) {
	out, err := c.goodsSkuServiceImpl.GetGoodsSku(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// 更新商品SKU
func (c *goodsSkuServiceInstance) UpdateGoodsSku(ctx context.Context, in *GoodsSku, nilOpts ...grpc.CallOption) (*emptypb.Empty, error) {
	out, err := c.goodsSkuServiceImpl.UpdateGoodsSku(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}
