// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/order.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "gitee.com/liujit/shop/server/api/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.OrderStatus(0)
)

// Validate checks the field values on PageOrderRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageOrderRequestMultiError, or nil if none found.
func (m *PageOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	// no validation rules for UserId

	// no validation rules for PageNum

	// no validation rules for PageSize

	if m.Status != nil {
		// no validation rules for Status
	}

	if m.PayType != nil {
		// no validation rules for PayType
	}

	if m.PayChannel != nil {
		// no validation rules for PayChannel
	}

	if len(errors) > 0 {
		return PageOrderRequestMultiError(errors)
	}

	return nil
}

// PageOrderRequestMultiError is an error wrapping multiple validation errors
// returned by PageOrderRequest.ValidateAll() if the designated constraints
// aren't met.
type PageOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageOrderRequestMultiError) AllErrors() []error { return m }

// PageOrderRequestValidationError is the validation error returned by
// PageOrderRequest.Validate if the designated constraints aren't met.
type PageOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageOrderRequestValidationError) ErrorName() string { return "PageOrderRequestValidationError" }

// Error satisfies the builtin error interface
func (e PageOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageOrderRequestValidationError{}

// Validate checks the field values on PageOrderResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageOrderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageOrderResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageOrderResponseMultiError, or nil if none found.
func (m *PageOrderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageOrderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageOrderResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageOrderResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageOrderResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageOrderResponseMultiError(errors)
	}

	return nil
}

// PageOrderResponseMultiError is an error wrapping multiple validation errors
// returned by PageOrderResponse.ValidateAll() if the designated constraints
// aren't met.
type PageOrderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageOrderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageOrderResponseMultiError) AllErrors() []error { return m }

// PageOrderResponseValidationError is the validation error returned by
// PageOrderResponse.Validate if the designated constraints aren't met.
type PageOrderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageOrderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageOrderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageOrderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageOrderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageOrderResponseValidationError) ErrorName() string {
	return "PageOrderResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageOrderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageOrderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageOrderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageOrderResponseValidationError{}

// Validate checks the field values on OrderResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderResponseMultiError, or
// nil if none found.
func (m *OrderResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOrder()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Order",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Order",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOrder()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderResponseValidationError{
				field:  "Order",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Countdown

	if all {
		switch v := interface{}(m.GetAddress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Address",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Address",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderResponseValidationError{
				field:  "Address",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCancel()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Cancel",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Cancel",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCancel()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderResponseValidationError{
				field:  "Cancel",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetGoods() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrderResponseValidationError{
						field:  fmt.Sprintf("Goods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrderResponseValidationError{
						field:  fmt.Sprintf("Goods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderResponseValidationError{
					field:  fmt.Sprintf("Goods[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetLogistics()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Logistics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Logistics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLogistics()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderResponseValidationError{
				field:  "Logistics",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderResponseValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRefund() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrderResponseValidationError{
						field:  fmt.Sprintf("Refund[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrderResponseValidationError{
						field:  fmt.Sprintf("Refund[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderResponseValidationError{
					field:  fmt.Sprintf("Refund[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OrderResponseMultiError(errors)
	}

	return nil
}

// OrderResponseMultiError is an error wrapping multiple validation errors
// returned by OrderResponse.ValidateAll() if the designated constraints
// aren't met.
type OrderResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderResponseMultiError) AllErrors() []error { return m }

// OrderResponseValidationError is the validation error returned by
// OrderResponse.Validate if the designated constraints aren't met.
type OrderResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderResponseValidationError) ErrorName() string { return "OrderResponseValidationError" }

// Error satisfies the builtin error interface
func (e OrderResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderResponseValidationError{}

// Validate checks the field values on OrderRefundResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderRefundResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderRefundResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderRefundResponseMultiError, or nil if none found.
func (m *OrderRefundResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderRefundResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPayment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderRefundResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderRefundResponseValidationError{
					field:  "Payment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderRefundResponseValidationError{
				field:  "Payment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetRefund() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrderRefundResponseValidationError{
						field:  fmt.Sprintf("Refund[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrderRefundResponseValidationError{
						field:  fmt.Sprintf("Refund[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderRefundResponseValidationError{
					field:  fmt.Sprintf("Refund[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return OrderRefundResponseMultiError(errors)
	}

	return nil
}

// OrderRefundResponseMultiError is an error wrapping multiple validation
// errors returned by OrderRefundResponse.ValidateAll() if the designated
// constraints aren't met.
type OrderRefundResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderRefundResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderRefundResponseMultiError) AllErrors() []error { return m }

// OrderRefundResponseValidationError is the validation error returned by
// OrderRefundResponse.Validate if the designated constraints aren't met.
type OrderRefundResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderRefundResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderRefundResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderRefundResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderRefundResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderRefundResponseValidationError) ErrorName() string {
	return "OrderRefundResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OrderRefundResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderRefundResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderRefundResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderRefundResponseValidationError{}

// Validate checks the field values on RefundOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefundOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefundOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefundOrderRequestMultiError, or nil if none found.
func (m *RefundOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefundOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	// no validation rules for RefundMoney

	if m.Reason != nil {
		// no validation rules for Reason
	}

	if len(errors) > 0 {
		return RefundOrderRequestMultiError(errors)
	}

	return nil
}

// RefundOrderRequestMultiError is an error wrapping multiple validation errors
// returned by RefundOrderRequest.ValidateAll() if the designated constraints
// aren't met.
type RefundOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefundOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefundOrderRequestMultiError) AllErrors() []error { return m }

// RefundOrderRequestValidationError is the validation error returned by
// RefundOrderRequest.Validate if the designated constraints aren't met.
type RefundOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefundOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefundOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefundOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefundOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefundOrderRequestValidationError) ErrorName() string {
	return "RefundOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RefundOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefundOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefundOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefundOrderRequestValidationError{}

// Validate checks the field values on OrderShippedResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderShippedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderShippedResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderShippedResponseMultiError, or nil if none found.
func (m *OrderShippedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderShippedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAddress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderShippedResponseValidationError{
					field:  "Address",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderShippedResponseValidationError{
					field:  "Address",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderShippedResponseValidationError{
				field:  "Address",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetGoods() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrderShippedResponseValidationError{
						field:  fmt.Sprintf("Goods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrderShippedResponseValidationError{
						field:  fmt.Sprintf("Goods[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderShippedResponseValidationError{
					field:  fmt.Sprintf("Goods[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetLogistics()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderShippedResponseValidationError{
					field:  "Logistics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderShippedResponseValidationError{
					field:  "Logistics",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLogistics()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderShippedResponseValidationError{
				field:  "Logistics",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return OrderShippedResponseMultiError(errors)
	}

	return nil
}

// OrderShippedResponseMultiError is an error wrapping multiple validation
// errors returned by OrderShippedResponse.ValidateAll() if the designated
// constraints aren't met.
type OrderShippedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderShippedResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderShippedResponseMultiError) AllErrors() []error { return m }

// OrderShippedResponseValidationError is the validation error returned by
// OrderShippedResponse.Validate if the designated constraints aren't met.
type OrderShippedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderShippedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderShippedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderShippedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderShippedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderShippedResponseValidationError) ErrorName() string {
	return "OrderShippedResponseValidationError"
}

// Error satisfies the builtin error interface
func (e OrderShippedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderShippedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderShippedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderShippedResponseValidationError{}

// Validate checks the field values on ShippedOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ShippedOrderRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShippedOrderRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ShippedOrderRequestMultiError, or nil if none found.
func (m *ShippedOrderRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ShippedOrderRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderId

	// no validation rules for Name

	// no validation rules for No

	// no validation rules for Contact

	if len(errors) > 0 {
		return ShippedOrderRequestMultiError(errors)
	}

	return nil
}

// ShippedOrderRequestMultiError is an error wrapping multiple validation
// errors returned by ShippedOrderRequest.ValidateAll() if the designated
// constraints aren't met.
type ShippedOrderRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShippedOrderRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShippedOrderRequestMultiError) AllErrors() []error { return m }

// ShippedOrderRequestValidationError is the validation error returned by
// ShippedOrderRequest.Validate if the designated constraints aren't met.
type ShippedOrderRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShippedOrderRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShippedOrderRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShippedOrderRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShippedOrderRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShippedOrderRequestValidationError) ErrorName() string {
	return "ShippedOrderRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ShippedOrderRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShippedOrderRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShippedOrderRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShippedOrderRequestValidationError{}

// Validate checks the field values on Order with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Order) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Order with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in OrderMultiError, or nil if none found.
func (m *Order) ValidateAll() error {
	return m.validate(true)
}

func (m *Order) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for OrderNo

	// no validation rules for UserId

	// no validation rules for PayMoney

	// no validation rules for TotalMoney

	// no validation rules for PostFee

	// no validation rules for GoodsNum

	// no validation rules for PayType

	// no validation rules for PayChannel

	// no validation rules for DeliveryTime

	// no validation rules for Status

	// no validation rules for Remark

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	// no validation rules for NickName

	if len(errors) > 0 {
		return OrderMultiError(errors)
	}

	return nil
}

// OrderMultiError is an error wrapping multiple validation errors returned by
// Order.ValidateAll() if the designated constraints aren't met.
type OrderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderMultiError) AllErrors() []error { return m }

// OrderValidationError is the validation error returned by Order.Validate if
// the designated constraints aren't met.
type OrderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderValidationError) ErrorName() string { return "OrderValidationError" }

// Error satisfies the builtin error interface
func (e OrderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrder.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderValidationError{}

// Validate checks the field values on OrderAddress with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderAddress) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderAddress with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderAddressMultiError, or
// nil if none found.
func (m *OrderAddress) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderAddress) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Receiver

	// no validation rules for Contact

	// no validation rules for Detail

	if len(errors) > 0 {
		return OrderAddressMultiError(errors)
	}

	return nil
}

// OrderAddressMultiError is an error wrapping multiple validation errors
// returned by OrderAddress.ValidateAll() if the designated constraints aren't met.
type OrderAddressMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderAddressMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderAddressMultiError) AllErrors() []error { return m }

// OrderAddressValidationError is the validation error returned by
// OrderAddress.Validate if the designated constraints aren't met.
type OrderAddressValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderAddressValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderAddressValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderAddressValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderAddressValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderAddressValidationError) ErrorName() string { return "OrderAddressValidationError" }

// Error satisfies the builtin error interface
func (e OrderAddressValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderAddress.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderAddressValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderAddressValidationError{}

// Validate checks the field values on OrderCancel with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderCancel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderCancel with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderCancelMultiError, or
// nil if none found.
func (m *OrderCancel) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderCancel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Reason

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return OrderCancelMultiError(errors)
	}

	return nil
}

// OrderCancelMultiError is an error wrapping multiple validation errors
// returned by OrderCancel.ValidateAll() if the designated constraints aren't met.
type OrderCancelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderCancelMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderCancelMultiError) AllErrors() []error { return m }

// OrderCancelValidationError is the validation error returned by
// OrderCancel.Validate if the designated constraints aren't met.
type OrderCancelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderCancelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderCancelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderCancelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderCancelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderCancelValidationError) ErrorName() string { return "OrderCancelValidationError" }

// Error satisfies the builtin error interface
func (e OrderCancelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderCancel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderCancelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderCancelValidationError{}

// Validate checks the field values on OrderGoods with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderGoods) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderGoods with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderGoodsMultiError, or
// nil if none found.
func (m *OrderGoods) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderGoods) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GoodsId

	// no validation rules for SkuCode

	// no validation rules for Picture

	// no validation rules for Name

	// no validation rules for Num

	// no validation rules for Price

	// no validation rules for PayPrice

	// no validation rules for TotalPrice

	// no validation rules for TotalPayPrice

	if len(errors) > 0 {
		return OrderGoodsMultiError(errors)
	}

	return nil
}

// OrderGoodsMultiError is an error wrapping multiple validation errors
// returned by OrderGoods.ValidateAll() if the designated constraints aren't met.
type OrderGoodsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderGoodsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderGoodsMultiError) AllErrors() []error { return m }

// OrderGoodsValidationError is the validation error returned by
// OrderGoods.Validate if the designated constraints aren't met.
type OrderGoodsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderGoodsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderGoodsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderGoodsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderGoodsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderGoodsValidationError) ErrorName() string { return "OrderGoodsValidationError" }

// Error satisfies the builtin error interface
func (e OrderGoodsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderGoods.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderGoodsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderGoodsValidationError{}

// Validate checks the field values on OrderLogistics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderLogistics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderLogistics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderLogisticsMultiError,
// or nil if none found.
func (m *OrderLogistics) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderLogistics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for No

	// no validation rules for Contact

	for idx, item := range m.GetDetail() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, OrderLogisticsValidationError{
						field:  fmt.Sprintf("Detail[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, OrderLogisticsValidationError{
						field:  fmt.Sprintf("Detail[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return OrderLogisticsValidationError{
					field:  fmt.Sprintf("Detail[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return OrderLogisticsMultiError(errors)
	}

	return nil
}

// OrderLogisticsMultiError is an error wrapping multiple validation errors
// returned by OrderLogistics.ValidateAll() if the designated constraints
// aren't met.
type OrderLogisticsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderLogisticsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderLogisticsMultiError) AllErrors() []error { return m }

// OrderLogisticsValidationError is the validation error returned by
// OrderLogistics.Validate if the designated constraints aren't met.
type OrderLogisticsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderLogisticsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderLogisticsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderLogisticsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderLogisticsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderLogisticsValidationError) ErrorName() string { return "OrderLogisticsValidationError" }

// Error satisfies the builtin error interface
func (e OrderLogisticsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderLogistics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderLogisticsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderLogisticsValidationError{}

// Validate checks the field values on OrderPayment with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderPayment) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPayment with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderPaymentMultiError, or
// nil if none found.
func (m *OrderPayment) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPayment) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	// no validation rules for ThirdOrderNo

	// no validation rules for TradeType

	// no validation rules for TradeState

	// no validation rules for TradeStateDesc

	// no validation rules for BankType

	// no validation rules for SuccessTime

	if all {
		switch v := interface{}(m.GetPayer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "Payer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "Payer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPayer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderPaymentValidationError{
				field:  "Payer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderPaymentValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSceneInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "SceneInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderPaymentValidationError{
					field:  "SceneInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSceneInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderPaymentValidationError{
				field:  "SceneInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return OrderPaymentMultiError(errors)
	}

	return nil
}

// OrderPaymentMultiError is an error wrapping multiple validation errors
// returned by OrderPayment.ValidateAll() if the designated constraints aren't met.
type OrderPaymentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPaymentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPaymentMultiError) AllErrors() []error { return m }

// OrderPaymentValidationError is the validation error returned by
// OrderPayment.Validate if the designated constraints aren't met.
type OrderPaymentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPaymentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPaymentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPaymentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPaymentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPaymentValidationError) ErrorName() string { return "OrderPaymentValidationError" }

// Error satisfies the builtin error interface
func (e OrderPaymentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPayment.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPaymentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPaymentValidationError{}

// Validate checks the field values on OrderRefund with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderRefund) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderRefund with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderRefundMultiError, or
// nil if none found.
func (m *OrderRefund) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderRefund) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OrderNo

	// no validation rules for ThirdOrderNo

	// no validation rules for RefundNo

	// no validation rules for Reason

	// no validation rules for ThirdRefundNo

	// no validation rules for Channel

	// no validation rules for UserReceivedAccount

	// no validation rules for CreateTime

	// no validation rules for SuccessTime

	// no validation rules for RefundState

	// no validation rules for FundsAccount

	if all {
		switch v := interface{}(m.GetAmount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, OrderRefundValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, OrderRefundValidationError{
					field:  "Amount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAmount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return OrderRefundValidationError{
				field:  "Amount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Status

	if len(errors) > 0 {
		return OrderRefundMultiError(errors)
	}

	return nil
}

// OrderRefundMultiError is an error wrapping multiple validation errors
// returned by OrderRefund.ValidateAll() if the designated constraints aren't met.
type OrderRefundMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderRefundMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderRefundMultiError) AllErrors() []error { return m }

// OrderRefundValidationError is the validation error returned by
// OrderRefund.Validate if the designated constraints aren't met.
type OrderRefundValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderRefundValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderRefundValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderRefundValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderRefundValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderRefundValidationError) ErrorName() string { return "OrderRefundValidationError" }

// Error satisfies the builtin error interface
func (e OrderRefundValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderRefund.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderRefundValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderRefundValidationError{}

// Validate checks the field values on OrderLogistics_Detail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderLogistics_Detail) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderLogistics_Detail with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderLogistics_DetailMultiError, or nil if none found.
func (m *OrderLogistics_Detail) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderLogistics_Detail) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Time

	// no validation rules for Text

	if len(errors) > 0 {
		return OrderLogistics_DetailMultiError(errors)
	}

	return nil
}

// OrderLogistics_DetailMultiError is an error wrapping multiple validation
// errors returned by OrderLogistics_Detail.ValidateAll() if the designated
// constraints aren't met.
type OrderLogistics_DetailMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderLogistics_DetailMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderLogistics_DetailMultiError) AllErrors() []error { return m }

// OrderLogistics_DetailValidationError is the validation error returned by
// OrderLogistics_Detail.Validate if the designated constraints aren't met.
type OrderLogistics_DetailValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderLogistics_DetailValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderLogistics_DetailValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderLogistics_DetailValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderLogistics_DetailValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderLogistics_DetailValidationError) ErrorName() string {
	return "OrderLogistics_DetailValidationError"
}

// Error satisfies the builtin error interface
func (e OrderLogistics_DetailValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderLogistics_Detail.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderLogistics_DetailValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderLogistics_DetailValidationError{}

// Validate checks the field values on OrderPayment_Payer with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderPayment_Payer) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPayment_Payer with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderPayment_PayerMultiError, or nil if none found.
func (m *OrderPayment_Payer) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPayment_Payer) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Openid

	if len(errors) > 0 {
		return OrderPayment_PayerMultiError(errors)
	}

	return nil
}

// OrderPayment_PayerMultiError is an error wrapping multiple validation errors
// returned by OrderPayment_Payer.ValidateAll() if the designated constraints
// aren't met.
type OrderPayment_PayerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPayment_PayerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPayment_PayerMultiError) AllErrors() []error { return m }

// OrderPayment_PayerValidationError is the validation error returned by
// OrderPayment_Payer.Validate if the designated constraints aren't met.
type OrderPayment_PayerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPayment_PayerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPayment_PayerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPayment_PayerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPayment_PayerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPayment_PayerValidationError) ErrorName() string {
	return "OrderPayment_PayerValidationError"
}

// Error satisfies the builtin error interface
func (e OrderPayment_PayerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPayment_Payer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPayment_PayerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPayment_PayerValidationError{}

// Validate checks the field values on OrderPayment_Amount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderPayment_Amount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPayment_Amount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderPayment_AmountMultiError, or nil if none found.
func (m *OrderPayment_Amount) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPayment_Amount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PayerTotal

	// no validation rules for Total

	// no validation rules for Currency

	// no validation rules for PayerCurrency

	if len(errors) > 0 {
		return OrderPayment_AmountMultiError(errors)
	}

	return nil
}

// OrderPayment_AmountMultiError is an error wrapping multiple validation
// errors returned by OrderPayment_Amount.ValidateAll() if the designated
// constraints aren't met.
type OrderPayment_AmountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPayment_AmountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPayment_AmountMultiError) AllErrors() []error { return m }

// OrderPayment_AmountValidationError is the validation error returned by
// OrderPayment_Amount.Validate if the designated constraints aren't met.
type OrderPayment_AmountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPayment_AmountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPayment_AmountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPayment_AmountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPayment_AmountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPayment_AmountValidationError) ErrorName() string {
	return "OrderPayment_AmountValidationError"
}

// Error satisfies the builtin error interface
func (e OrderPayment_AmountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPayment_Amount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPayment_AmountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPayment_AmountValidationError{}

// Validate checks the field values on OrderPayment_SceneInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderPayment_SceneInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderPayment_SceneInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderPayment_SceneInfoMultiError, or nil if none found.
func (m *OrderPayment_SceneInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderPayment_SceneInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DeviceId

	if len(errors) > 0 {
		return OrderPayment_SceneInfoMultiError(errors)
	}

	return nil
}

// OrderPayment_SceneInfoMultiError is an error wrapping multiple validation
// errors returned by OrderPayment_SceneInfo.ValidateAll() if the designated
// constraints aren't met.
type OrderPayment_SceneInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderPayment_SceneInfoMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderPayment_SceneInfoMultiError) AllErrors() []error { return m }

// OrderPayment_SceneInfoValidationError is the validation error returned by
// OrderPayment_SceneInfo.Validate if the designated constraints aren't met.
type OrderPayment_SceneInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderPayment_SceneInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderPayment_SceneInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderPayment_SceneInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderPayment_SceneInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderPayment_SceneInfoValidationError) ErrorName() string {
	return "OrderPayment_SceneInfoValidationError"
}

// Error satisfies the builtin error interface
func (e OrderPayment_SceneInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderPayment_SceneInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderPayment_SceneInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderPayment_SceneInfoValidationError{}

// Validate checks the field values on OrderRefund_Amount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderRefund_Amount) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderRefund_Amount with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderRefund_AmountMultiError, or nil if none found.
func (m *OrderRefund_Amount) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderRefund_Amount) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	// no validation rules for Refund

	// no validation rules for PayerTotal

	// no validation rules for PayerRefund

	if len(errors) > 0 {
		return OrderRefund_AmountMultiError(errors)
	}

	return nil
}

// OrderRefund_AmountMultiError is an error wrapping multiple validation errors
// returned by OrderRefund_Amount.ValidateAll() if the designated constraints
// aren't met.
type OrderRefund_AmountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderRefund_AmountMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderRefund_AmountMultiError) AllErrors() []error { return m }

// OrderRefund_AmountValidationError is the validation error returned by
// OrderRefund_Amount.Validate if the designated constraints aren't met.
type OrderRefund_AmountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderRefund_AmountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderRefund_AmountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderRefund_AmountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderRefund_AmountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderRefund_AmountValidationError) ErrorName() string {
	return "OrderRefund_AmountValidationError"
}

// Error satisfies the builtin error interface
func (e OrderRefund_AmountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderRefund_Amount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderRefund_AmountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderRefund_AmountValidationError{}
