// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/shop_banner.proto

package admin

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "gitee.com/liujit/shop/server/api/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.ShopBannerSite(0)
)

// Validate checks the field values on PageShopBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageShopBannerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageShopBannerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageShopBannerRequestMultiError, or nil if none found.
func (m *PageShopBannerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageShopBannerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageNum

	// no validation rules for PageSize

	if m.Site != nil {
		// no validation rules for Site
	}

	if m.Type != nil {
		// no validation rules for Type
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return PageShopBannerRequestMultiError(errors)
	}

	return nil
}

// PageShopBannerRequestMultiError is an error wrapping multiple validation
// errors returned by PageShopBannerRequest.ValidateAll() if the designated
// constraints aren't met.
type PageShopBannerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageShopBannerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageShopBannerRequestMultiError) AllErrors() []error { return m }

// PageShopBannerRequestValidationError is the validation error returned by
// PageShopBannerRequest.Validate if the designated constraints aren't met.
type PageShopBannerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageShopBannerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageShopBannerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageShopBannerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageShopBannerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageShopBannerRequestValidationError) ErrorName() string {
	return "PageShopBannerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageShopBannerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageShopBannerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageShopBannerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageShopBannerRequestValidationError{}

// Validate checks the field values on PageShopBannerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageShopBannerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageShopBannerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageShopBannerResponseMultiError, or nil if none found.
func (m *PageShopBannerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageShopBannerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageShopBannerResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageShopBannerResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageShopBannerResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageShopBannerResponseMultiError(errors)
	}

	return nil
}

// PageShopBannerResponseMultiError is an error wrapping multiple validation
// errors returned by PageShopBannerResponse.ValidateAll() if the designated
// constraints aren't met.
type PageShopBannerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageShopBannerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageShopBannerResponseMultiError) AllErrors() []error { return m }

// PageShopBannerResponseValidationError is the validation error returned by
// PageShopBannerResponse.Validate if the designated constraints aren't met.
type PageShopBannerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageShopBannerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageShopBannerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageShopBannerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageShopBannerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageShopBannerResponseValidationError) ErrorName() string {
	return "PageShopBannerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageShopBannerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageShopBannerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageShopBannerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageShopBannerResponseValidationError{}

// Validate checks the field values on ShopBanner with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShopBanner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShopBanner with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShopBannerMultiError, or
// nil if none found.
func (m *ShopBanner) ValidateAll() error {
	return m.validate(true)
}

func (m *ShopBanner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Site

	// no validation rules for Picture

	// no validation rules for Type

	// no validation rules for Href

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return ShopBannerMultiError(errors)
	}

	return nil
}

// ShopBannerMultiError is an error wrapping multiple validation errors
// returned by ShopBanner.ValidateAll() if the designated constraints aren't met.
type ShopBannerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShopBannerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShopBannerMultiError) AllErrors() []error { return m }

// ShopBannerValidationError is the validation error returned by
// ShopBanner.Validate if the designated constraints aren't met.
type ShopBannerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShopBannerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShopBannerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShopBannerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShopBannerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShopBannerValidationError) ErrorName() string { return "ShopBannerValidationError" }

// Error satisfies the builtin error interface
func (e ShopBannerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShopBanner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShopBannerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShopBannerValidationError{}

// Validate checks the field values on ShopBannerForm with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShopBannerForm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShopBannerForm with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShopBannerFormMultiError,
// or nil if none found.
func (m *ShopBannerForm) ValidateAll() error {
	return m.validate(true)
}

func (m *ShopBannerForm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Picture

	// no validation rules for Href

	// no validation rules for Sort

	if m.Site != nil {
		// no validation rules for Site
	}

	if m.Type != nil {
		// no validation rules for Type
	}

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return ShopBannerFormMultiError(errors)
	}

	return nil
}

// ShopBannerFormMultiError is an error wrapping multiple validation errors
// returned by ShopBannerForm.ValidateAll() if the designated constraints
// aren't met.
type ShopBannerFormMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShopBannerFormMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShopBannerFormMultiError) AllErrors() []error { return m }

// ShopBannerFormValidationError is the validation error returned by
// ShopBannerForm.Validate if the designated constraints aren't met.
type ShopBannerFormValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShopBannerFormValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShopBannerFormValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShopBannerFormValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShopBannerFormValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShopBannerFormValidationError) ErrorName() string { return "ShopBannerFormValidationError" }

// Error satisfies the builtin error interface
func (e ShopBannerFormValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShopBannerForm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShopBannerFormValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShopBannerFormValidationError{}
