// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: admin/shop_banner.proto

package admin

import (
	common "gitee.com/liujit/shop/server/api/common"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageShopBannerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 位置：枚举【ShopBannerSite】
	Site *common.ShopBannerSite `protobuf:"varint,1,opt,name=site,proto3,enum=common.ShopBannerSite,oneof" json:"site,omitempty"`
	// 跳转类型：枚举【ShopBannerType】
	Type *common.ShopBannerType `protobuf:"varint,2,opt,name=type,proto3,enum=common.ShopBannerType,oneof" json:"type,omitempty"`
	// 状态
	Status *common.Status `protobuf:"varint,100,opt,name=status,proto3,enum=common.Status,oneof" json:"status,omitempty"`
	// 当前页码
	PageNum int64 `protobuf:"varint,101,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 每一页的行数
	PageSize      int64 `protobuf:"varint,102,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageShopBannerRequest) Reset() {
	*x = PageShopBannerRequest{}
	mi := &file_admin_shop_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageShopBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageShopBannerRequest) ProtoMessage() {}

func (x *PageShopBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_shop_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageShopBannerRequest.ProtoReflect.Descriptor instead.
func (*PageShopBannerRequest) Descriptor() ([]byte, []int) {
	return file_admin_shop_banner_proto_rawDescGZIP(), []int{0}
}

func (x *PageShopBannerRequest) GetSite() common.ShopBannerSite {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return common.ShopBannerSite(0)
}

func (x *PageShopBannerRequest) GetType() common.ShopBannerType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return common.ShopBannerType(0)
}

func (x *PageShopBannerRequest) GetStatus() common.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return common.Status(0)
}

func (x *PageShopBannerRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageShopBannerRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageShopBannerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页数据
	List []*ShopBanner `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageShopBannerResponse) Reset() {
	*x = PageShopBannerResponse{}
	mi := &file_admin_shop_banner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageShopBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageShopBannerResponse) ProtoMessage() {}

func (x *PageShopBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_shop_banner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageShopBannerResponse.ProtoReflect.Descriptor instead.
func (*PageShopBannerResponse) Descriptor() ([]byte, []int) {
	return file_admin_shop_banner_proto_rawDescGZIP(), []int{1}
}

func (x *PageShopBannerResponse) GetList() []*ShopBanner {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PageShopBannerResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShopBanner struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 位置：枚举【ShopBannerSite】
	Site common.ShopBannerSite `protobuf:"varint,2,opt,name=site,proto3,enum=common.ShopBannerSite" json:"site,omitempty"`
	// 图片链接
	Picture string `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	// 跳转类型：枚举【ShopBannerType】
	Type common.ShopBannerType `protobuf:"varint,4,opt,name=type,proto3,enum=common.ShopBannerType" json:"type,omitempty"`
	// 跳转地址
	Href string `protobuf:"bytes,5,opt,name=href,proto3" json:"href,omitempty"`
	// 排序
	Sort int32 `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	// 状态
	Status        common.Status `protobuf:"varint,100,opt,name=status,proto3,enum=common.Status" json:"status,omitempty"`
	CreatedAt     string        `protobuf:"bytes,200,opt,name=createdAt,proto3" json:"createdAt,omitempty"` // 创建时间
	UpdatedAt     string        `protobuf:"bytes,201,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopBanner) Reset() {
	*x = ShopBanner{}
	mi := &file_admin_shop_banner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopBanner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBanner) ProtoMessage() {}

func (x *ShopBanner) ProtoReflect() protoreflect.Message {
	mi := &file_admin_shop_banner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBanner.ProtoReflect.Descriptor instead.
func (*ShopBanner) Descriptor() ([]byte, []int) {
	return file_admin_shop_banner_proto_rawDescGZIP(), []int{2}
}

func (x *ShopBanner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopBanner) GetSite() common.ShopBannerSite {
	if x != nil {
		return x.Site
	}
	return common.ShopBannerSite(0)
}

func (x *ShopBanner) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ShopBanner) GetType() common.ShopBannerType {
	if x != nil {
		return x.Type
	}
	return common.ShopBannerType(0)
}

func (x *ShopBanner) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *ShopBanner) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ShopBanner) GetStatus() common.Status {
	if x != nil {
		return x.Status
	}
	return common.Status(0)
}

func (x *ShopBanner) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ShopBanner) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ShopBannerForm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 主键id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 位置：枚举【ShopBannerSite】
	Site *common.ShopBannerSite `protobuf:"varint,2,opt,name=site,proto3,enum=common.ShopBannerSite,oneof" json:"site,omitempty"`
	// 图片链接
	Picture string `protobuf:"bytes,3,opt,name=picture,proto3" json:"picture,omitempty"`
	// 跳转类型：枚举【ShopBannerType】
	Type *common.ShopBannerType `protobuf:"varint,4,opt,name=type,proto3,enum=common.ShopBannerType,oneof" json:"type,omitempty"`
	// 跳转地址
	Href string `protobuf:"bytes,5,opt,name=href,proto3" json:"href,omitempty"`
	// 排序
	Sort          int32          `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Status        *common.Status `protobuf:"varint,100,opt,name=status,proto3,enum=common.Status,oneof" json:"status,omitempty"` // 状态：枚举【Status】
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopBannerForm) Reset() {
	*x = ShopBannerForm{}
	mi := &file_admin_shop_banner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopBannerForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBannerForm) ProtoMessage() {}

func (x *ShopBannerForm) ProtoReflect() protoreflect.Message {
	mi := &file_admin_shop_banner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBannerForm.ProtoReflect.Descriptor instead.
func (*ShopBannerForm) Descriptor() ([]byte, []int) {
	return file_admin_shop_banner_proto_rawDescGZIP(), []int{3}
}

func (x *ShopBannerForm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopBannerForm) GetSite() common.ShopBannerSite {
	if x != nil && x.Site != nil {
		return *x.Site
	}
	return common.ShopBannerSite(0)
}

func (x *ShopBannerForm) GetPicture() string {
	if x != nil {
		return x.Picture
	}
	return ""
}

func (x *ShopBannerForm) GetType() common.ShopBannerType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return common.ShopBannerType(0)
}

func (x *ShopBannerForm) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *ShopBannerForm) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ShopBannerForm) GetStatus() common.Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return common.Status(0)
}

var File_admin_shop_banner_proto protoreflect.FileDescriptor

const file_admin_shop_banner_proto_rawDesc = "" +
	"\n" +
	"\x17admin/shop_banner.proto\x12\x05admin\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x13common/common.proto\x1a\x11common/enum.proto\"\xa9\x03\n" +
	"\x15PageShopBannerRequest\x12Z\n" +
	"\x04site\x18\x01 \x01(\x0e2\x16.common.ShopBannerSiteB)\xbaG&\x92\x02#位置：枚举【ShopBannerSite】H\x00R\x04site\x88\x01\x01\x12`\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.common.ShopBannerTypeB/\xbaG,\x92\x02)跳转类型：枚举【ShopBannerType】H\x01R\x04type\x88\x01\x01\x129\n" +
	"\x06status\x18d \x01(\x0e2\x0e.common.StatusB\f\xbaG\t\x92\x02\x06状态H\x02R\x06status\x88\x01\x01\x128\n" +
	"\apageNum\x18e \x01(\x03B\x1e\xbaG\x1b\x8a\x02\t\t\x00\x00\x00\x00\x00\x00\xf0?\x92\x02\f当前页码R\apageNum\x12@\n" +
	"\bpageSize\x18f \x01(\x03B$\xbaG!\x8a\x02\t\t\x00\x00\x00\x00\x00\x00$@\x92\x02\x12每一页的行数R\bpageSizeB\a\n" +
	"\x05_siteB\a\n" +
	"\x05_typeB\t\n" +
	"\a_status\"U\n" +
	"\x16PageShopBannerResponse\x12%\n" +
	"\x04list\x18\x01 \x03(\v2\x11.admin.ShopBannerR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf4\x03\n" +
	"\n" +
	"ShopBanner\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b主键idR\x02id\x12U\n" +
	"\x04site\x18\x02 \x01(\x0e2\x16.common.ShopBannerSiteB)\xbaG&\x92\x02#位置：枚举【ShopBannerSite】R\x04site\x12,\n" +
	"\apicture\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f图片链接R\apicture\x12[\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.common.ShopBannerTypeB/\xbaG,\x92\x02)跳转类型：枚举【ShopBannerType】R\x04type\x12&\n" +
	"\x04href\x18\x05 \x01(\tB\x12\xbaG\x0f\x92\x02\f跳转地址R\x04href\x12 \n" +
	"\x04sort\x18\x06 \x01(\x05B\f\xbaG\t\x92\x02\x06排序R\x04sort\x124\n" +
	"\x06status\x18d \x01(\x0e2\x0e.common.StatusB\f\xbaG\t\x92\x02\x06状态R\x06status\x121\n" +
	"\tcreatedAt\x18\xc8\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f创建时间R\tcreatedAt\x121\n" +
	"\tupdatedAt\x18\xc9\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f更新时间R\tupdatedAt\"\xd3\x03\n" +
	"\x0eShopBannerForm\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b主键idR\x02id\x12Z\n" +
	"\x04site\x18\x02 \x01(\x0e2\x16.common.ShopBannerSiteB)\xbaG&\x92\x02#位置：枚举【ShopBannerSite】H\x00R\x04site\x88\x01\x01\x12,\n" +
	"\apicture\x18\x03 \x01(\tB\x12\xbaG\x0f\x92\x02\f图片链接R\apicture\x12`\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.common.ShopBannerTypeB/\xbaG,\x92\x02)跳转类型：枚举【ShopBannerType】H\x01R\x04type\x88\x01\x01\x12&\n" +
	"\x04href\x18\x05 \x01(\tB\x12\xbaG\x0f\x92\x02\f跳转地址R\x04href\x12 \n" +
	"\x04sort\x18\x06 \x01(\x05B\f\xbaG\t\x92\x02\x06排序R\x04sort\x12N\n" +
	"\x06status\x18d \x01(\x0e2\x0e.common.StatusB!\xbaG\x1e\x92\x02\x1b状态：枚举【Status】H\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_siteB\a\n" +
	"\x05_typeB\t\n" +
	"\a_status2\xaa\x05\n" +
	"\x11ShopBannerService\x12m\n" +
	"\x0ePageShopBanner\x12\x1c.admin.PageShopBannerRequest\x1a\x1d.admin.PageShopBannerResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/admin/shop/banner\x12k\n" +
	"\rGetShopBanner\x12\x1b.google.protobuf.Int64Value\x1a\x15.admin.ShopBannerForm\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/admin/shop/banner/{value}\x12d\n" +
	"\x10CreateShopBanner\x12\x15.admin.ShopBannerForm\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/admin/shop/banner\x12i\n" +
	"\x10UpdateShopBanner\x12\x15.admin.ShopBannerForm\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/api/admin/shop/banner/{id}\x12p\n" +
	"\x10DeleteShopBanner\x12\x1c.google.protobuf.StringValue\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 *\x1e/api/admin/shop/banner/{value}\x12v\n" +
	"\x13SetShopBannerStatus\x12\x18.common.SetStatusRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/admin/shop/banner/{id}/statusB~\n" +
	"\tcom.adminB\x0fShopBannerProtoP\x01Z,gitee.com/liujit/shop/server/api/admin;admin\xa2\x02\x03AXX\xaa\x02\x05Admin\xca\x02\x05Admin\xe2\x02\x11Admin\\GPBMetadata\xea\x02\x05Adminb\x06proto3"

var (
	file_admin_shop_banner_proto_rawDescOnce sync.Once
	file_admin_shop_banner_proto_rawDescData []byte
)

func file_admin_shop_banner_proto_rawDescGZIP() []byte {
	file_admin_shop_banner_proto_rawDescOnce.Do(func() {
		file_admin_shop_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_shop_banner_proto_rawDesc), len(file_admin_shop_banner_proto_rawDesc)))
	})
	return file_admin_shop_banner_proto_rawDescData
}

var file_admin_shop_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_admin_shop_banner_proto_goTypes = []any{
	(*PageShopBannerRequest)(nil),   // 0: admin.PageShopBannerRequest
	(*PageShopBannerResponse)(nil),  // 1: admin.PageShopBannerResponse
	(*ShopBanner)(nil),              // 2: admin.ShopBanner
	(*ShopBannerForm)(nil),          // 3: admin.ShopBannerForm
	(common.ShopBannerSite)(0),      // 4: common.ShopBannerSite
	(common.ShopBannerType)(0),      // 5: common.ShopBannerType
	(common.Status)(0),              // 6: common.Status
	(*wrapperspb.Int64Value)(nil),   // 7: google.protobuf.Int64Value
	(*wrapperspb.StringValue)(nil),  // 8: google.protobuf.StringValue
	(*common.SetStatusRequest)(nil), // 9: common.SetStatusRequest
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_admin_shop_banner_proto_depIdxs = []int32{
	4,  // 0: admin.PageShopBannerRequest.site:type_name -> common.ShopBannerSite
	5,  // 1: admin.PageShopBannerRequest.type:type_name -> common.ShopBannerType
	6,  // 2: admin.PageShopBannerRequest.status:type_name -> common.Status
	2,  // 3: admin.PageShopBannerResponse.list:type_name -> admin.ShopBanner
	4,  // 4: admin.ShopBanner.site:type_name -> common.ShopBannerSite
	5,  // 5: admin.ShopBanner.type:type_name -> common.ShopBannerType
	6,  // 6: admin.ShopBanner.status:type_name -> common.Status
	4,  // 7: admin.ShopBannerForm.site:type_name -> common.ShopBannerSite
	5,  // 8: admin.ShopBannerForm.type:type_name -> common.ShopBannerType
	6,  // 9: admin.ShopBannerForm.status:type_name -> common.Status
	0,  // 10: admin.ShopBannerService.PageShopBanner:input_type -> admin.PageShopBannerRequest
	7,  // 11: admin.ShopBannerService.GetShopBanner:input_type -> google.protobuf.Int64Value
	3,  // 12: admin.ShopBannerService.CreateShopBanner:input_type -> admin.ShopBannerForm
	3,  // 13: admin.ShopBannerService.UpdateShopBanner:input_type -> admin.ShopBannerForm
	8,  // 14: admin.ShopBannerService.DeleteShopBanner:input_type -> google.protobuf.StringValue
	9,  // 15: admin.ShopBannerService.SetShopBannerStatus:input_type -> common.SetStatusRequest
	1,  // 16: admin.ShopBannerService.PageShopBanner:output_type -> admin.PageShopBannerResponse
	3,  // 17: admin.ShopBannerService.GetShopBanner:output_type -> admin.ShopBannerForm
	10, // 18: admin.ShopBannerService.CreateShopBanner:output_type -> google.protobuf.Empty
	10, // 19: admin.ShopBannerService.UpdateShopBanner:output_type -> google.protobuf.Empty
	10, // 20: admin.ShopBannerService.DeleteShopBanner:output_type -> google.protobuf.Empty
	10, // 21: admin.ShopBannerService.SetShopBannerStatus:output_type -> google.protobuf.Empty
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_admin_shop_banner_proto_init() }
func file_admin_shop_banner_proto_init() {
	if File_admin_shop_banner_proto != nil {
		return
	}
	file_admin_shop_banner_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_shop_banner_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_shop_banner_proto_rawDesc), len(file_admin_shop_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_shop_banner_proto_goTypes,
		DependencyIndexes: file_admin_shop_banner_proto_depIdxs,
		MessageInfos:      file_admin_shop_banner_proto_msgTypes,
	}.Build()
	File_admin_shop_banner_proto = out.File
	file_admin_shop_banner_proto_goTypes = nil
	file_admin_shop_banner_proto_depIdxs = nil
}
