// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: admin/shop_service.proto

package admin

import (
	context "context"
	common "gitee.com/liujit/shop/server/api/common"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShopServiceServiceCreateShopService = "/admin.ShopServiceService/CreateShopService"
const OperationShopServiceServiceDeleteShopService = "/admin.ShopServiceService/DeleteShopService"
const OperationShopServiceServiceGetShopService = "/admin.ShopServiceService/GetShopService"
const OperationShopServiceServicePageShopService = "/admin.ShopServiceService/PageShopService"
const OperationShopServiceServiceSetShopServiceStatus = "/admin.ShopServiceService/SetShopServiceStatus"
const OperationShopServiceServiceUpdateShopService = "/admin.ShopServiceService/UpdateShopService"

type ShopServiceServiceHTTPServer interface {
	// CreateShopService 创建商城服务
	CreateShopService(context.Context, *ShopServiceForm) (*emptypb.Empty, error)
	// DeleteShopService 删除商城服务
	DeleteShopService(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	// GetShopService 查询商城服务
	GetShopService(context.Context, *wrapperspb.Int64Value) (*ShopServiceForm, error)
	// PageShopService 查询商城服务分页列表
	PageShopService(context.Context, *PageShopServiceRequest) (*PageShopServiceResponse, error)
	// SetShopServiceStatus 设置状态
	SetShopServiceStatus(context.Context, *common.SetStatusRequest) (*emptypb.Empty, error)
	// UpdateShopService 更新商城服务
	UpdateShopService(context.Context, *ShopServiceForm) (*emptypb.Empty, error)
}

func RegisterShopServiceServiceHTTPServer(s *http.Server, srv ShopServiceServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/admin/shop/service", _ShopServiceService_PageShopService0_HTTP_Handler(srv))
	r.GET("/api/admin/shop/service/{value}", _ShopServiceService_GetShopService0_HTTP_Handler(srv))
	r.POST("/api/admin/shop/service", _ShopServiceService_CreateShopService0_HTTP_Handler(srv))
	r.PUT("/api/admin/shop/service/{id}", _ShopServiceService_UpdateShopService0_HTTP_Handler(srv))
	r.DELETE("/api/admin/shop/service/{value}", _ShopServiceService_DeleteShopService0_HTTP_Handler(srv))
	r.PUT("/api/admin/shop/service/{id}/status", _ShopServiceService_SetShopServiceStatus0_HTTP_Handler(srv))
}

func _ShopServiceService_PageShopService0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageShopServiceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServicePageShopService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageShopService(ctx, req.(*PageShopServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageShopServiceResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopServiceService_GetShopService0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServiceGetShopService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShopService(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShopServiceForm)
		return ctx.Result(200, reply)
	}
}

func _ShopServiceService_CreateShopService0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShopServiceForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServiceCreateShopService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShopService(ctx, req.(*ShopServiceForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ShopServiceService_UpdateShopService0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShopServiceForm
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServiceUpdateShopService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateShopService(ctx, req.(*ShopServiceForm))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ShopServiceService_DeleteShopService0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.StringValue
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServiceDeleteShopService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteShopService(ctx, req.(*wrapperspb.StringValue))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _ShopServiceService_SetShopServiceStatus0_HTTP_Handler(srv ShopServiceServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in common.SetStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopServiceServiceSetShopServiceStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetShopServiceStatus(ctx, req.(*common.SetStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ShopServiceServiceHTTPClient interface {
	CreateShopService(ctx context.Context, req *ShopServiceForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteShopService(ctx context.Context, req *wrapperspb.StringValue, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetShopService(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *ShopServiceForm, err error)
	PageShopService(ctx context.Context, req *PageShopServiceRequest, opts ...http.CallOption) (rsp *PageShopServiceResponse, err error)
	SetShopServiceStatus(ctx context.Context, req *common.SetStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateShopService(ctx context.Context, req *ShopServiceForm, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ShopServiceServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopServiceServiceHTTPClient(client *http.Client) ShopServiceServiceHTTPClient {
	return &ShopServiceServiceHTTPClientImpl{client}
}

func (c *ShopServiceServiceHTTPClientImpl) CreateShopService(ctx context.Context, in *ShopServiceForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/shop/service"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceServiceCreateShopService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopServiceServiceHTTPClientImpl) DeleteShopService(ctx context.Context, in *wrapperspb.StringValue, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/shop/service/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceServiceDeleteShopService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopServiceServiceHTTPClientImpl) GetShopService(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*ShopServiceForm, error) {
	var out ShopServiceForm
	pattern := "/api/admin/shop/service/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceServiceGetShopService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopServiceServiceHTTPClientImpl) PageShopService(ctx context.Context, in *PageShopServiceRequest, opts ...http.CallOption) (*PageShopServiceResponse, error) {
	var out PageShopServiceResponse
	pattern := "/api/admin/shop/service"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopServiceServicePageShopService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopServiceServiceHTTPClientImpl) SetShopServiceStatus(ctx context.Context, in *common.SetStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/shop/service/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceServiceSetShopServiceStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopServiceServiceHTTPClientImpl) UpdateShopService(ctx context.Context, in *ShopServiceForm, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/admin/shop/service/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationShopServiceServiceUpdateShopService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
