// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               unknown
// source: app/user_collect.proto

/* eslint-disable */
import { type Empty } from "../google/protobuf/empty";
import { type BoolValue, type StringValue } from "../google/protobuf/wrappers";

export interface IsCollectRequest {
  /** 商品ID */
  goodsId: number;
}

export interface PageUserCollectRequest {
  /** 当前页码 */
  pageNum: number;
  /** 每一页的行数 */
  pageSize: number;
}

export interface PageUserCollectResponse {
  /** 数据 */
  list: UserCollect[];
  /** 总数 */
  total: number;
}

/** 用户购物车 */
export interface UserCollectForm {
  /** 商品id */
  goodsId: number;
}

/** 用户收藏 */
export interface UserCollect {
  /** 用户收藏ID */
  id: number;
  /** 商品ID */
  goodsId: number;
  /** 名称 */
  name: string;
  /** 描述 */
  desc: string;
  /** 商品图片 */
  picture: string;
  /** 销量 */
  saleNum: number;
  /** 价格 */
  price: number;
  /** 加入时价格 */
  joinPrice: number;
}

/** App用户收藏管理服务 */
export interface UserCollectService {
  /** 查询用户收藏列表 */
  PageUserCollect(request: PageUserCollectRequest): Promise<PageUserCollectResponse>;
  /** 查询用户是否收藏 */
  GetIsCollect(request: IsCollectRequest): Promise<BoolValue>;
  /** 创建用户收藏 */
  CreateUserCollect(request: UserCollectForm): Promise<Empty>;
  /** 删除用户收藏 */
  DeleteUserCollect(request: StringValue): Promise<Empty>;
}
