// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: config/config.proto

package config

import (
	context "context"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConfigServiceGetConfig = "/config.ConfigService/GetConfig"

type ConfigServiceHTTPServer interface {
	// GetConfig 获取系统配置
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
}

func RegisterConfigServiceHTTPServer(s *http.Server, srv ConfigServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/config", _ConfigService_GetConfig0_HTTP_Handler(srv))
}

func _ConfigService_GetConfig0_HTTP_Handler(srv ConfigServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfigRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConfigServiceGetConfig)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetConfig(ctx, req.(*ConfigRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfigResponse)
		return ctx.Result(200, reply)
	}
}

type ConfigServiceHTTPClient interface {
	GetConfig(ctx context.Context, req *ConfigRequest, opts ...http.CallOption) (rsp *ConfigResponse, err error)
}

type ConfigServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewConfigServiceHTTPClient(client *http.Client) ConfigServiceHTTPClient {
	return &ConfigServiceHTTPClientImpl{client}
}

func (c *ConfigServiceHTTPClientImpl) GetConfig(ctx context.Context, in *ConfigRequest, opts ...http.CallOption) (*ConfigResponse, error) {
	var out ConfigResponse
	pattern := "/api/config"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConfigServiceGetConfig))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
