// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: common/enum.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 状态
type Status int32

const (
	Status_UNKNOWN Status = 0
	Status_ENABLE  Status = 1 // 启用
	Status_DISABLE Status = 2 // 禁用
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ENABLE",
		2: "DISABLE",
	}
	Status_value = map[string]int32{
		"UNKNOWN": 0,
		"ENABLE":  1,
		"DISABLE": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{0}
}

// 系统配置位置
type BaseConfigSite int32

const (
	BaseConfigSite_UNKNOWN_BCS BaseConfigSite = 0
	BaseConfigSite_SYSTEM      BaseConfigSite = 1 // 系统内使用
	BaseConfigSite_ADMIN       BaseConfigSite = 2 // 管理端
	BaseConfigSite_APP         BaseConfigSite = 3 // 移动端
)

// Enum value maps for BaseConfigSite.
var (
	BaseConfigSite_name = map[int32]string{
		0: "UNKNOWN_BCS",
		1: "SYSTEM",
		2: "ADMIN",
		3: "APP",
	}
	BaseConfigSite_value = map[string]int32{
		"UNKNOWN_BCS": 0,
		"SYSTEM":      1,
		"ADMIN":       2,
		"APP":         3,
	}
)

func (x BaseConfigSite) Enum() *BaseConfigSite {
	p := new(BaseConfigSite)
	*p = x
	return p
}

func (x BaseConfigSite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseConfigSite) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[1].Descriptor()
}

func (BaseConfigSite) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[1]
}

func (x BaseConfigSite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseConfigSite.Descriptor instead.
func (BaseConfigSite) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{1}
}

// 系统配置类型
type BaseConfigType int32

const (
	BaseConfigType_UNKNOWN_BCT BaseConfigType = 0
	BaseConfigType_TEXT        BaseConfigType = 1 // 文本
	BaseConfigType_IMAGE       BaseConfigType = 2 // 图片
	BaseConfigType_RICH_TEXT   BaseConfigType = 3 // 富文本
)

// Enum value maps for BaseConfigType.
var (
	BaseConfigType_name = map[int32]string{
		0: "UNKNOWN_BCT",
		1: "TEXT",
		2: "IMAGE",
		3: "RICH_TEXT",
	}
	BaseConfigType_value = map[string]int32{
		"UNKNOWN_BCT": 0,
		"TEXT":        1,
		"IMAGE":       2,
		"RICH_TEXT":   3,
	}
)

func (x BaseConfigType) Enum() *BaseConfigType {
	p := new(BaseConfigType)
	*p = x
	return p
}

func (x BaseConfigType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseConfigType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[2].Descriptor()
}

func (BaseConfigType) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[2]
}

func (x BaseConfigType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseConfigType.Descriptor instead.
func (BaseConfigType) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{2}
}

// 定时任务日志状态
type BaseJobLogStatus int32

const (
	BaseJobLogStatus_UNKNOWN_BJLS BaseJobLogStatus = 0
	BaseJobLogStatus_SUCCESS      BaseJobLogStatus = 1 // 成功
	BaseJobLogStatus_FAIL         BaseJobLogStatus = 2 // 失败
)

// Enum value maps for BaseJobLogStatus.
var (
	BaseJobLogStatus_name = map[int32]string{
		0: "UNKNOWN_BJLS",
		1: "SUCCESS",
		2: "FAIL",
	}
	BaseJobLogStatus_value = map[string]int32{
		"UNKNOWN_BJLS": 0,
		"SUCCESS":      1,
		"FAIL":         2,
	}
)

func (x BaseJobLogStatus) Enum() *BaseJobLogStatus {
	p := new(BaseJobLogStatus)
	*p = x
	return p
}

func (x BaseJobLogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseJobLogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[3].Descriptor()
}

func (BaseJobLogStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[3]
}

func (x BaseJobLogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseJobLogStatus.Descriptor instead.
func (BaseJobLogStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{3}
}

// 菜单类型
type BaseMenuType int32

const (
	BaseMenuType_UNKNOWN_MT BaseMenuType = 0
	BaseMenuType_FOLDER     BaseMenuType = 1 // 目录
	BaseMenuType_MENU       BaseMenuType = 2 // 菜单
	BaseMenuType_BUTTON     BaseMenuType = 3 // 按钮
	BaseMenuType_EXT_LINK   BaseMenuType = 4 // 外部链接
)

// Enum value maps for BaseMenuType.
var (
	BaseMenuType_name = map[int32]string{
		0: "UNKNOWN_MT",
		1: "FOLDER",
		2: "MENU",
		3: "BUTTON",
		4: "EXT_LINK",
	}
	BaseMenuType_value = map[string]int32{
		"UNKNOWN_MT": 0,
		"FOLDER":     1,
		"MENU":       2,
		"BUTTON":     3,
		"EXT_LINK":   4,
	}
)

func (x BaseMenuType) Enum() *BaseMenuType {
	p := new(BaseMenuType)
	*p = x
	return p
}

func (x BaseMenuType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseMenuType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[4].Descriptor()
}

func (BaseMenuType) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[4]
}

func (x BaseMenuType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseMenuType.Descriptor instead.
func (BaseMenuType) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{4}
}

// 角色数据范围
type BaseRoleDataScope int32

const (
	BaseRoleDataScope_UNKNOWN_RDS       BaseRoleDataScope = 0
	BaseRoleDataScope_ALL               BaseRoleDataScope = 1 // 全部数据
	BaseRoleDataScope_DEPT_AND_CHILDREN BaseRoleDataScope = 2 // 部门及子部门数据
	BaseRoleDataScope_SELF_DEPT         BaseRoleDataScope = 3 // 本部门数据
	BaseRoleDataScope_SELF_USER         BaseRoleDataScope = 4 // 本人数据
)

// Enum value maps for BaseRoleDataScope.
var (
	BaseRoleDataScope_name = map[int32]string{
		0: "UNKNOWN_RDS",
		1: "ALL",
		2: "DEPT_AND_CHILDREN",
		3: "SELF_DEPT",
		4: "SELF_USER",
	}
	BaseRoleDataScope_value = map[string]int32{
		"UNKNOWN_RDS":       0,
		"ALL":               1,
		"DEPT_AND_CHILDREN": 2,
		"SELF_DEPT":         3,
		"SELF_USER":         4,
	}
)

func (x BaseRoleDataScope) Enum() *BaseRoleDataScope {
	p := new(BaseRoleDataScope)
	*p = x
	return p
}

func (x BaseRoleDataScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseRoleDataScope) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[5].Descriptor()
}

func (BaseRoleDataScope) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[5]
}

func (x BaseRoleDataScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseRoleDataScope.Descriptor instead.
func (BaseRoleDataScope) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{5}
}

// 用户性别
type BaseUserGender int32

const (
	BaseUserGender_UNKNOWN_BUG BaseUserGender = 0
	BaseUserGender_SECRET      BaseUserGender = 1 // 保密
	BaseUserGender_BOY         BaseUserGender = 2 // 男
	BaseUserGender_GIRL        BaseUserGender = 3 // 禁用
)

// Enum value maps for BaseUserGender.
var (
	BaseUserGender_name = map[int32]string{
		0: "UNKNOWN_BUG",
		1: "SECRET",
		2: "BOY",
		3: "GIRL",
	}
	BaseUserGender_value = map[string]int32{
		"UNKNOWN_BUG": 0,
		"SECRET":      1,
		"BOY":         2,
		"GIRL":        3,
	}
)

func (x BaseUserGender) Enum() *BaseUserGender {
	p := new(BaseUserGender)
	*p = x
	return p
}

func (x BaseUserGender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseUserGender) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[6].Descriptor()
}

func (BaseUserGender) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[6]
}

func (x BaseUserGender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseUserGender.Descriptor instead.
func (BaseUserGender) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{6}
}

// 用户门店审核状态
type UserStoreStatus int32

const (
	UserStoreStatus_UNKNOWN_USS    UserStoreStatus = 0
	UserStoreStatus_PENDING_REVIEW UserStoreStatus = 1 // 待审核
	UserStoreStatus_FAILED_REVIEW  UserStoreStatus = 2 // 审核失败
	UserStoreStatus_APPROVED       UserStoreStatus = 3 // 审核通过
)

// Enum value maps for UserStoreStatus.
var (
	UserStoreStatus_name = map[int32]string{
		0: "UNKNOWN_USS",
		1: "PENDING_REVIEW",
		2: "FAILED_REVIEW",
		3: "APPROVED",
	}
	UserStoreStatus_value = map[string]int32{
		"UNKNOWN_USS":    0,
		"PENDING_REVIEW": 1,
		"FAILED_REVIEW":  2,
		"APPROVED":       3,
	}
)

func (x UserStoreStatus) Enum() *UserStoreStatus {
	p := new(UserStoreStatus)
	*p = x
	return p
}

func (x UserStoreStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStoreStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[7].Descriptor()
}

func (UserStoreStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[7]
}

func (x UserStoreStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStoreStatus.Descriptor instead.
func (UserStoreStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{7}
}

// 商品状态
type GoodsStatus int32

const (
	GoodsStatus_UNKNOWN_GS GoodsStatus = 0
	GoodsStatus_PUT_ON     GoodsStatus = 1 // 已上架
	GoodsStatus_PULL_OFF   GoodsStatus = 2 // 已下架
)

// Enum value maps for GoodsStatus.
var (
	GoodsStatus_name = map[int32]string{
		0: "UNKNOWN_GS",
		1: "PUT_ON",
		2: "PULL_OFF",
	}
	GoodsStatus_value = map[string]int32{
		"UNKNOWN_GS": 0,
		"PUT_ON":     1,
		"PULL_OFF":   2,
	}
)

func (x GoodsStatus) Enum() *GoodsStatus {
	p := new(GoodsStatus)
	*p = x
	return p
}

func (x GoodsStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GoodsStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[8].Descriptor()
}

func (GoodsStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[8]
}

func (x GoodsStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GoodsStatus.Descriptor instead.
func (GoodsStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{8}
}

// 订单状态
type OrderStatus int32

const (
	OrderStatus_UNKNOWN_OS OrderStatus = 0
	OrderStatus_CREATED    OrderStatus = 1  // 待付款
	OrderStatus_PAID       OrderStatus = 2  // 待发货
	OrderStatus_SHIPPED    OrderStatus = 3  // 待收货
	OrderStatus_RECEIVED   OrderStatus = 4  // 已完成
	OrderStatus_REFUNDING  OrderStatus = 97 // 已退款
	OrderStatus_CANCELED   OrderStatus = 98 // 已取消
	OrderStatus_DELETED    OrderStatus = 99 // 已删除
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0:  "UNKNOWN_OS",
		1:  "CREATED",
		2:  "PAID",
		3:  "SHIPPED",
		4:  "RECEIVED",
		97: "REFUNDING",
		98: "CANCELED",
		99: "DELETED",
	}
	OrderStatus_value = map[string]int32{
		"UNKNOWN_OS": 0,
		"CREATED":    1,
		"PAID":       2,
		"SHIPPED":    3,
		"RECEIVED":   4,
		"REFUNDING":  97,
		"CANCELED":   98,
		"DELETED":    99,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[9].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[9]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{9}
}

// 订单支付方式
type OrderPayType int32

const (
	OrderPayType_UNKNOWN_OPT      OrderPayType = 0
	OrderPayType_ONLINE_PAY       OrderPayType = 1 // 在线支付
	OrderPayType_CASH_ON_DELIVERY OrderPayType = 2 // 货到付款
)

// Enum value maps for OrderPayType.
var (
	OrderPayType_name = map[int32]string{
		0: "UNKNOWN_OPT",
		1: "ONLINE_PAY",
		2: "CASH_ON_DELIVERY",
	}
	OrderPayType_value = map[string]int32{
		"UNKNOWN_OPT":      0,
		"ONLINE_PAY":       1,
		"CASH_ON_DELIVERY": 2,
	}
)

func (x OrderPayType) Enum() *OrderPayType {
	p := new(OrderPayType)
	*p = x
	return p
}

func (x OrderPayType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPayType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[10].Descriptor()
}

func (OrderPayType) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[10]
}

func (x OrderPayType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPayType.Descriptor instead.
func (OrderPayType) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{10}
}

// 订单支付渠道
type OrderPayChannel int32

const (
	OrderPayChannel_UNKNOWN_OPC OrderPayChannel = 0
	OrderPayChannel_WX_PAY      OrderPayChannel = 1 // 微信支付
	OrderPayChannel_UNION_PAY   OrderPayChannel = 2 // 银联支付
)

// Enum value maps for OrderPayChannel.
var (
	OrderPayChannel_name = map[int32]string{
		0: "UNKNOWN_OPC",
		1: "WX_PAY",
		2: "UNION_PAY",
	}
	OrderPayChannel_value = map[string]int32{
		"UNKNOWN_OPC": 0,
		"WX_PAY":      1,
		"UNION_PAY":   2,
	}
)

func (x OrderPayChannel) Enum() *OrderPayChannel {
	p := new(OrderPayChannel)
	*p = x
	return p
}

func (x OrderPayChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderPayChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[11].Descriptor()
}

func (OrderPayChannel) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[11]
}

func (x OrderPayChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderPayChannel.Descriptor instead.
func (OrderPayChannel) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{11}
}

// 订单配送时间
type OrderDeliveryTime int32

const (
	OrderDeliveryTime_UNKNOWN_ODT OrderDeliveryTime = 0
	OrderDeliveryTime_ALL_TIME    OrderDeliveryTime = 1 // 时间不限 (周一至周日)
	OrderDeliveryTime_WEEKDAY     OrderDeliveryTime = 2 // 工作日送 (周一至周五)
	OrderDeliveryTime_WEEKEND     OrderDeliveryTime = 3 // 周末配送 (周六至周日)
)

// Enum value maps for OrderDeliveryTime.
var (
	OrderDeliveryTime_name = map[int32]string{
		0: "UNKNOWN_ODT",
		1: "ALL_TIME",
		2: "WEEKDAY",
		3: "WEEKEND",
	}
	OrderDeliveryTime_value = map[string]int32{
		"UNKNOWN_ODT": 0,
		"ALL_TIME":    1,
		"WEEKDAY":     2,
		"WEEKEND":     3,
	}
)

func (x OrderDeliveryTime) Enum() *OrderDeliveryTime {
	p := new(OrderDeliveryTime)
	*p = x
	return p
}

func (x OrderDeliveryTime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderDeliveryTime) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[12].Descriptor()
}

func (OrderDeliveryTime) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[12]
}

func (x OrderDeliveryTime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderDeliveryTime.Descriptor instead.
func (OrderDeliveryTime) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{12}
}

// 订单取消原因
type OrderCancelReason int32

const (
	OrderCancelReason_UNKNOWN_OCR           OrderCancelReason = 0
	OrderCancelReason_CANCEL_GOODS_NO_STOCK OrderCancelReason = 1 // 商品无货
	OrderCancelReason_CANCEL_SELF           OrderCancelReason = 2 // 不想要了
	OrderCancelReason_CANCEL_GOODS_ERROR    OrderCancelReason = 3 // 商品信息填错了
	OrderCancelReason_CANCEL_ADDRESS_ERROR  OrderCancelReason = 4 // 地址信息填写错误
	OrderCancelReason_CANCEL_GOODS_DISCOUNT OrderCancelReason = 5 // 商品降价
	OrderCancelReason_CANCEL_OTHER          OrderCancelReason = 6 // 其它
)

// Enum value maps for OrderCancelReason.
var (
	OrderCancelReason_name = map[int32]string{
		0: "UNKNOWN_OCR",
		1: "CANCEL_GOODS_NO_STOCK",
		2: "CANCEL_SELF",
		3: "CANCEL_GOODS_ERROR",
		4: "CANCEL_ADDRESS_ERROR",
		5: "CANCEL_GOODS_DISCOUNT",
		6: "CANCEL_OTHER",
	}
	OrderCancelReason_value = map[string]int32{
		"UNKNOWN_OCR":           0,
		"CANCEL_GOODS_NO_STOCK": 1,
		"CANCEL_SELF":           2,
		"CANCEL_GOODS_ERROR":    3,
		"CANCEL_ADDRESS_ERROR":  4,
		"CANCEL_GOODS_DISCOUNT": 5,
		"CANCEL_OTHER":          6,
	}
)

func (x OrderCancelReason) Enum() *OrderCancelReason {
	p := new(OrderCancelReason)
	*p = x
	return p
}

func (x OrderCancelReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderCancelReason) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[13].Descriptor()
}

func (OrderCancelReason) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[13]
}

func (x OrderCancelReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderCancelReason.Descriptor instead.
func (OrderCancelReason) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{13}
}

// 订单对帐状态
type OrderBillStatus int32

const (
	OrderBillStatus_UNKNOWN_OBS   OrderBillStatus = 0
	OrderBillStatus_NO_CHECK      OrderBillStatus = 1 // 未对账
	OrderBillStatus_CHECK_SUCCESS OrderBillStatus = 2 // 对账成功
	OrderBillStatus_CHECK_FAIL    OrderBillStatus = 3 // 对账失败
)

// Enum value maps for OrderBillStatus.
var (
	OrderBillStatus_name = map[int32]string{
		0: "UNKNOWN_OBS",
		1: "NO_CHECK",
		2: "CHECK_SUCCESS",
		3: "CHECK_FAIL",
	}
	OrderBillStatus_value = map[string]int32{
		"UNKNOWN_OBS":   0,
		"NO_CHECK":      1,
		"CHECK_SUCCESS": 2,
		"CHECK_FAIL":    3,
	}
)

func (x OrderBillStatus) Enum() *OrderBillStatus {
	p := new(OrderBillStatus)
	*p = x
	return p
}

func (x OrderBillStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBillStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[14].Descriptor()
}

func (OrderBillStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[14]
}

func (x OrderBillStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderBillStatus.Descriptor instead.
func (OrderBillStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{14}
}

// 订单退款原因
type OrderRefundReason int32

const (
	OrderRefundReason_UNKNOWN_ORR           OrderRefundReason = 0
	OrderRefundReason_REFUND_GOODS_NO_STOCK OrderRefundReason = 1 // 商品无货
	OrderRefundReason_REFUND_SELF           OrderRefundReason = 2 // 不想要了
	OrderRefundReason_REFUND_GOODS_ERROR    OrderRefundReason = 3 // 商品信息填错了
	OrderRefundReason_REFUND_ADDRESS_ERROR  OrderRefundReason = 4 // 地址信息填写错误
	OrderRefundReason_REFUND_GOODS_DISCOUNT OrderRefundReason = 5 // 商品降价
	OrderRefundReason_REFUND_OTHER          OrderRefundReason = 6 // 其它
)

// Enum value maps for OrderRefundReason.
var (
	OrderRefundReason_name = map[int32]string{
		0: "UNKNOWN_ORR",
		1: "REFUND_GOODS_NO_STOCK",
		2: "REFUND_SELF",
		3: "REFUND_GOODS_ERROR",
		4: "REFUND_ADDRESS_ERROR",
		5: "REFUND_GOODS_DISCOUNT",
		6: "REFUND_OTHER",
	}
	OrderRefundReason_value = map[string]int32{
		"UNKNOWN_ORR":           0,
		"REFUND_GOODS_NO_STOCK": 1,
		"REFUND_SELF":           2,
		"REFUND_GOODS_ERROR":    3,
		"REFUND_ADDRESS_ERROR":  4,
		"REFUND_GOODS_DISCOUNT": 5,
		"REFUND_OTHER":          6,
	}
)

func (x OrderRefundReason) Enum() *OrderRefundReason {
	p := new(OrderRefundReason)
	*p = x
	return p
}

func (x OrderRefundReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderRefundReason) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[15].Descriptor()
}

func (OrderRefundReason) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[15]
}

func (x OrderRefundReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderRefundReason.Descriptor instead.
func (OrderRefundReason) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{15}
}

// 轮播图位置
type ShopBannerSite int32

const (
	ShopBannerSite_UNKNOWN_SBS ShopBannerSite = 0
	ShopBannerSite_INDEX       ShopBannerSite = 1 // 首页
	ShopBannerSite_CATEGORY    ShopBannerSite = 2 // 分类页
)

// Enum value maps for ShopBannerSite.
var (
	ShopBannerSite_name = map[int32]string{
		0: "UNKNOWN_SBS",
		1: "INDEX",
		2: "CATEGORY",
	}
	ShopBannerSite_value = map[string]int32{
		"UNKNOWN_SBS": 0,
		"INDEX":       1,
		"CATEGORY":    2,
	}
)

func (x ShopBannerSite) Enum() *ShopBannerSite {
	p := new(ShopBannerSite)
	*p = x
	return p
}

func (x ShopBannerSite) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopBannerSite) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[16].Descriptor()
}

func (ShopBannerSite) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[16]
}

func (x ShopBannerSite) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopBannerSite.Descriptor instead.
func (ShopBannerSite) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{16}
}

// 轮播图类型
type ShopBannerType int32

const (
	ShopBannerType_UNKNOWN_SBT     ShopBannerType = 0
	ShopBannerType_GOODS_DETAIL    ShopBannerType = 1 // 商品详情
	ShopBannerType_CATEGORY_DETAIL ShopBannerType = 2 // 分类详情
	ShopBannerType_WEB_VIEW        ShopBannerType = 3 // H5链接
	ShopBannerType_MINI            ShopBannerType = 4 // 其他小程序
)

// Enum value maps for ShopBannerType.
var (
	ShopBannerType_name = map[int32]string{
		0: "UNKNOWN_SBT",
		1: "GOODS_DETAIL",
		2: "CATEGORY_DETAIL",
		3: "WEB_VIEW",
		4: "MINI",
	}
	ShopBannerType_value = map[string]int32{
		"UNKNOWN_SBT":     0,
		"GOODS_DETAIL":    1,
		"CATEGORY_DETAIL": 2,
		"WEB_VIEW":        3,
		"MINI":            4,
	}
)

func (x ShopBannerType) Enum() *ShopBannerType {
	p := new(ShopBannerType)
	*p = x
	return p
}

func (x ShopBannerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopBannerType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[17].Descriptor()
}

func (ShopBannerType) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[17]
}

func (x ShopBannerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopBannerType.Descriptor instead.
func (ShopBannerType) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{17}
}

// 支付对账单状态
type PayBillStatus int32

const (
	PayBillStatus_UNKNOWN_PBS PayBillStatus = 0
	PayBillStatus_NO_COMPARE  PayBillStatus = 1 // 未比对
	PayBillStatus_NO_ERROR    PayBillStatus = 2 // 无误差
	PayBillStatus_HAS_ERROR   PayBillStatus = 3 // 有误差
)

// Enum value maps for PayBillStatus.
var (
	PayBillStatus_name = map[int32]string{
		0: "UNKNOWN_PBS",
		1: "NO_COMPARE",
		2: "NO_ERROR",
		3: "HAS_ERROR",
	}
	PayBillStatus_value = map[string]int32{
		"UNKNOWN_PBS": 0,
		"NO_COMPARE":  1,
		"NO_ERROR":    2,
		"HAS_ERROR":   3,
	}
)

func (x PayBillStatus) Enum() *PayBillStatus {
	p := new(PayBillStatus)
	*p = x
	return p
}

func (x PayBillStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayBillStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_enum_proto_enumTypes[18].Descriptor()
}

func (PayBillStatus) Type() protoreflect.EnumType {
	return &file_common_enum_proto_enumTypes[18]
}

func (x PayBillStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayBillStatus.Descriptor instead.
func (PayBillStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_enum_proto_rawDescGZIP(), []int{18}
}

var File_common_enum_proto protoreflect.FileDescriptor

const file_common_enum_proto_rawDesc = "" +
	"\n" +
	"\x11common/enum.proto\x12\x06common*.\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ENABLE\x10\x01\x12\v\n" +
	"\aDISABLE\x10\x02*A\n" +
	"\x0eBaseConfigSite\x12\x0f\n" +
	"\vUNKNOWN_BCS\x10\x00\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x01\x12\t\n" +
	"\x05ADMIN\x10\x02\x12\a\n" +
	"\x03APP\x10\x03*E\n" +
	"\x0eBaseConfigType\x12\x0f\n" +
	"\vUNKNOWN_BCT\x10\x00\x12\b\n" +
	"\x04TEXT\x10\x01\x12\t\n" +
	"\x05IMAGE\x10\x02\x12\r\n" +
	"\tRICH_TEXT\x10\x03*;\n" +
	"\x10BaseJobLogStatus\x12\x10\n" +
	"\fUNKNOWN_BJLS\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\b\n" +
	"\x04FAIL\x10\x02*N\n" +
	"\fBaseMenuType\x12\x0e\n" +
	"\n" +
	"UNKNOWN_MT\x10\x00\x12\n" +
	"\n" +
	"\x06FOLDER\x10\x01\x12\b\n" +
	"\x04MENU\x10\x02\x12\n" +
	"\n" +
	"\x06BUTTON\x10\x03\x12\f\n" +
	"\bEXT_LINK\x10\x04*b\n" +
	"\x11BaseRoleDataScope\x12\x0f\n" +
	"\vUNKNOWN_RDS\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\x15\n" +
	"\x11DEPT_AND_CHILDREN\x10\x02\x12\r\n" +
	"\tSELF_DEPT\x10\x03\x12\r\n" +
	"\tSELF_USER\x10\x04*@\n" +
	"\x0eBaseUserGender\x12\x0f\n" +
	"\vUNKNOWN_BUG\x10\x00\x12\n" +
	"\n" +
	"\x06SECRET\x10\x01\x12\a\n" +
	"\x03BOY\x10\x02\x12\b\n" +
	"\x04GIRL\x10\x03*W\n" +
	"\x0fUserStoreStatus\x12\x0f\n" +
	"\vUNKNOWN_USS\x10\x00\x12\x12\n" +
	"\x0ePENDING_REVIEW\x10\x01\x12\x11\n" +
	"\rFAILED_REVIEW\x10\x02\x12\f\n" +
	"\bAPPROVED\x10\x03*7\n" +
	"\vGoodsStatus\x12\x0e\n" +
	"\n" +
	"UNKNOWN_GS\x10\x00\x12\n" +
	"\n" +
	"\x06PUT_ON\x10\x01\x12\f\n" +
	"\bPULL_OFF\x10\x02*y\n" +
	"\vOrderStatus\x12\x0e\n" +
	"\n" +
	"UNKNOWN_OS\x10\x00\x12\v\n" +
	"\aCREATED\x10\x01\x12\b\n" +
	"\x04PAID\x10\x02\x12\v\n" +
	"\aSHIPPED\x10\x03\x12\f\n" +
	"\bRECEIVED\x10\x04\x12\r\n" +
	"\tREFUNDING\x10a\x12\f\n" +
	"\bCANCELED\x10b\x12\v\n" +
	"\aDELETED\x10c*E\n" +
	"\fOrderPayType\x12\x0f\n" +
	"\vUNKNOWN_OPT\x10\x00\x12\x0e\n" +
	"\n" +
	"ONLINE_PAY\x10\x01\x12\x14\n" +
	"\x10CASH_ON_DELIVERY\x10\x02*=\n" +
	"\x0fOrderPayChannel\x12\x0f\n" +
	"\vUNKNOWN_OPC\x10\x00\x12\n" +
	"\n" +
	"\x06WX_PAY\x10\x01\x12\r\n" +
	"\tUNION_PAY\x10\x02*L\n" +
	"\x11OrderDeliveryTime\x12\x0f\n" +
	"\vUNKNOWN_ODT\x10\x00\x12\f\n" +
	"\bALL_TIME\x10\x01\x12\v\n" +
	"\aWEEKDAY\x10\x02\x12\v\n" +
	"\aWEEKEND\x10\x03*\xaf\x01\n" +
	"\x11OrderCancelReason\x12\x0f\n" +
	"\vUNKNOWN_OCR\x10\x00\x12\x19\n" +
	"\x15CANCEL_GOODS_NO_STOCK\x10\x01\x12\x0f\n" +
	"\vCANCEL_SELF\x10\x02\x12\x16\n" +
	"\x12CANCEL_GOODS_ERROR\x10\x03\x12\x18\n" +
	"\x14CANCEL_ADDRESS_ERROR\x10\x04\x12\x19\n" +
	"\x15CANCEL_GOODS_DISCOUNT\x10\x05\x12\x10\n" +
	"\fCANCEL_OTHER\x10\x06*S\n" +
	"\x0fOrderBillStatus\x12\x0f\n" +
	"\vUNKNOWN_OBS\x10\x00\x12\f\n" +
	"\bNO_CHECK\x10\x01\x12\x11\n" +
	"\rCHECK_SUCCESS\x10\x02\x12\x0e\n" +
	"\n" +
	"CHECK_FAIL\x10\x03*\xaf\x01\n" +
	"\x11OrderRefundReason\x12\x0f\n" +
	"\vUNKNOWN_ORR\x10\x00\x12\x19\n" +
	"\x15REFUND_GOODS_NO_STOCK\x10\x01\x12\x0f\n" +
	"\vREFUND_SELF\x10\x02\x12\x16\n" +
	"\x12REFUND_GOODS_ERROR\x10\x03\x12\x18\n" +
	"\x14REFUND_ADDRESS_ERROR\x10\x04\x12\x19\n" +
	"\x15REFUND_GOODS_DISCOUNT\x10\x05\x12\x10\n" +
	"\fREFUND_OTHER\x10\x06*:\n" +
	"\x0eShopBannerSite\x12\x0f\n" +
	"\vUNKNOWN_SBS\x10\x00\x12\t\n" +
	"\x05INDEX\x10\x01\x12\f\n" +
	"\bCATEGORY\x10\x02*`\n" +
	"\x0eShopBannerType\x12\x0f\n" +
	"\vUNKNOWN_SBT\x10\x00\x12\x10\n" +
	"\fGOODS_DETAIL\x10\x01\x12\x13\n" +
	"\x0fCATEGORY_DETAIL\x10\x02\x12\f\n" +
	"\bWEB_VIEW\x10\x03\x12\b\n" +
	"\x04MINI\x10\x04*M\n" +
	"\rPayBillStatus\x12\x0f\n" +
	"\vUNKNOWN_PBS\x10\x00\x12\x0e\n" +
	"\n" +
	"NO_COMPARE\x10\x01\x12\f\n" +
	"\bNO_ERROR\x10\x02\x12\r\n" +
	"\tHAS_ERROR\x10\x03B\x7f\n" +
	"\n" +
	"com.commonB\tEnumProtoP\x01Z.gitee.com/liujit/shop/server/api/common;common\xa2\x02\x03CXX\xaa\x02\x06Common\xca\x02\x06Common\xe2\x02\x12Common\\GPBMetadata\xea\x02\x06Commonb\x06proto3"

var (
	file_common_enum_proto_rawDescOnce sync.Once
	file_common_enum_proto_rawDescData []byte
)

func file_common_enum_proto_rawDescGZIP() []byte {
	file_common_enum_proto_rawDescOnce.Do(func() {
		file_common_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_enum_proto_rawDesc), len(file_common_enum_proto_rawDesc)))
	})
	return file_common_enum_proto_rawDescData
}

var file_common_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 19)
var file_common_enum_proto_goTypes = []any{
	(Status)(0),            // 0: common.Status
	(BaseConfigSite)(0),    // 1: common.BaseConfigSite
	(BaseConfigType)(0),    // 2: common.BaseConfigType
	(BaseJobLogStatus)(0),  // 3: common.BaseJobLogStatus
	(BaseMenuType)(0),      // 4: common.BaseMenuType
	(BaseRoleDataScope)(0), // 5: common.BaseRoleDataScope
	(BaseUserGender)(0),    // 6: common.BaseUserGender
	(UserStoreStatus)(0),   // 7: common.UserStoreStatus
	(GoodsStatus)(0),       // 8: common.GoodsStatus
	(OrderStatus)(0),       // 9: common.OrderStatus
	(OrderPayType)(0),      // 10: common.OrderPayType
	(OrderPayChannel)(0),   // 11: common.OrderPayChannel
	(OrderDeliveryTime)(0), // 12: common.OrderDeliveryTime
	(OrderCancelReason)(0), // 13: common.OrderCancelReason
	(OrderBillStatus)(0),   // 14: common.OrderBillStatus
	(OrderRefundReason)(0), // 15: common.OrderRefundReason
	(ShopBannerSite)(0),    // 16: common.ShopBannerSite
	(ShopBannerType)(0),    // 17: common.ShopBannerType
	(PayBillStatus)(0),     // 18: common.PayBillStatus
}
var file_common_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_enum_proto_init() }
func file_common_enum_proto_init() {
	if File_common_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_enum_proto_rawDesc), len(file_common_enum_proto_rawDesc)),
			NumEnums:      19,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_enum_proto_goTypes,
		DependencyIndexes: file_common_enum_proto_depIdxs,
		EnumInfos:         file_common_enum_proto_enumTypes,
	}.Build()
	File_common_enum_proto = out.File
	file_common_enum_proto_goTypes = nil
	file_common_enum_proto_depIdxs = nil
}
