// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: app/auth.proto

package app

import (
	"context"
	"errors"
	"fmt"
	"gitee.com/liujit/shop/server/api/app"
	"gitee.com/liujit/shop/server/api/common"
	"gitee.com/liujit/shop/server/api/login"
	_const "gitee.com/liujit/shop/server/lib/const"
	"gitee.com/liujit/shop/server/lib/data"
	"gitee.com/liujit/shop/server/lib/data/models"
	"gitee.com/liujit/shop/server/lib/utils/captcha"
	"gitee.com/liujit/shop/server/lib/utils/crypto"
	"gitee.com/liujit/shop/server/lib/utils/str"
	"gitee.com/liujit/shop/server/pkg/config"
	"gitee.com/liujit/shop/server/pkg/core"
	"gitee.com/liujit/shop/server/pkg/service/app/biz"
	"gitee.com/liujit/shop/server/pkg/service/app/util"
	"github.com/google/uuid"
	"go.newcapec.cn/ncttools/nmskit-auth/authn/engine"
	nmskitAuthData "go.newcapec.cn/ncttools/nmskit-auth/data"
	authMiddleware "go.newcapec.cn/ncttools/nmskit-auth/middleware"
	"go.newcapec.cn/ncttools/nmskit/log"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
	"gorm.io/gorm"
	"strings"
	"time"
)

const _ = grpc.SupportPackageIsVersion7

// AuthServiceImpl is the server API for AuthService service implement.
type AuthServiceImpl struct {
	app.UnimplementedAuthServiceServer
	*core.ShopCore
	baseUserCase *biz.BaseUserCase
	baseRoleCase *biz.BaseRoleCase
	wxMiniApp    *config.WxMiniApp
}

// NewAuthServiceImpl create a service implement.
// App用户登录认证服务
func NewAuthServiceImpl(
	sc *core.ShopCore,
	baseUserCase *biz.BaseUserCase,
	baseRoleCase *biz.BaseRoleCase,
	wxMiniApp *config.WxMiniApp,
) *AuthServiceImpl {
	var ss = AuthServiceImpl{
		ShopCore:     sc,
		baseUserCase: baseUserCase,
		baseRoleCase: baseRoleCase,
		wxMiniApp:    wxMiniApp,
	}
	log.Debug("NewAuthServiceImpl.")
	return &ss
}

// Login
// 登录
func (s *AuthServiceImpl) Login(ctx context.Context, req *login.LoginRequest) (*login.LoginResponse, error) {
	if req.GetCaptchaId() == "" || req.GetCaptchaCode() == "" {
		return nil, errors.New("验证码不存在")
	}
	if !captcha.Verify(req.GetCaptchaId(), req.GetCaptchaCode(), true) {
		return nil, errors.New("验证码错误")
	}

	user, err := s.baseUserCase.GetFromPhone(ctx, req.GetUserName())
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	bMatched := crypto.CheckPasswordHash(req.GetPassword(), user.Password)
	if !bMatched {
		return nil, errors.New("密码错误")
	}

	return s.login(ctx, user)
}

func (s *AuthServiceImpl) WxLogin(ctx context.Context, req *app.WxLoginRequest) (*login.LoginResponse, error) {
	sessionKey, err := util.GetSessionKey(s.wxMiniApp.GetAppid(), s.wxMiniApp.GetSecret(), req.GetCode())
	if err != nil {
		return nil, errors.New("登录失败，code错误")
	}
	if sessionKey.ErrCode != 0 {
		return nil, fmt.Errorf("【%d】%s", sessionKey.ErrCode, sessionKey.ErrMsg)
	}
	if sessionKey.Openid == "" {
		return nil, errors.New("登录失败，Openid错误")
	}
	var user *models.BaseUser
	user, err = s.baseUserCase.GetFromOpenid(ctx, sessionKey.Openid)
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			// 自动注册
			uuidV4 := uuid.New()
			user = &models.BaseUser{
				Openid:   sessionKey.Openid,
				UserName: strings.ReplaceAll(uuidV4.String(), "-", ""),
				RoleID:   4,
				DeptID:   5,
				Phone:    "",
				Password: "",
				Gender:   3,
				Avatar:   "",
				Status:   int32(common.Status_ENABLE),
				Remark:   "自动注册用户",
			}
			err = s.baseUserCase.Create(ctx, user)
			if err != nil {
				return nil, errors.New("用户不存在")
			}
		} else {
			return nil, errors.New("用户不存在")
		}
	}
	return s.login(ctx, user)
}

// GetUserInfo
// 获取已经登录的用户的数据
func (s *AuthServiceImpl) GetUserInfo(ctx context.Context, req *emptypb.Empty) (*app.UserInfo, error) {
	authInfo, err := authMiddleware.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var user *models.BaseUser
	user, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		return nil, errors.New("用户不存在")
	}
	if user.Status != int32(common.Status_ENABLE) {
		return nil, errors.New("用户状态错误")
	}
	return &app.UserInfo{
		UserName: user.UserName,
		NickName: user.NickName,
		Gender:   user.Gender,
		Phone:    str.DesensitizePhone(user.Phone),
		Avatar:   user.Avatar,
	}, nil
}

// UpdateUserInfo
// 修改个人中心用户信息
func (s *AuthServiceImpl) UpdateUserInfo(ctx context.Context, req *app.UpdateUserInfoRequest) (*emptypb.Empty, error) {
	authInfo, err := authMiddleware.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var oldBaseUser *models.BaseUser
	oldBaseUser, err = s.baseUserCase.GetFromID(ctx, authInfo.UserId)
	if err != nil {
		log.Errorf("修改个人中心用户信息[%s]", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}
	baseUser := &models.BaseUser{
		ID:       authInfo.UserId,
		NickName: req.GetNickName(),
		Gender:   req.GetGender(),
		Avatar:   req.GetAvatar(),
	}
	err = s.baseUserCase.UpdateByID(ctx, baseUser)
	if err != nil {
		log.Errorf("修改个人中心用户信息[%s]", err.Error())
		return nil, errors.New("修改个人中心用户信息失败")
	}
	// 删除图片
	s.FileCase.DeleteFile(oldBaseUser.Avatar, baseUser.Avatar)
	return &emptypb.Empty{}, nil
}

// PhoneAuth
// 手机号授权
func (s *AuthServiceImpl) PhoneAuth(ctx context.Context, req *app.PhoneAuthRequest) (*app.PhoneAuthResponse, error) {
	authInfo, err := authMiddleware.FromContext(ctx)
	if err != nil {
		log.Errorf("用户认证失败[%s]", err.Error())
		return nil, common.ErrorAccessForbidden("用户认证失败")
	}

	var accessToken string
	accessToken, err = s.Cache.Get(_const.CacheKeyWxAccessToken)
	if err != nil {
		var token *util.WxAccessToken
		token, err = util.GetAccessToken(s.wxMiniApp.GetAppid(), s.wxMiniApp.GetSecret())
		if err != nil {
			return nil, fmt.Errorf("授权失败:%s", err.Error())
		}
		if token.ErrCode != 0 {
			return nil, fmt.Errorf("授权失败:%s", token.ErrMsg)
		}
		accessToken = token.AccessToken
		err = s.Cache.Set(_const.CacheKeyWxAccessToken, accessToken, time.Duration(token.ExpiresIn-300))
		if err != nil {
			log.Errorf("cache set accessToken err:%s", err.Error())
		}
	}

	var phone *util.PhoneNumber
	phone, err = util.GetPhoneNumber(accessToken, req.GetCode())
	if err != nil {
		return nil, fmt.Errorf("授权失败:%s", err.Error())
	}
	if phone.ErrCode != 0 {
		return nil, fmt.Errorf("授权失败:%s", phone.ErrMsg)
	}
	phoneInfo := phone.PhoneInfo

	var find *models.BaseUser
	find, err = s.baseUserCase.Find(ctx, &data.BaseUserCondition{
		Phone: phoneInfo.PhoneNumber,
	})
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, fmt.Errorf("授权失败")
	}
	if find != nil && find.ID != authInfo.UserId {
		return nil, fmt.Errorf("授权失败，手机号被占用")
	}

	user := &models.BaseUser{
		ID:    authInfo.UserId,
		Phone: phoneInfo.PhoneNumber,
	}
	err = s.baseUserCase.UpdateByID(ctx, user)
	if err != nil {
		log.Errorf("手机号授权[%s]", err.Error())
		return nil, errors.New("手机号授权失败")
	}
	return &app.PhoneAuthResponse{
		Phone: str.DesensitizePhone(user.Phone),
	}, nil
}

func (s *AuthServiceImpl) login(ctx context.Context, user *models.BaseUser) (*login.LoginResponse, error) {
	if user.Status != int32(common.Status_ENABLE) {
		return nil, errors.New("用户状态错误")
	}
	// 查询角色信息
	role, err := s.baseRoleCase.GetFromID(ctx, user.RoleID)
	if err != nil {
		return nil, errors.New("角色不存在")
	}

	// 生成访问令牌
	var accessToken, refreshToken string
	accessToken, refreshToken, err = s.UserToken.GenerateToken(&nmskitAuthData.UserTokenPayload{
		UserId:   user.ID,
		UserName: user.UserName,
		RoleId:   user.RoleID,
		RoleCode: role.Code,
		RoleName: role.Name,
		DeptId:   user.DeptID,
		OpenId:   user.Openid,
	})
	if err != nil {
		return nil, errors.New("登录失败")
	}

	// Token 有效期
	expiresIn := s.UserToken.GetAccessTokenExpires()

	return &login.LoginResponse{
		TokenType:    engine.BearerWord,
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    expiresIn,
	}, nil
}
