// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: app/auth.proto

package app

import (
	login "gitee.com/liujit/shop/server/api/login"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"` // 用户账号
	NickName      string                 `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"` // 用户昵称
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`    // 性别
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`       // 手机号
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_app_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserInfo) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 微信后台登录 - 请求
type WxLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 用户登录凭据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxLoginRequest) Reset() {
	*x = WxLoginRequest{}
	mi := &file_app_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxLoginRequest) ProtoMessage() {}

func (x *WxLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxLoginRequest.ProtoReflect.Descriptor instead.
func (*WxLoginRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{1}
}

func (x *WxLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UpdateUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NickName      string                 `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"` // 昵称
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`     // 头像URL
	Gender        int32                  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`    // 性别
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserInfoRequest) Reset() {
	*x = UpdateUserInfoRequest{}
	mi := &file_app_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInfoRequest) ProtoMessage() {}

func (x *UpdateUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserInfoRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserInfoRequest) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type PhoneAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 授权信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneAuthRequest) Reset() {
	*x = PhoneAuthRequest{}
	mi := &file_app_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneAuthRequest) ProtoMessage() {}

func (x *PhoneAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneAuthRequest.ProtoReflect.Descriptor instead.
func (*PhoneAuthRequest) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PhoneAuthRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PhoneAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"` // 手机号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneAuthResponse) Reset() {
	*x = PhoneAuthResponse{}
	mi := &file_app_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneAuthResponse) ProtoMessage() {}

func (x *PhoneAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneAuthResponse.ProtoReflect.Descriptor instead.
func (*PhoneAuthResponse) Descriptor() ([]byte, []int) {
	return file_app_auth_proto_rawDescGZIP(), []int{4}
}

func (x *PhoneAuthResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

var File_app_auth_proto protoreflect.FileDescriptor

const file_app_auth_proto_rawDesc = "" +
	"\n" +
	"\x0eapp/auth.proto\x12\x03app\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11login/login.proto\"\xdd\x01\n" +
	"\bUserInfo\x12.\n" +
	"\buserName\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f用户账号R\buserName\x12.\n" +
	"\bnickName\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f用户昵称R\bnickName\x12$\n" +
	"\x06gender\x18\x03 \x01(\x05B\f\xbaG\t\x92\x02\x06性别R\x06gender\x12%\n" +
	"\x05phone\x18\x04 \x01(\tB\x0f\xbaG\f\x92\x02\t手机号R\x05phone\x12$\n" +
	"\x06avatar\x18\x05 \x01(\tB\f\xbaG\t\x92\x02\x06头像R\x06avatar\">\n" +
	"\x0eWxLoginRequest\x12,\n" +
	"\x04code\x18\x01 \x01(\tB\x18\xbaG\x15\x92\x02\x12用户登录凭据R\x04code\"\x90\x01\n" +
	"\x15UpdateUserInfoRequest\x12(\n" +
	"\bnickName\x18\x01 \x01(\tB\f\xbaG\t\x92\x02\x06昵称R\bnickName\x12'\n" +
	"\x06avatar\x18\x02 \x01(\tB\x0f\xbaG\f\x92\x02\t头像URLR\x06avatar\x12$\n" +
	"\x06gender\x18\x03 \x01(\x05B\f\xbaG\t\x92\x02\x06性别R\x06gender\":\n" +
	"\x10PhoneAuthRequest\x12&\n" +
	"\x04code\x18\x01 \x01(\tB\x12\xbaG\x0f\x92\x02\f授权信息R\x04code\":\n" +
	"\x11PhoneAuthResponse\x12%\n" +
	"\x05phone\x18\x01 \x01(\tB\x0f\xbaG\f\x92\x02\t手机号R\x05phone2\xde\x03\n" +
	"\vAuthService\x12R\n" +
	"\x05Login\x12\x13.login.LoginRequest\x1a\x14.login.LoginResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/app/auth/login\x12W\n" +
	"\aWxLogin\x12\x13.app.WxLoginRequest\x1a\x14.login.LoginResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/app/auth/login/wx\x12T\n" +
	"\vGetUserInfo\x12\x16.google.protobuf.Empty\x1a\r.app.UserInfo\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/app/auth/userInfo\x12g\n" +
	"\x0eUpdateUserInfo\x12\x1a.app.UpdateUserInfoRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\x1a\x16/api/app/auth/userInfo\x12c\n" +
	"\tPhoneAuth\x12\x15.app.PhoneAuthRequest\x1a\x16.app.PhoneAuthResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/app/auth/userInfo/phoneBj\n" +
	"\acom.appB\tAuthProtoP\x01Z(gitee.com/liujit/shop/server/api/app;app\xa2\x02\x03AXX\xaa\x02\x03App\xca\x02\x03App\xe2\x02\x0fApp\\GPBMetadata\xea\x02\x03Appb\x06proto3"

var (
	file_app_auth_proto_rawDescOnce sync.Once
	file_app_auth_proto_rawDescData []byte
)

func file_app_auth_proto_rawDescGZIP() []byte {
	file_app_auth_proto_rawDescOnce.Do(func() {
		file_app_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_auth_proto_rawDesc), len(file_app_auth_proto_rawDesc)))
	})
	return file_app_auth_proto_rawDescData
}

var file_app_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_auth_proto_goTypes = []any{
	(*UserInfo)(nil),              // 0: app.UserInfo
	(*WxLoginRequest)(nil),        // 1: app.WxLoginRequest
	(*UpdateUserInfoRequest)(nil), // 2: app.UpdateUserInfoRequest
	(*PhoneAuthRequest)(nil),      // 3: app.PhoneAuthRequest
	(*PhoneAuthResponse)(nil),     // 4: app.PhoneAuthResponse
	(*login.LoginRequest)(nil),    // 5: login.LoginRequest
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
	(*login.LoginResponse)(nil),   // 7: login.LoginResponse
}
var file_app_auth_proto_depIdxs = []int32{
	5, // 0: app.AuthService.Login:input_type -> login.LoginRequest
	1, // 1: app.AuthService.WxLogin:input_type -> app.WxLoginRequest
	6, // 2: app.AuthService.GetUserInfo:input_type -> google.protobuf.Empty
	2, // 3: app.AuthService.UpdateUserInfo:input_type -> app.UpdateUserInfoRequest
	3, // 4: app.AuthService.PhoneAuth:input_type -> app.PhoneAuthRequest
	7, // 5: app.AuthService.Login:output_type -> login.LoginResponse
	7, // 6: app.AuthService.WxLogin:output_type -> login.LoginResponse
	0, // 7: app.AuthService.GetUserInfo:output_type -> app.UserInfo
	6, // 8: app.AuthService.UpdateUserInfo:output_type -> google.protobuf.Empty
	4, // 9: app.AuthService.PhoneAuth:output_type -> app.PhoneAuthResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_auth_proto_init() }
func file_app_auth_proto_init() {
	if File_app_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_auth_proto_rawDesc), len(file_app_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_auth_proto_goTypes,
		DependencyIndexes: file_app_auth_proto_depIdxs,
		MessageInfos:      file_app_auth_proto_msgTypes,
	}.Build()
	File_app_auth_proto = out.File
	file_app_auth_proto_goTypes = nil
	file_app_auth_proto_depIdxs = nil
}
