// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: app/base_area.proto

package app

import (
	context "context"
	common "gitee.com/liujit/shop/server/api/common"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationBaseAreaServiceTreeBaseArea = "/app.BaseAreaService/TreeBaseArea"

type BaseAreaServiceHTTPServer interface {
	// TreeBaseArea 查询行政区域树形列表
	TreeBaseArea(context.Context, *emptypb.Empty) (*common.AppTreeOptionResponse, error)
}

func RegisterBaseAreaServiceHTTPServer(s *http.Server, srv BaseAreaServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/app/base/area/tree", _BaseAreaService_TreeBaseArea0_HTTP_Handler(srv))
}

func _BaseAreaService_TreeBaseArea0_HTTP_Handler(srv BaseAreaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationBaseAreaServiceTreeBaseArea)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TreeBaseArea(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*common.AppTreeOptionResponse)
		return ctx.Result(200, reply)
	}
}

type BaseAreaServiceHTTPClient interface {
	TreeBaseArea(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *common.AppTreeOptionResponse, err error)
}

type BaseAreaServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewBaseAreaServiceHTTPClient(client *http.Client) BaseAreaServiceHTTPClient {
	return &BaseAreaServiceHTTPClientImpl{client}
}

func (c *BaseAreaServiceHTTPClientImpl) TreeBaseArea(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*common.AppTreeOptionResponse, error) {
	var out common.AppTreeOptionResponse
	pattern := "/api/app/base/area/tree"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationBaseAreaServiceTreeBaseArea))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
