// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/shop_hot.proto

package app

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListShopHotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListShopHotRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListShopHotRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListShopHotRequestMultiError, or nil if none found.
func (m *ListShopHotRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListShopHotRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.ParentId != nil {
		// no validation rules for ParentId
	}

	if len(errors) > 0 {
		return ListShopHotRequestMultiError(errors)
	}

	return nil
}

// ListShopHotRequestMultiError is an error wrapping multiple validation errors
// returned by ListShopHotRequest.ValidateAll() if the designated constraints
// aren't met.
type ListShopHotRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListShopHotRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListShopHotRequestMultiError) AllErrors() []error { return m }

// ListShopHotRequestValidationError is the validation error returned by
// ListShopHotRequest.Validate if the designated constraints aren't met.
type ListShopHotRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListShopHotRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListShopHotRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListShopHotRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListShopHotRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListShopHotRequestValidationError) ErrorName() string {
	return "ListShopHotRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListShopHotRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListShopHotRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListShopHotRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListShopHotRequestValidationError{}

// Validate checks the field values on ListShopHotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListShopHotResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListShopHotResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListShopHotResponseMultiError, or nil if none found.
func (m *ListShopHotResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListShopHotResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListShopHotResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListShopHotResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListShopHotResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListShopHotResponseMultiError(errors)
	}

	return nil
}

// ListShopHotResponseMultiError is an error wrapping multiple validation
// errors returned by ListShopHotResponse.ValidateAll() if the designated
// constraints aren't met.
type ListShopHotResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListShopHotResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListShopHotResponseMultiError) AllErrors() []error { return m }

// ListShopHotResponseValidationError is the validation error returned by
// ListShopHotResponse.Validate if the designated constraints aren't met.
type ListShopHotResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListShopHotResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListShopHotResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListShopHotResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListShopHotResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListShopHotResponseValidationError) ErrorName() string {
	return "ListShopHotResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListShopHotResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListShopHotResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListShopHotResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListShopHotResponseValidationError{}

// Validate checks the field values on PageShopHotGoodsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageShopHotGoodsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageShopHotGoodsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageShopHotGoodsRequestMultiError, or nil if none found.
func (m *PageShopHotGoodsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageShopHotGoodsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for HotItemId

	// no validation rules for PageNum

	// no validation rules for PageSize

	if len(errors) > 0 {
		return PageShopHotGoodsRequestMultiError(errors)
	}

	return nil
}

// PageShopHotGoodsRequestMultiError is an error wrapping multiple validation
// errors returned by PageShopHotGoodsRequest.ValidateAll() if the designated
// constraints aren't met.
type PageShopHotGoodsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageShopHotGoodsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageShopHotGoodsRequestMultiError) AllErrors() []error { return m }

// PageShopHotGoodsRequestValidationError is the validation error returned by
// PageShopHotGoodsRequest.Validate if the designated constraints aren't met.
type PageShopHotGoodsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageShopHotGoodsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageShopHotGoodsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageShopHotGoodsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageShopHotGoodsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageShopHotGoodsRequestValidationError) ErrorName() string {
	return "PageShopHotGoodsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageShopHotGoodsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageShopHotGoodsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageShopHotGoodsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageShopHotGoodsRequestValidationError{}

// Validate checks the field values on PageShopHotGoodsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageShopHotGoodsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageShopHotGoodsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageShopHotGoodsResponseMultiError, or nil if none found.
func (m *PageShopHotGoodsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PageShopHotGoodsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageShopHotGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageShopHotGoodsResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageShopHotGoodsResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return PageShopHotGoodsResponseMultiError(errors)
	}

	return nil
}

// PageShopHotGoodsResponseMultiError is an error wrapping multiple validation
// errors returned by PageShopHotGoodsResponse.ValidateAll() if the designated
// constraints aren't met.
type PageShopHotGoodsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageShopHotGoodsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageShopHotGoodsResponseMultiError) AllErrors() []error { return m }

// PageShopHotGoodsResponseValidationError is the validation error returned by
// PageShopHotGoodsResponse.Validate if the designated constraints aren't met.
type PageShopHotGoodsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageShopHotGoodsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageShopHotGoodsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageShopHotGoodsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageShopHotGoodsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageShopHotGoodsResponseValidationError) ErrorName() string {
	return "PageShopHotGoodsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PageShopHotGoodsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageShopHotGoodsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageShopHotGoodsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageShopHotGoodsResponseValidationError{}

// Validate checks the field values on ShopHot with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShopHot) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShopHot with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ShopHotMultiError, or nil if none found.
func (m *ShopHot) ValidateAll() error {
	return m.validate(true)
}

func (m *ShopHot) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Desc

	if len(errors) > 0 {
		return ShopHotMultiError(errors)
	}

	return nil
}

// ShopHotMultiError is an error wrapping multiple validation errors returned
// by ShopHot.ValidateAll() if the designated constraints aren't met.
type ShopHotMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShopHotMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShopHotMultiError) AllErrors() []error { return m }

// ShopHotValidationError is the validation error returned by ShopHot.Validate
// if the designated constraints aren't met.
type ShopHotValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShopHotValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShopHotValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShopHotValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShopHotValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShopHotValidationError) ErrorName() string { return "ShopHotValidationError" }

// Error satisfies the builtin error interface
func (e ShopHotValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShopHot.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShopHotValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShopHotValidationError{}

// Validate checks the field values on ListShopHotItemResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListShopHotItemResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListShopHotItemResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListShopHotItemResponseMultiError, or nil if none found.
func (m *ListShopHotItemResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListShopHotItemResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	// no validation rules for Banner

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListShopHotItemResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListShopHotItemResponseValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListShopHotItemResponseValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListShopHotItemResponseMultiError(errors)
	}

	return nil
}

// ListShopHotItemResponseMultiError is an error wrapping multiple validation
// errors returned by ListShopHotItemResponse.ValidateAll() if the designated
// constraints aren't met.
type ListShopHotItemResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListShopHotItemResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListShopHotItemResponseMultiError) AllErrors() []error { return m }

// ListShopHotItemResponseValidationError is the validation error returned by
// ListShopHotItemResponse.Validate if the designated constraints aren't met.
type ListShopHotItemResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListShopHotItemResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListShopHotItemResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListShopHotItemResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListShopHotItemResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListShopHotItemResponseValidationError) ErrorName() string {
	return "ListShopHotItemResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListShopHotItemResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListShopHotItemResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListShopHotItemResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListShopHotItemResponseValidationError{}

// Validate checks the field values on ShopHotItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ShopHotItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ShopHotItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ShopHotItemMultiError, or
// nil if none found.
func (m *ShopHotItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ShopHotItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Title

	if len(errors) > 0 {
		return ShopHotItemMultiError(errors)
	}

	return nil
}

// ShopHotItemMultiError is an error wrapping multiple validation errors
// returned by ShopHotItem.ValidateAll() if the designated constraints aren't met.
type ShopHotItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ShopHotItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ShopHotItemMultiError) AllErrors() []error { return m }

// ShopHotItemValidationError is the validation error returned by
// ShopHotItem.Validate if the designated constraints aren't met.
type ShopHotItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ShopHotItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ShopHotItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ShopHotItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ShopHotItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ShopHotItemValidationError) ErrorName() string { return "ShopHotItemValidationError" }

// Error satisfies the builtin error interface
func (e ShopHotItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sShopHotItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ShopHotItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ShopHotItemValidationError{}
