// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: app/shop_hot.proto

package app

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListShopHotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      *int64                 `protobuf:"varint,1,opt,name=parentId,proto3,oneof" json:"parentId,omitempty"` // 父节点ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopHotRequest) Reset() {
	*x = ListShopHotRequest{}
	mi := &file_app_shop_hot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopHotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopHotRequest) ProtoMessage() {}

func (x *ListShopHotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopHotRequest.ProtoReflect.Descriptor instead.
func (*ListShopHotRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{0}
}

func (x *ListShopHotRequest) GetParentId() int64 {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return 0
}

type ListShopHotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页数据
	List          []*ShopHot `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopHotResponse) Reset() {
	*x = ListShopHotResponse{}
	mi := &file_app_shop_hot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopHotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopHotResponse) ProtoMessage() {}

func (x *ListShopHotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopHotResponse.ProtoReflect.Descriptor instead.
func (*ListShopHotResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{1}
}

func (x *ListShopHotResponse) GetList() []*ShopHot {
	if x != nil {
		return x.List
	}
	return nil
}

type PageShopHotGoodsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 选项id
	HotItemId int64 `protobuf:"varint,1,opt,name=hotItemId,proto3" json:"hotItemId,omitempty"`
	// 当前页码
	PageNum int64 `protobuf:"varint,101,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	// 每一页的行数
	PageSize      int64 `protobuf:"varint,102,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageShopHotGoodsRequest) Reset() {
	*x = PageShopHotGoodsRequest{}
	mi := &file_app_shop_hot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageShopHotGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageShopHotGoodsRequest) ProtoMessage() {}

func (x *PageShopHotGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageShopHotGoodsRequest.ProtoReflect.Descriptor instead.
func (*PageShopHotGoodsRequest) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{2}
}

func (x *PageShopHotGoodsRequest) GetHotItemId() int64 {
	if x != nil {
		return x.HotItemId
	}
	return 0
}

func (x *PageShopHotGoodsRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageShopHotGoodsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageShopHotGoodsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分页数据
	List []*Goods `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 总数
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageShopHotGoodsResponse) Reset() {
	*x = PageShopHotGoodsResponse{}
	mi := &file_app_shop_hot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageShopHotGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageShopHotGoodsResponse) ProtoMessage() {}

func (x *PageShopHotGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageShopHotGoodsResponse.ProtoReflect.Descriptor instead.
func (*PageShopHotGoodsResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{3}
}

func (x *PageShopHotGoodsResponse) GetList() []*Goods {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PageShopHotGoodsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ShopHot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 主键id
	// 标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 描述
	Desc string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	// 图片链接
	Picture       []string `protobuf:"bytes,4,rep,name=picture,proto3" json:"picture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopHot) Reset() {
	*x = ShopHot{}
	mi := &file_app_shop_hot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopHot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopHot) ProtoMessage() {}

func (x *ShopHot) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopHot.ProtoReflect.Descriptor instead.
func (*ShopHot) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{4}
}

func (x *ShopHot) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopHot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShopHot) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ShopHot) GetPicture() []string {
	if x != nil {
		return x.Picture
	}
	return nil
}

type ListShopHotItemResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 主键id
	// 标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 轮播图
	Banner string `protobuf:"bytes,3,opt,name=banner,proto3" json:"banner,omitempty"`
	// 选项
	List          []*ShopHotItem `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListShopHotItemResponse) Reset() {
	*x = ListShopHotItemResponse{}
	mi := &file_app_shop_hot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListShopHotItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListShopHotItemResponse) ProtoMessage() {}

func (x *ListShopHotItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListShopHotItemResponse.ProtoReflect.Descriptor instead.
func (*ListShopHotItemResponse) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{5}
}

func (x *ListShopHotItemResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListShopHotItemResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListShopHotItemResponse) GetBanner() string {
	if x != nil {
		return x.Banner
	}
	return ""
}

func (x *ListShopHotItemResponse) GetList() []*ShopHotItem {
	if x != nil {
		return x.List
	}
	return nil
}

type ShopHotItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 主键id
	// 标题
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopHotItem) Reset() {
	*x = ShopHotItem{}
	mi := &file_app_shop_hot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopHotItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopHotItem) ProtoMessage() {}

func (x *ShopHotItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_shop_hot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopHotItem.ProtoReflect.Descriptor instead.
func (*ShopHotItem) Descriptor() ([]byte, []int) {
	return file_app_shop_hot_proto_rawDescGZIP(), []int{6}
}

func (x *ShopHotItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShopHotItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_app_shop_hot_proto protoreflect.FileDescriptor

const file_app_shop_hot_proto_rawDesc = "" +
	"\n" +
	"\x12app/shop_hot.proto\x12\x03app\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x0fapp/goods.proto\"U\n" +
	"\x12ListShopHotRequest\x122\n" +
	"\bparentId\x18\x01 \x01(\x03B\x11\xbaG\x0e\x92\x02\v父节点IDH\x00R\bparentId\x88\x01\x01B\v\n" +
	"\t_parentId\"7\n" +
	"\x13ListShopHotResponse\x12 \n" +
	"\x04list\x18\x01 \x03(\v2\f.app.ShopHotR\x04list\"\xc3\x01\n" +
	"\x17PageShopHotGoodsRequest\x12,\n" +
	"\thotItemId\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b选项idR\thotItemId\x128\n" +
	"\apageNum\x18e \x01(\x03B\x1e\xbaG\x1b\x8a\x02\t\t\x00\x00\x00\x00\x00\x00\xf0?\x92\x02\f当前页码R\apageNum\x12@\n" +
	"\bpageSize\x18f \x01(\x03B$\xbaG!\x8a\x02\t\t\x00\x00\x00\x00\x00\x00$@\x92\x02\x12每一页的行数R\bpageSize\"P\n" +
	"\x18PageShopHotGoodsResponse\x12\x1e\n" +
	"\x04list\x18\x01 \x03(\v2\n" +
	".app.GoodsR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9d\x01\n" +
	"\aShopHot\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b主键idR\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\f\xbaG\t\x92\x02\x06标题R\x05title\x12 \n" +
	"\x04desc\x18\x03 \x01(\tB\f\xbaG\t\x92\x02\x06描述R\x04desc\x12,\n" +
	"\apicture\x18\x04 \x03(\tB\x12\xbaG\x0f\x92\x02\f图片链接R\apicture\"\xba\x01\n" +
	"\x17ListShopHotItemResponse\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b主键idR\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\f\xbaG\t\x92\x02\x06标题R\x05title\x12'\n" +
	"\x06banner\x18\x03 \x01(\tB\x0f\xbaG\f\x92\x02\t轮播图R\x06banner\x122\n" +
	"\x04list\x18\x04 \x03(\v2\x10.app.ShopHotItemB\f\xbaG\t\x92\x02\x06选项R\x04list\"Q\n" +
	"\vShopHotItem\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\x03B\x0e\xbaG\v\x92\x02\b主键idR\x02id\x12\"\n" +
	"\x05title\x18\x02 \x01(\tB\f\xbaG\t\x92\x02\x06标题R\x05title2\xcc\x02\n" +
	"\x0eShopHotService\x12Z\n" +
	"\vListShopHot\x12\x16.google.protobuf.Empty\x1a\x18.app.ListShopHotResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/app/shop/hot\x12l\n" +
	"\x0fListShopHotItem\x12\x1b.google.protobuf.Int64Value\x1a\x1c.app.ListShopHotItemResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/app/shop/hot/item\x12p\n" +
	"\x10PageShopHotGoods\x12\x1c.app.PageShopHotGoodsRequest\x1a\x1d.app.PageShopHotGoodsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/app/shop/hot/goodsBm\n" +
	"\acom.appB\fShopHotProtoP\x01Z(gitee.com/liujit/shop/server/api/app;app\xa2\x02\x03AXX\xaa\x02\x03App\xca\x02\x03App\xe2\x02\x0fApp\\GPBMetadata\xea\x02\x03Appb\x06proto3"

var (
	file_app_shop_hot_proto_rawDescOnce sync.Once
	file_app_shop_hot_proto_rawDescData []byte
)

func file_app_shop_hot_proto_rawDescGZIP() []byte {
	file_app_shop_hot_proto_rawDescOnce.Do(func() {
		file_app_shop_hot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_shop_hot_proto_rawDesc), len(file_app_shop_hot_proto_rawDesc)))
	})
	return file_app_shop_hot_proto_rawDescData
}

var file_app_shop_hot_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_shop_hot_proto_goTypes = []any{
	(*ListShopHotRequest)(nil),       // 0: app.ListShopHotRequest
	(*ListShopHotResponse)(nil),      // 1: app.ListShopHotResponse
	(*PageShopHotGoodsRequest)(nil),  // 2: app.PageShopHotGoodsRequest
	(*PageShopHotGoodsResponse)(nil), // 3: app.PageShopHotGoodsResponse
	(*ShopHot)(nil),                  // 4: app.ShopHot
	(*ListShopHotItemResponse)(nil),  // 5: app.ListShopHotItemResponse
	(*ShopHotItem)(nil),              // 6: app.ShopHotItem
	(*Goods)(nil),                    // 7: app.Goods
	(*emptypb.Empty)(nil),            // 8: google.protobuf.Empty
	(*wrapperspb.Int64Value)(nil),    // 9: google.protobuf.Int64Value
}
var file_app_shop_hot_proto_depIdxs = []int32{
	4, // 0: app.ListShopHotResponse.list:type_name -> app.ShopHot
	7, // 1: app.PageShopHotGoodsResponse.list:type_name -> app.Goods
	6, // 2: app.ListShopHotItemResponse.list:type_name -> app.ShopHotItem
	8, // 3: app.ShopHotService.ListShopHot:input_type -> google.protobuf.Empty
	9, // 4: app.ShopHotService.ListShopHotItem:input_type -> google.protobuf.Int64Value
	2, // 5: app.ShopHotService.PageShopHotGoods:input_type -> app.PageShopHotGoodsRequest
	1, // 6: app.ShopHotService.ListShopHot:output_type -> app.ListShopHotResponse
	5, // 7: app.ShopHotService.ListShopHotItem:output_type -> app.ListShopHotItemResponse
	3, // 8: app.ShopHotService.PageShopHotGoods:output_type -> app.PageShopHotGoodsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_shop_hot_proto_init() }
func file_app_shop_hot_proto_init() {
	if File_app_shop_hot_proto != nil {
		return
	}
	file_app_goods_proto_init()
	file_app_shop_hot_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_shop_hot_proto_rawDesc), len(file_app_shop_hot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_shop_hot_proto_goTypes,
		DependencyIndexes: file_app_shop_hot_proto_depIdxs,
		MessageInfos:      file_app_shop_hot_proto_msgTypes,
	}.Build()
	File_app_shop_hot_proto = out.File
	file_app_shop_hot_proto_goTypes = nil
	file_app_shop_hot_proto_depIdxs = nil
}
