// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: app/shop_hot.proto

package app

import (
	context "context"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationShopHotServiceListShopHot = "/app.ShopHotService/ListShopHot"
const OperationShopHotServiceListShopHotItem = "/app.ShopHotService/ListShopHotItem"
const OperationShopHotServicePageShopHotGoods = "/app.ShopHotService/PageShopHotGoods"

type ShopHotServiceHTTPServer interface {
	// ListShopHot 查询热门推荐列表
	ListShopHot(context.Context, *emptypb.Empty) (*ListShopHotResponse, error)
	// ListShopHotItem 查询热门推荐选项
	ListShopHotItem(context.Context, *wrapperspb.Int64Value) (*ListShopHotItemResponse, error)
	// PageShopHotGoods 查询热门推荐商品
	PageShopHotGoods(context.Context, *PageShopHotGoodsRequest) (*PageShopHotGoodsResponse, error)
}

func RegisterShopHotServiceHTTPServer(s *http.Server, srv ShopHotServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/app/shop/hot", _ShopHotService_ListShopHot0_HTTP_Handler(srv))
	r.GET("/api/app/shop/hot/item", _ShopHotService_ListShopHotItem0_HTTP_Handler(srv))
	r.GET("/api/app/shop/hot/goods", _ShopHotService_PageShopHotGoods0_HTTP_Handler(srv))
}

func _ShopHotService_ListShopHot0_HTTP_Handler(srv ShopHotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopHotServiceListShopHot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShopHot(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShopHotResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopHotService_ListShopHotItem0_HTTP_Handler(srv ShopHotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopHotServiceListShopHotItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShopHotItem(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListShopHotItemResponse)
		return ctx.Result(200, reply)
	}
}

func _ShopHotService_PageShopHotGoods0_HTTP_Handler(srv ShopHotServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageShopHotGoodsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationShopHotServicePageShopHotGoods)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PageShopHotGoods(ctx, req.(*PageShopHotGoodsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageShopHotGoodsResponse)
		return ctx.Result(200, reply)
	}
}

type ShopHotServiceHTTPClient interface {
	ListShopHot(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListShopHotResponse, err error)
	ListShopHotItem(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *ListShopHotItemResponse, err error)
	PageShopHotGoods(ctx context.Context, req *PageShopHotGoodsRequest, opts ...http.CallOption) (rsp *PageShopHotGoodsResponse, err error)
}

type ShopHotServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewShopHotServiceHTTPClient(client *http.Client) ShopHotServiceHTTPClient {
	return &ShopHotServiceHTTPClientImpl{client}
}

func (c *ShopHotServiceHTTPClientImpl) ListShopHot(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListShopHotResponse, error) {
	var out ListShopHotResponse
	pattern := "/api/app/shop/hot"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopHotServiceListShopHot))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopHotServiceHTTPClientImpl) ListShopHotItem(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*ListShopHotItemResponse, error) {
	var out ListShopHotItemResponse
	pattern := "/api/app/shop/hot/item"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopHotServiceListShopHotItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *ShopHotServiceHTTPClientImpl) PageShopHotGoods(ctx context.Context, in *PageShopHotGoodsRequest, opts ...http.CallOption) (*PageShopHotGoodsResponse, error) {
	var out PageShopHotGoodsResponse
	pattern := "/api/app/shop/hot/goods"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationShopHotServicePageShopHotGoods))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
