// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: app/user_store.proto

package app

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "gitee.com/liujit/shop/server/api/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.UserStoreStatus(0)
)

// Validate checks the field values on UserStore with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserStore) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserStore with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserStoreMultiError, or nil
// if none found.
func (m *UserStore) ValidateAll() error {
	return m.validate(true)
}

func (m *UserStore) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Detail

	// no validation rules for Status

	// no validation rules for Remark

	if len(errors) > 0 {
		return UserStoreMultiError(errors)
	}

	return nil
}

// UserStoreMultiError is an error wrapping multiple validation errors returned
// by UserStore.ValidateAll() if the designated constraints aren't met.
type UserStoreMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserStoreMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserStoreMultiError) AllErrors() []error { return m }

// UserStoreValidationError is the validation error returned by
// UserStore.Validate if the designated constraints aren't met.
type UserStoreValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserStoreValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserStoreValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserStoreValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserStoreValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserStoreValidationError) ErrorName() string { return "UserStoreValidationError" }

// Error satisfies the builtin error interface
func (e UserStoreValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserStore.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserStoreValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserStoreValidationError{}

// Validate checks the field values on UserStoreForm with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserStoreForm) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserStoreForm with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserStoreFormMultiError, or
// nil if none found.
func (m *UserStoreForm) ValidateAll() error {
	return m.validate(true)
}

func (m *UserStoreForm) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Name

	// no validation rules for Detail

	if len(errors) > 0 {
		return UserStoreFormMultiError(errors)
	}

	return nil
}

// UserStoreFormMultiError is an error wrapping multiple validation errors
// returned by UserStoreForm.ValidateAll() if the designated constraints
// aren't met.
type UserStoreFormMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserStoreFormMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserStoreFormMultiError) AllErrors() []error { return m }

// UserStoreFormValidationError is the validation error returned by
// UserStoreForm.Validate if the designated constraints aren't met.
type UserStoreFormValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserStoreFormValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserStoreFormValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserStoreFormValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserStoreFormValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserStoreFormValidationError) ErrorName() string { return "UserStoreFormValidationError" }

// Error satisfies the builtin error interface
func (e UserStoreFormValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserStoreForm.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserStoreFormValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserStoreFormValidationError{}
