// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.0.1
// - protoc             (unknown)
// source: app/user_cart.proto

package app

import (
	context "context"
	http "go.newcapec.cn/ncttools/nmskit/transport/http"
	binding "go.newcapec.cn/ncttools/nmskit/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Nms package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserCartServiceCountUserCart = "/app.UserCartService/CountUserCart"
const OperationUserCartServiceCreateUserCart = "/app.UserCartService/CreateUserCart"
const OperationUserCartServiceDeleteUserCart = "/app.UserCartService/DeleteUserCart"
const OperationUserCartServiceListUserCart = "/app.UserCartService/ListUserCart"
const OperationUserCartServiceSelectedUserCart = "/app.UserCartService/SelectedUserCart"
const OperationUserCartServiceSetUserCartStatus = "/app.UserCartService/SetUserCartStatus"
const OperationUserCartServiceUpdateUserCart = "/app.UserCartService/UpdateUserCart"

type UserCartServiceHTTPServer interface {
	// CountUserCart 查询用户购物车数量
	CountUserCart(context.Context, *emptypb.Empty) (*wrapperspb.Int32Value, error)
	// CreateUserCart 创建用户购物车
	CreateUserCart(context.Context, *CreateUserCartRequest) (*emptypb.Empty, error)
	// DeleteUserCart 删除用户购物车
	DeleteUserCart(context.Context, *wrapperspb.Int64Value) (*emptypb.Empty, error)
	// ListUserCart 查询用户购物车列表
	ListUserCart(context.Context, *emptypb.Empty) (*ListUserCartResponse, error)
	// SelectedUserCart 设置全选
	SelectedUserCart(context.Context, *SelectedUserCartRequest) (*emptypb.Empty, error)
	// SetUserCartStatus 设置状态
	SetUserCartStatus(context.Context, *SetUserCartStatusRequest) (*emptypb.Empty, error)
	// UpdateUserCart 更新用户购物车
	UpdateUserCart(context.Context, *UpdateUserCartRequest) (*emptypb.Empty, error)
}

func RegisterUserCartServiceHTTPServer(s *http.Server, srv UserCartServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/app/user/cart/count", _UserCartService_CountUserCart0_HTTP_Handler(srv))
	r.GET("/api/app/user/cart/list", _UserCartService_ListUserCart0_HTTP_Handler(srv))
	r.POST("/api/app/user/cart", _UserCartService_CreateUserCart0_HTTP_Handler(srv))
	r.PUT("/api/app/user/cart", _UserCartService_UpdateUserCart0_HTTP_Handler(srv))
	r.DELETE("/api/app/user/cart/{value}", _UserCartService_DeleteUserCart0_HTTP_Handler(srv))
	r.PUT("/api/app/user/cart/{id}/status", _UserCartService_SetUserCartStatus0_HTTP_Handler(srv))
	r.PUT("/api/app/user/cart/selected", _UserCartService_SelectedUserCart0_HTTP_Handler(srv))
}

func _UserCartService_CountUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceCountUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CountUserCart(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*wrapperspb.Int32Value)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_ListUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceListUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListUserCart(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListUserCartResponse)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_CreateUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateUserCartRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceCreateUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateUserCart(ctx, req.(*CreateUserCartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_UpdateUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateUserCartRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceUpdateUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateUserCart(ctx, req.(*UpdateUserCartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_DeleteUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in wrapperspb.Int64Value
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceDeleteUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteUserCart(ctx, req.(*wrapperspb.Int64Value))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_SetUserCartStatus0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetUserCartStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceSetUserCartStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetUserCartStatus(ctx, req.(*SetUserCartStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _UserCartService_SelectedUserCart0_HTTP_Handler(srv UserCartServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SelectedUserCartRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserCartServiceSelectedUserCart)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SelectedUserCart(ctx, req.(*SelectedUserCartRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type UserCartServiceHTTPClient interface {
	CountUserCart(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *wrapperspb.Int32Value, err error)
	CreateUserCart(ctx context.Context, req *CreateUserCartRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteUserCart(ctx context.Context, req *wrapperspb.Int64Value, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	ListUserCart(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListUserCartResponse, err error)
	SelectedUserCart(ctx context.Context, req *SelectedUserCartRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	SetUserCartStatus(ctx context.Context, req *SetUserCartStatusRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	UpdateUserCart(ctx context.Context, req *UpdateUserCartRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type UserCartServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserCartServiceHTTPClient(client *http.Client) UserCartServiceHTTPClient {
	return &UserCartServiceHTTPClientImpl{client}
}

func (c *UserCartServiceHTTPClientImpl) CountUserCart(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*wrapperspb.Int32Value, error) {
	var out wrapperspb.Int32Value
	pattern := "/api/app/user/cart/count"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCartServiceCountUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) CreateUserCart(ctx context.Context, in *CreateUserCartRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/app/user/cart"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCartServiceCreateUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) DeleteUserCart(ctx context.Context, in *wrapperspb.Int64Value, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/app/user/cart/{value}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCartServiceDeleteUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) ListUserCart(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListUserCartResponse, error) {
	var out ListUserCartResponse
	pattern := "/api/app/user/cart/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationUserCartServiceListUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) SelectedUserCart(ctx context.Context, in *SelectedUserCartRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/app/user/cart/selected"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCartServiceSelectedUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) SetUserCartStatus(ctx context.Context, in *SetUserCartStatusRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/app/user/cart/{id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCartServiceSetUserCartStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *UserCartServiceHTTPClientImpl) UpdateUserCart(ctx context.Context, in *UpdateUserCartRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/app/user/cart"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserCartServiceUpdateUserCart))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
