// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: app/user_store.proto

package app

import (
	common "gitee.com/liujit/shop/server/api/common"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户门店信息
type UserStore struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                      // 用户门店ID
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 门店名称
	Address         []string               `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`                             // 省市区
	Detail          string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                               // 详细地址
	Picture         []string               `protobuf:"bytes,5,rep,name=picture,proto3" json:"picture,omitempty"`                             // 门店照片
	BusinessLicense []string               `protobuf:"bytes,6,rep,name=businessLicense,proto3" json:"businessLicense,omitempty"`             // 营业执照
	AddressName     []string               `protobuf:"bytes,10,rep,name=addressName,proto3" json:"addressName,omitempty"`                    // 省市区
	Status          common.UserStoreStatus `protobuf:"varint,51,opt,name=status,proto3,enum=common.UserStoreStatus" json:"status,omitempty"` // 状态
	Remark          string                 `protobuf:"bytes,52,opt,name=remark,proto3" json:"remark,omitempty"`                              // 备注名
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserStore) Reset() {
	*x = UserStore{}
	mi := &file_app_user_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStore) ProtoMessage() {}

func (x *UserStore) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStore.ProtoReflect.Descriptor instead.
func (*UserStore) Descriptor() ([]byte, []int) {
	return file_app_user_store_proto_rawDescGZIP(), []int{0}
}

func (x *UserStore) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserStore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserStore) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserStore) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UserStore) GetPicture() []string {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *UserStore) GetBusinessLicense() []string {
	if x != nil {
		return x.BusinessLicense
	}
	return nil
}

func (x *UserStore) GetAddressName() []string {
	if x != nil {
		return x.AddressName
	}
	return nil
}

func (x *UserStore) GetStatus() common.UserStoreStatus {
	if x != nil {
		return x.Status
	}
	return common.UserStoreStatus(0)
}

func (x *UserStore) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 用户门店信息
type UserStoreForm struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                          // 用户门店ID
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 门店名称
	Address         []string               `protobuf:"bytes,3,rep,name=address,proto3" json:"address,omitempty"`                 // 省市区
	Detail          string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`                   // 详细地址
	Picture         []string               `protobuf:"bytes,5,rep,name=picture,proto3" json:"picture,omitempty"`                 // 门店照片
	BusinessLicense []string               `protobuf:"bytes,6,rep,name=businessLicense,proto3" json:"businessLicense,omitempty"` // 营业执照
	AddressName     []string               `protobuf:"bytes,10,rep,name=addressName,proto3" json:"addressName,omitempty"`        // 省市区
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserStoreForm) Reset() {
	*x = UserStoreForm{}
	mi := &file_app_user_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStoreForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStoreForm) ProtoMessage() {}

func (x *UserStoreForm) ProtoReflect() protoreflect.Message {
	mi := &file_app_user_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStoreForm.ProtoReflect.Descriptor instead.
func (*UserStoreForm) Descriptor() ([]byte, []int) {
	return file_app_user_store_proto_rawDescGZIP(), []int{1}
}

func (x *UserStoreForm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserStoreForm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserStoreForm) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserStoreForm) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UserStoreForm) GetPicture() []string {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *UserStoreForm) GetBusinessLicense() []string {
	if x != nil {
		return x.BusinessLicense
	}
	return nil
}

func (x *UserStoreForm) GetAddressName() []string {
	if x != nil {
		return x.AddressName
	}
	return nil
}

var File_app_user_store_proto protoreflect.FileDescriptor

const file_app_user_store_proto_rawDesc = "" +
	"\n" +
	"\x14app/user_store.proto\x12\x03app\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x11common/enum.proto\"\xb7\x03\n" +
	"\tUserStore\x12$\n" +
	"\x02id\x18\x01 \x01(\x03B\x14\xbaG\x11\x92\x02\x0e用户门店IDR\x02id\x12&\n" +
	"\x04name\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f门店名称R\x04name\x12)\n" +
	"\aaddress\x18\x03 \x03(\tB\x0f\xbaG\f\x92\x02\t省市区R\aaddress\x12*\n" +
	"\x06detail\x18\x04 \x01(\tB\x12\xbaG\x0f\x92\x02\f详细地址R\x06detail\x12,\n" +
	"\apicture\x18\x05 \x03(\tB\x12\xbaG\x0f\x92\x02\f门店照片R\apicture\x12<\n" +
	"\x0fbusinessLicense\x18\x06 \x03(\tB\x12\xbaG\x0f\x92\x02\f营业执照R\x0fbusinessLicense\x121\n" +
	"\vaddressName\x18\n" +
	" \x03(\tB\x0f\xbaG\f\x92\x02\t省市区R\vaddressName\x12=\n" +
	"\x06status\x183 \x01(\x0e2\x17.common.UserStoreStatusB\f\xbaG\t\x92\x02\x06状态R\x06status\x12'\n" +
	"\x06remark\x184 \x01(\tB\x0f\xbaG\f\x92\x02\t备注名R\x06remark\"\xd3\x02\n" +
	"\rUserStoreForm\x12$\n" +
	"\x02id\x18\x01 \x01(\x03B\x14\xbaG\x11\x92\x02\x0e用户门店IDR\x02id\x12&\n" +
	"\x04name\x18\x02 \x01(\tB\x12\xbaG\x0f\x92\x02\f门店名称R\x04name\x12)\n" +
	"\aaddress\x18\x03 \x03(\tB\x0f\xbaG\f\x92\x02\t省市区R\aaddress\x12*\n" +
	"\x06detail\x18\x04 \x01(\tB\x12\xbaG\x0f\x92\x02\f详细地址R\x06detail\x12,\n" +
	"\apicture\x18\x05 \x03(\tB\x12\xbaG\x0f\x92\x02\f门店照片R\apicture\x12<\n" +
	"\x0fbusinessLicense\x18\x06 \x03(\tB\x12\xbaG\x0f\x92\x02\f营业执照R\x0fbusinessLicense\x121\n" +
	"\vaddressName\x18\n" +
	" \x03(\tB\x0f\xbaG\f\x92\x02\t省市区R\vaddressName2\xaa\x02\n" +
	"\x10UserStoreService\x12S\n" +
	"\fGetUserStore\x12\x16.google.protobuf.Empty\x1a\x0e.app.UserStore\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/app/user/store\x12]\n" +
	"\x0fCreateUserStore\x12\x12.app.UserStoreForm\x1a\x16.google.protobuf.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/app/user/store\x12b\n" +
	"\x0fUpdateUserStore\x12\x12.app.UserStoreForm\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/app/user/store/{id}Bo\n" +
	"\acom.appB\x0eUserStoreProtoP\x01Z(gitee.com/liujit/shop/server/api/app;app\xa2\x02\x03AXX\xaa\x02\x03App\xca\x02\x03App\xe2\x02\x0fApp\\GPBMetadata\xea\x02\x03Appb\x06proto3"

var (
	file_app_user_store_proto_rawDescOnce sync.Once
	file_app_user_store_proto_rawDescData []byte
)

func file_app_user_store_proto_rawDescGZIP() []byte {
	file_app_user_store_proto_rawDescOnce.Do(func() {
		file_app_user_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_user_store_proto_rawDesc), len(file_app_user_store_proto_rawDesc)))
	})
	return file_app_user_store_proto_rawDescData
}

var file_app_user_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_user_store_proto_goTypes = []any{
	(*UserStore)(nil),           // 0: app.UserStore
	(*UserStoreForm)(nil),       // 1: app.UserStoreForm
	(common.UserStoreStatus)(0), // 2: common.UserStoreStatus
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_app_user_store_proto_depIdxs = []int32{
	2, // 0: app.UserStore.status:type_name -> common.UserStoreStatus
	3, // 1: app.UserStoreService.GetUserStore:input_type -> google.protobuf.Empty
	1, // 2: app.UserStoreService.CreateUserStore:input_type -> app.UserStoreForm
	1, // 3: app.UserStoreService.UpdateUserStore:input_type -> app.UserStoreForm
	0, // 4: app.UserStoreService.GetUserStore:output_type -> app.UserStore
	3, // 5: app.UserStoreService.CreateUserStore:output_type -> google.protobuf.Empty
	3, // 6: app.UserStoreService.UpdateUserStore:output_type -> google.protobuf.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_user_store_proto_init() }
func file_app_user_store_proto_init() {
	if File_app_user_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_user_store_proto_rawDesc), len(file_app_user_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_user_store_proto_goTypes,
		DependencyIndexes: file_app_user_store_proto_depIdxs,
		MessageInfos:      file_app_user_store_proto_msgTypes,
	}.Build()
	File_app_user_store_proto = out.File
	file_app_user_store_proto_goTypes = nil
	file_app_user_store_proto_depIdxs = nil
}
