data:
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:112233@tcp(127.0.0.1:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
    openLog: true
#
#  redis:
#    addr:
#      - 127.0.0.1:6379
#    password:
#    db: 1
