// Code generated by protoc-gen-go-grpc-impl.
// versions:
// - protoc-gen-go-grpc-impl v0.0.2
// - protoc             (unknown)
// source: config/config.proto

package config

import (
	"context"
	"errors"
	"gitee.com/liujit/shop/server/api/config"
	"gitee.com/liujit/shop/server/pkg/core"
	"gitee.com/liujit/shop/server/pkg/service/config/biz"
	"go.newcapec.cn/ncttools/nmskit/log"
	"google.golang.org/grpc"
)

const _ = grpc.SupportPackageIsVersion7

// ConfigServiceImpl is the server API for ConfigService service implement.
type ConfigServiceImpl struct {
	config.UnimplementedConfigServiceServer
	*core.ShopCore
	configCase *biz.ConfigCase
}

// NewConfigServiceImpl create a service implement.
// 系统配置公共服务
func NewConfigServiceImpl(
	sc *core.ShopCore,
	configCase *biz.ConfigCase,
) *ConfigServiceImpl {
	var ss = ConfigServiceImpl{
		ShopCore:   sc,
		configCase: configCase,
	}
	log.Debug("NewConfigServiceImpl.")
	return &ss
}

// GetConfig
// 获取系统配置
func (s *ConfigServiceImpl) GetConfig(ctx context.Context, req *config.ConfigRequest) (*config.ConfigResponse, error) {
	resp, err := s.configCase.GetConfig(ctx, req)
	if err != nil {
		log.Error("GetConfig err:", err.Error())
		return nil, errors.New("获取系统配置失败")
	}

	return resp, nil
}
