// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameBaseArea = "base_area"

// BaseArea 行政区域信息
type BaseArea struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:区域ID" json:"id"`                            // 区域ID
	ParentID int64  `gorm:"column:parent_id;type:bigint;index:idx_base_area_parent_id,priority:1;comment:父级区域ID" json:"parent_id"` // 父级区域ID
	Name     string `gorm:"column:name;type:varchar(50);comment:区域名称" json:"name"`                                                 // 区域名称
}

// TableName BaseArea's table name
func (*BaseArea) TableName() string {
	return TableNameBaseArea
}
