// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameOrder = "order"

// Order 订单信息表
type Order struct {
	ID           int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:订单ID" json:"id"`                             // 订单ID
	OrderNo      string         `gorm:"column:order_no;type:varchar(20);uniqueIndex:unique_order_info,priority:1;comment:订单编号" json:"order_no"` // 订单编号
	UserID       int64          `gorm:"column:user_id;type:bigint;comment:用户id" json:"user_id"`                                                 // 用户id
	PayMoney     int64          `gorm:"column:pay_money;type:bigint;comment:实际支付金额" json:"pay_money"`                                           // 实际支付金额
	TotalMoney   int64          `gorm:"column:total_money;type:bigint;comment:总价" json:"total_money"`                                           // 总价
	PostFee      int64          `gorm:"column:post_fee;type:bigint;comment:优惠金额" json:"post_fee"`                                               // 优惠金额
	GoodsNum     int64          `gorm:"column:goods_num;type:bigint;comment:商品总数" json:"goods_num"`                                             // 商品总数
	PayType      int32          `gorm:"column:pay_type;type:tinyint;comment:支付方式：枚举【OrderPayType】" json:"pay_type"`                             // 支付方式：枚举【OrderPayType】
	PayChannel   int32          `gorm:"column:pay_channel;type:tinyint;comment:支付渠道：枚举【OrderPayChannel】" json:"pay_channel"`                    // 支付渠道：枚举【OrderPayChannel】
	DeliveryTime int32          `gorm:"column:delivery_time;type:tinyint;comment:配送时间：枚举【OrderDeliveryTime】" json:"delivery_time"`              // 配送时间：枚举【OrderDeliveryTime】
	Status       int32          `gorm:"column:status;type:tinyint;comment:状态：枚举【OrderStatus】" json:"status"`                                    // 状态：枚举【OrderStatus】
	Remark       string         `gorm:"column:remark;type:varchar(255);comment:订单备注" json:"remark"`                                             // 订单备注
	CreatedAt    time.Time      `gorm:"column:created_at;type:datetime;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:datetime;comment:更新时间" json:"updated_at"`                                         // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                         // 删除时间
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
